apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: auto-yt-dl
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/auto-yt-dl/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

