metadata:
    name: pgadmin
    namespace: pgadmin
spec:
    interval: 15m
    chart:
        spec:
            chart: pgadmin
            version: 16.1.4
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: pgadmin
    values:
        TZ: Europe/London
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        ingress:
            main:
                enabled: true
                hosts:
                    - host: pgadmin.musson-lan.uk
                      paths:
                        - path: /
                          pathType: Prefix
                ingressClassName: ""
                integrations:
                    certManager:
                        certificateIssuer: cloudflare-prod
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: allowlist-private
                              namespace: ""
        persistence:
            config:
                enabled: true
                mountPath: /var/lib/pgadmin
                readOnly: false
                storageClass: ""
        release_name: pgadmin
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                fsGroup: 5050
                readOnlyRootFilesystem: false
                runAsGroup: 5050
                runAsNonRoot: true
                runAsUser: 5050
            pod:
                fsGroup: 5050
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                ports:
                    main:
                        port: 10024
                        targetPort: 80
                type: ClusterIP
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                PGADMIN_DEFAULT_EMAIL: jtmusson@hey.com
                                PGADMIN_DEFAULT_PASSWORD: REPLACED
                            probes:
                                liveness:
                                    enabled: true
                                    path: /misc/ping
                                    type: http
                                readiness:
                                    enabled: true
                                    path: /misc/ping
                                    type: http
                                startup:
                                    enabled: true
                                    path: /misc/ping
                                    type: http
                replicas: 1
                type: Deployment
