---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: handbrake
  namespace: handbrake
spec:
  interval: 15m
  chart:
    spec:
      chart: handbrake
      version: 23.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      backblaze:
        accessKey: "${B2_ACCESSKEY}"
        bucket: "${B2_BUCKET}"
        encrKey: "${B2_ENCRKEY}"
        secretKey: "${B2_SECRETKEY}"
        type: s3
        url: "${B2_URL}"
    handbrake:
      AUTOMATED_CONVERSION_FORMAT: mkv
      AUTOMATED_CONVERSION_KEEP_SOURCE: false
      AUTOMATED_CONVERSION_NON_VIDEO_FILE_ACTION: ignore
      AUTOMATED_CONVERSION_PRESET: General/HQ 1080p30 Surround Subtitles QSV
      DISPLAY_HEIGHT: 768
      DISPLAY_WIDTH: 1280
      ENABLE_CJK_FONT: false
      KEEP_APP_RUNNING: true
      SECURE_CONNECTION: false
      autoconv: true
      gui: false
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: false
      output:
        path: /mnt/pool0/movies/_Pending
        server: 10.242.1.242
        type: nfs
#      watch:
#        enabled: true
#        path: /mnt/pool0/movies/_MKV
#        server: 10.242.1.242
#        type: nfs
#        mountPath: "/watch"
    securityContext:
      container:
        PUID: 568
        UMASK: "0022"
        runAsUser: 0
        runAsGroup: 0
#       allowPrivilegeEscalation: true
#       privileged: true
      pod:
        fsGroup: 3010
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: []
    service:
      main:
        ports:
          main:
            port: 10053
            targetPort: 5800
        type: ClusterIP
#      vnc:
#        ports:
#          vnc:
#            port: 10055
#            targetPort: 5900
#        type: ClusterIP
    ingress:
      main:
        enabled: true
        hosts:
          - host: "handbrake-hydra.${BASE_URL}"
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: "cloudflare-prod"
            enabled: true
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: "allowlist-private"
                namespace: "traefik"
            homepage:
              enabled: true
              group: Ripping