metadata:
    name: handbrake
    namespace: handbrake
spec:
    interval: 15m
    chart:
        spec:
            chart: handbrake
            version: 22.0.8
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: handbrake
    values:
        TZ: Europe/London
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        configmap:
            handbrake:
                data:
                    AUTOMATED_CONVERSION_FORMAT: '{{ .Values.handbrake.AUTOMATED_CONVERSION_FORMAT }}'
                    AUTOMATED_CONVERSION_KEEP_SOURCE: '{{ ternary "1" "0" .Values.handbrake.AUTOMATED_CONVERSION_KEEP_SOURCE }}'
                    AUTOMATED_CONVERSION_NON_VIDEO_FILE_ACTION: '{{ .Values.handbrake.AUTOMATED_CONVERSION_NON_VIDEO_FILE_ACTION }}'
                    AUTOMATED_CONVERSION_PRESET: '{{ .Values.handbrake.AUTOMATED_CONVERSION_PRESET }}'
                    DISPLAY_HEIGHT: '{{ .Values.handbrake.DISPLAY_HEIGHT }}'
                    DISPLAY_WIDTH: '{{ .Values.handbrake.DISPLAY_WIDTH }}'
                    ENABLE_CJK_FONT: '{{ ternary "1" "0" .Values.handbrake.ENABLE_CJK_FONT }}'
                    KEEP_APP_RUNNING: '{{ ternary "1" "0" .Values.handbrake.KEEP_APP_RUNNING }}'
                    SECURE_CONNECTION: '{{ ternary "1" "0" .Values.handbrake.SECURE_CONNECTION }}'
                enabled: true
        credentials:
            backblaze:
                accessKey: REPLACED
                bucket: Pluto-JTM
                encrKey: REPLACED
                name: backblaze
                path: ""
                secretKey: REPLACED
                type: s3
                url: https://s3.us-west-001.backblazeb2.com
        handbrake:
            AUTOMATED_CONVERSION_FORMAT: mkv
            AUTOMATED_CONVERSION_KEEP_SOURCE: false
            AUTOMATED_CONVERSION_NON_VIDEO_FILE_ACTION: ignore
            AUTOMATED_CONVERSION_PRESET: General/HQ 1080p30 Surround Subtitles QSV
            DISPLAY_HEIGHT: 768
            DISPLAY_WIDTH: 1280
            ENABLE_CJK_FONT: false
            KEEP_APP_RUNNING: true
            SECURE_CONNECTION: false
            autoconv: true
            gui: false
        ingress:
            main:
                enabled: true
                hosts:
                    - host: handbrake.musson-lan.uk
                      paths:
                        - path: /
                          pathType: Prefix
                ingressClassName: ""
                integrations:
                    certManager:
                        certificateIssuer: cloudflare-prod
                        enabled: true
                    homepage:
                        description: ""
                        enabled: true
                        group: Ripping
                        icon: ""
                        name: ""
                        widget:
                            custom:
                                key: ""
                            enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: allowlist-private
                              namespace: ""
        persistence:
            config:
                enabled: true
                mountPath: /config
                readOnly: false
                storageClass: ""
                volsync:
                    - credentials: backblaze
                      dest:
                        enabled: false
                      name: config
                      src:
                        enabled: true
                      type: restic
            output:
                autoPermissions:
                    enabled: false
                enabled: true
                mountPath: /output
                path: /mnt/pool0/movies/_Pending
                readOnly: false
                server: 10.242.1.242
                type: nfs
            storage:
                enabled: true
                mountPath: /storage
                readOnly: false
                storageClass: ""
        release_name: handbrake
        resources:
            limits:
                cpu: 7000m
                memory: 10Gi
        securityContext:
            container:
                UMASK: "0022"
                privileged: true
                readOnlyRootFilesystem: false
                runAsGroup: 0
                runAsNonRoot: false
                runAsUser: 0
            pod:
                fsGroup: 3010
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                ports:
                    main:
                        port: 10053
                        targetPort: 5800
                type: ClusterIP
            vnc:
                enabled: true
                ports:
                    vnc:
                        enabled: true
                        port: 10055
                        targetPort: 5900
                type: ClusterIP
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                VNC_PASSWORD: ""
                            envFrom:
                                - configMapRef:
                                    name: handbrake
                            probes:
                                liveness:
                                    type: tcp
                                readiness:
                                    type: tcp
                                startup:
                                    type: tcp
                            securityContext:
                                capabilities:
                                    add:
                                        - NET_BIND_SERVICE
                                        - KILL
                replicas: 1
                type: Deployment
