metadata:
    name: external-dns
    namespace: external-dns
spec:
    interval: 15m
    chart:
        spec:
            chart: external-dns
            version: 5.0.10
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: external-dns
    values:
        TZ: Europe/London
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        externaldns:
            cloudflareProxied: ""
            interval: 10m
            logFormat: text
            logLevel: info
            piholePassword: REPLACED
            piholeServer: https://valledan.musson-lan.uk
            policy: upsert-only
            provider: pihole
            registry: noop
            sources:
                - ingress
                - service
            triggerLoopOnEvent: "false"
            txtOwnerId: ""
            txtPrefix: ""
            txtSuffix: ""
        podOptions:
            automountServiceAccountToken: true
        rbac:
            main:
                clusterWide: true
                enabled: true
                primary: true
                rules:
                    - apiGroups:
                        - ""
                      resources:
                        - nodes
                      verbs:
                        - list
                        - watch
                    - apiGroups:
                        - ""
                      resources:
                        - pods
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - ""
                      resources:
                        - services
                        - endpoints
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - extensions
                        - networking.k8s.io
                      resources:
                        - ingresses
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - networking.istio.io
                      resources:
                        - gateways
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - networking.istio.io
                      resources:
                        - virtualservices
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - getambassador.io
                      resources:
                        - hosts
                        - ingresses
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - projectcontour.io
                      resources:
                        - httpproxies
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - externaldns.k8s.io
                      resources:
                        - dnsendpoints
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - externaldns.k8s.io
                      resources:
                        - dnsendpoints/status
                      verbs:
                        - '*'
                    - apiGroups:
                        - gateway.networking.k8s.io
                      resources:
                        - gateways
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - gateway.networking.k8s.io
                      resources:
                        - httproutes
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - ""
                      resources:
                        - namespaces
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - gateway.networking.k8s.io
                      resources:
                        - grpcroutes
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - gateway.networking.k8s.io
                      resources:
                        - tlsroutes
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - gateway.networking.k8s.io
                      resources:
                        - tcproutes
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - gateway.networking.k8s.io
                      resources:
                        - udproutes
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - gloo.solo.io
                        - gateway.solo.io
                      resources:
                        - proxies
                        - virtualservices
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - configuration.konghq.com
                      resources:
                        - tcpingresses
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - traefik.containo.us
                        - traefik.io
                      resources:
                        - ingressroutes
                        - ingressroutetcps
                        - ingressrouteudps
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - route.openshift.io
                      resources:
                        - routes
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - zalando.org
                      resources:
                        - routegroups
                      verbs:
                        - get
                        - watch
                        - list
                    - apiGroups:
                        - zalando.org
                      resources:
                        - routegroups/status
                      verbs:
                        - patch
                        - update
                    - apiGroups:
                        - cis.f5.com
                      resources:
                        - virtualservers
                      verbs:
                        - get
                        - watch
                        - list
        release_name: external-dns
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                runAsGroup: 568
                runAsUser: 568
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                ports:
                    main:
                        port: 7979
                        protocol: http
                        targetPort: 7979
        serviceAccount:
            main:
                enabled: true
                primary: true
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                CF_API_EMAIL: ""
                                CF_API_KEY: ""
                                CF_API_TOKEN: ""
                                DNSIMPLE_OAUTH: ""
                                DNSSIMPLE_OAUTH: ""
                                DO_TOKEN: ""
                                LINODE_TOKEN: ""
                                OVH_APPLICATION_KEY: ""
                                OVH_APPLICATION_SECRET: ""
                                OVH_CONSUMER_KEY: ""
                                SCW_ACCESS_KEY: ""
                                SCW_SECRET_KEY: ""
                            probes:
                                liveness:
                                    path: /healthz
                                readiness:
                                    path: /healthz
                                startup:
                                    path: /healthz
                replicas: 1
                type: Deployment
