metadata:
    name: clusterissuer
    namespace: clusterissuer
spec:
    interval: 15m
    chart:
        spec:
            chart: clusterissuer
            version: 8.0.12
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: clusterissuer
    values:
        clusterIssuer:
            ACME:
                - cfapikey: ""
                  cfapitoken: REPLACED
                  email: jtmusson@hey.com
                  name: cloudflare-prod
                  server: https://acme-v02.api.letsencrypt.org/directory
                  type: cloudflare
            selfSigned:
                enabled: false
                name: selfsigned
        customMetrics:
            enabled: true
        manifestManager:
            enabled: true
        operator:
            cert-manager:
                namespace: ix-cert-manager
        release_name: clusterissuer
        service:
            main:
                enabled: false
                ports:
                    main:
                        enabled: false
                        port: 9999
        workload:
            main:
                enabled: false
                podSpec:
                    containers:
                        main:
                            enabled: false
                            probes:
                                liveness:
                                    enabled: false
                                readiness:
                                    enabled: false
                                startup:
                                    enabled: false
