metadata:
    name: traefik
    namespace: traefik
spec:
    interval: 15m
    chart:
        spec:
            chart: traefik
            version: 27.0.14
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: traefik
    values:
        TZ: Europe/London
        additionalArguments:
            - --serverstransport.insecureskipverify=true
            - --providers.kubernetesingress.allowexternalnameservices=true
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        configmap:
            dashboard:
                data:
                    traefik.json: '{{ .Files.Get "dashboard.json" | indent 8 }}'
                enabled: true
                labels:
                    grafana_dashboard: "1"
        defaultCertificate: ""
        expertIngressClass: false
        globalArguments:
            - --global.checknewversion
        ingress:
            main:
                enabled: false
        ingressClass:
            enabled: false
            fallbackApiVersion: ""
            isDefaultClass: false
        ingressRoute:
            dashboard:
                enabled: true
        logs:
            access:
                enabled: false
                fields:
                    general:
                        defaultmode: keep
                    headers:
                        defaultmode: drop
                filters:
                    minduration: 10ms
                    retryattempts: true
                    statuscodes: 200,300-302
                format: common
            general:
                format: common
                level: ERROR
        metrics:
            main:
                enabled: true
                endpoints:
                    - path: /metrics
                      port: metrics
                prometheusRule:
                    enabled: true
                targetSelector: metrics
                type: servicemonitor
        middlewares:
            ipWhite:
                allowlist-private:
                    ipStrategy:
                        depth: 0
                    name: allowlist-private
                    sourceRange:
                        - 10.0.0.0/8
                        - 172.16.0.0/12
                        - 192.168.0.0/16
        operator:
            register: true
        persistence:
            crowdsec-bouncer-tls:
                enabled: '{{ if .Values.middlewares.bouncer }}true{{ else }}false{{ end }}'
                expandObjectName: false
                mountPath: /etc/traefik/crowdsec-certs
                objectName: crowdsec-bouncer-tls
                type: secret
            plugins:
                enabled: true
                mountPath: /plugins-storage
                type: emptyDir
        podOptions:
            automountServiceAccountToken: true
        portalhook:
            enabled: true
        providers:
            kubernetesCRD:
                enabled: true
            kubernetesIngress:
                enabled: true
                publishedService:
                    enabled: true
        rbac:
            main:
                clusterWide: true
                enabled: true
                primary: true
                rules:
                    - apiGroups:
                        - ""
                      resources:
                        - services
                        - endpoints
                        - secrets
                      verbs:
                        - get
                        - list
                        - watch
                    - apiGroups:
                        - extensions
                        - networking.k8s.io
                      resources:
                        - ingresses
                        - ingressclasses
                      verbs:
                        - get
                        - list
                        - watch
                    - apiGroups:
                        - extensions
                        - networking.k8s.io
                      resources:
                        - ingresses/status
                      verbs:
                        - update
                    - apiGroups:
                        - traefik.containo.us
                        - traefik.io
                      resources:
                        - middlewares
                        - middlewaretcps
                        - ingressroutes
                        - traefikservices
                        - ingressroutetcps
                        - ingressrouteudps
                        - tlsoptions
                        - tlsstores
                        - serverstransports
                      verbs:
                        - get
                        - list
                        - watch
        release_name: traefik
        resources:
            limits:
                cpu: 8000m
                memory: 10Gi
        securityContext:
            container:
                UMASK: "0022"
                runAsGroup: 568
                runAsUser: 568
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                loadBalancerIP: ""
                ports:
                    main:
                        forwardedHeaders:
                            enabled: false
                        port: 9000
                        protocol: http
                        proxyProtocol:
                            enabled: false
                        targetPort: 9000
                type: LoadBalancer
            metrics:
                enabled: true
                ports:
                    metrics:
                        enabled: true
                        forwardedHeaders:
                            enabled: false
                        port: 9180
                        protocol: http
                        proxyProtocol:
                            enabled: false
                        targetPort: 9180
                type: ClusterIP
            tcp:
                enabled: true
                externalTrafficPolicy: Cluster
                loadBalancerIP: ""
                ports:
                    web:
                        enabled: true
                        forwardedHeaders:
                            enabled: false
                            insecureMode: false
                        port: 80
                        protocol: http
                        proxyProtocol:
                            enabled: false
                            insecureMode: false
                        redirectTo: websecure
                    websecure:
                        enabled: true
                        forwardedHeaders:
                            enabled: false
                            insecureMode: false
                        port: 443
                        protocol: https
                        proxyProtocol:
                            enabled: false
                            insecureMode: false
                        tls:
                            enabled: true
                type: LoadBalancer
        serviceAccount:
            main:
                enabled: true
                primary: true
        tlsOptions:
            default:
                cipherSuites:
                    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
                    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
                    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
                    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
                    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
                    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
                    - TLS_AES_128_GCM_SHA256
                    - TLS_AES_256_GCM_SHA384
                    - TLS_CHACHA20_POLY1305_SHA256
                curvePreferences:
                    - CurveP521
                    - CurveP384
                    - X25519
                minVersion: VersionTLS12
                sniStrict: false
        warning:
            warningconfim: true
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            probes:
                                liveness:
                                    type: tcp
                                readiness:
                                    type: tcp
                                startup:
                                    type: tcp
                replicas: 2
                strategy: RollingUpdate
                type: Deployment
