metadata:
    name: ntfy
    namespace: ntfy
spec:
    interval: 15m
    chart:
        spec:
            chart: ntfy
            version: 10.1.4
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: ntfy
    values:
        TZ: Europe/London
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        configmap:
            ntfy:
                data:
                    NTFY_ATTACHMENT_CACHE_DIR: '{{ ternary "/var/cache/ntfy/attachments" "" .Values.workload.main.podSpec.containers.main.env.ENABLE_ATTACHMENT_CACHE_DIR }}'
                    NTFY_AUTH_FILE: '{{ ternary "/etc/ntfy/user.db" "" .Values.workload.main.podSpec.containers.main.env.ENABLE_AUTH_FILE }}'
                    NTFY_CACHE_FILE: '{{ ternary "/var/cache/ntfy/cache.db" "" .Values.workload.main.podSpec.containers.main.env.ENABLE_CACHE_FILE }}'
                    NTFY_FIREBASE_KEY_FILE: '{{ ternary "/etc/ntfy/firebase-key.json" "" .Values.workload.main.podSpec.containers.main.env.ENABLE_FIREBASE_FILE }}'
                enabled: true
        credentials:
            backblaze:
                accessKey: "${B2_ACCESSKEY}"
                bucket: "${B2_BUCKET}"
                encrKey: "${B2_ENCRKEY}"
                name: backblaze
                path: ""
                secretKey: "${B2_SECRETKEY}"
                type: s3
                url: "${B2_URL}"
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ntfy.musson-lan.uk
                      paths:
                        - path: /
                          pathType: Prefix
                ingressClassName: ""
                integrations:
                    certManager:
                        certificateIssuer: cloudflare-prod
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: allowlist-private
                              namespace: ""
        metrics:
            main:
                enabled: true
                endpoints:
                    - path: /metrics
                      port: main
                prometheusRule:
                    enabled: true
                type: servicemonitor
        persistence:
            cache:
                enabled: true
                mountPath: /var/cache/ntfy
                readOnly: false
                storageClass: ""
            config:
                enabled: true
                mountPath: /etc/ntfy
                readOnly: false
                storageClass: ""
                volsync:
                    - credentials: backblaze
                      dest:
                        enabled: false
                      name: config
                      src:
                        enabled: true
                      type: restic
        release_name: ntfy
        resources:
            limits:
                cpu: 8000m
                memory: 5Gi
        securityContext:
            container:
                UMASK: "0022"
                runAsGroup: 568
                runAsUser: 568
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                ports:
                    main:
                        port: 10222
                type: ClusterIP
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            args:
                                - serve
                            env:
                                ENABLE_ATTACHMENT_CACHE_DIR: true
                                ENABLE_AUTH_FILE: false
                                ENABLE_CACHE_FILE: true
                                ENABLE_FIREBASE_FILE: false
                                ENABLE_SMTP_SETTINGS: false
                                ENABLE_VISITOR_SETTINGS: false
                                NTFY_ATTACHMENT_EXPIRY_DURATION: 3h
                                NTFY_ATTACHMENT_FILE_SIZE_LIMIT: 15M
                                NTFY_ATTACHMENT_TOTAL_SIZE_LIMIT: 5G
                                NTFY_BASE_URL: https://ntfy.musson-lan.uk
                                NTFY_BEHIND_PROXY: true
                                NTFY_CACHE_DURATION: 12h
                                NTFY_ENABLE_METRICS: '{{ .Values.metrics.main.enabled }}'
                                NTFY_GLOBAL_TOPIC_LIMIT: 15000
                                NTFY_KEEPALIVE_INTERVAL: 45s
                                NTFY_LISTEN_HTTP: :{{ .Values.service.main.ports.main.port }}
                                NTFY_MANAGER_INTERVAL: 1m
                                NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
                            envFrom:
                                - configMapRef:
                                    name: ntfy
                            probes:
                                liveness:
                                    type: tcp
                                readiness:
                                    type: tcp
                                startup:
                                    type: tcp
                replicas: 1
                type: Deployment
