---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
spec:
  interval: 15m
  chart:
    spec:
      chart: speedtest-tracker
      version: 5.6.7
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 30m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      backblaze:
        accessKey: "${B2_ACCESSKEY}"
        bucket: "${B2_BUCKET}"
        encrKey: "${B2_ENCRKEY}"
        name: backblaze
        secretKey: "${B2_SECRETKEY}"
        type: s3
        url: "${B2_URL}"
    cnpg:
      main:
        mode: recovery
        backups:
          credentials: backblaze
          revision: "1"
        recovery:
          method: object_store
          revision: 
          credentials: backblaze
        database: "speedtest-tracker"
        password: "PLACEHOLDERPASSWORD"
        pgVersion: 16
        user: "speedtest-tracker"
    ingress:
      main:
        enabled: true
        hosts:
          - host: speed.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: "cloudflare-prod"
            enabled: true
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: "allowlist-private"
                namespace: "traefik"
          homepage:
            enabled: true
            group: "Network - Performance"
            widget:
              type: "speedtest"
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
    securityContext:
      container:
        PUID: 568
        UMASK: "0022"
        runAsUser: 0
        runAsGroup: 0
        allowPrivilegeEscalation: true
        privileged: true
      pod:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
## TODO #107 - speedtest-tracker: remove service if set in tc/values.yaml
    service:
      main:
        type: ClusterIP
        ports:
          main:
            port: 80
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                APP_NAME: "71YC"
                PUBLIC_DASHBOARD: "false"
                SPEEDTEST_SCHEDULE: "27 */2 * * *"
                PRUNE_RESULTS_OLDER_THAN: "14"
                DISPLAY_TIMEZONE: "Europe/London"
                DATETIME_FORMAT: "Y-m-d H:i"