---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
spec:
  interval: 15m
  chart:
    spec:
      chart: speedtest-tracker
      version: 2.1.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    cnpg:
      main:
        mode: recovery
        backups:
          credentials: backblaze
          revision: "1"
          enabled: true
        recovery:
          method: object_store
          credentials: backblaze
    credentials:
      backblaze:
        accessKey: "${B2_ACCESSKEY}"
        bucket: "${B2_BUCKET}"
        encrKey: "${B2_ENCRKEY}"
        name: backblaze
        path: ""
        secretKey: "${B2_SECRETKEY}"
        type: s3
        url: "${B2_URL}"
# TODO - Enable ingress
#    ingress:
#     main:
#        enabled: true
#          hosts:
#                   - host: speed.musson-lan.uk
#                      paths:
#                        - path: /
#                          pathType: Prefix
#                ingressClassName: ""
#                integrations:
#                    certManager:
#                        certificateIssuer: cloudflare-prod
#                        enabled: true
#                    traefik:
#                        allowCors: false
#                        enabled: true
#                        entrypoints:
#                            - websecure
#                        middlewares:
#                            - name: allowlist-private
#                              namespace: ""
    homepage:
      description: ""
      enabled: true
      group: Network - Performance
      icon: ""
      name: ""
      widget:
        custom:
          key: ""
        enabled: true
        type: speedtest
    persistence:
      config:
        enabled: true
        mountPath: /config
        readOnly: false
        volsync:
          - name: config
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
    service:
      main:
        enabled: true
        ports:
          main:
            port: 9004
            targetPort: 80
        type: ClusterIP