apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins-gpu
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/core/intel-device-plugins-gpu/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

