metadata:
    name: ext-kestra
    namespace: ext-kestra
spec:
    interval: 15m
    chart:
        spec:
            chart: external-service
            version: 14.1.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: ext-kestra
    values:
        ingress:
            main:
                annotations:
                    traefik.frontend.passHostHeader: "false"
                enabled: true
                hosts:
                    - host: kestra.musson-lan.uk
                      paths:
                        - path: /
                          pathType: Prefix
                ingressClassName: ""
                integrations:
                    certManager:
                        certificateIssuer: cloudflare-prod
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: allowlist-private
                              namespace: ""
        release_name: ext-kestra
        service:
            main:
                enabled: true
                externalIP: 10.242.1.222
                ports:
                    main:
                        enabled: true
                        port: 8080
                        protocol: http
                type: ExternalIP
                useSlice: false
        workload:
            main:
                enabled: false
                podSpec:
                    containers:
                        main: {}
