---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ext-kestra
  namespace: ext-kestra
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 15.2.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        type: ExternalIP
        externalIP: "${CHARON_IP}"
        ports:
          main:
            protocol: http
            port: 8080
    ingress:
      main:
        enabled: true
        hosts:
          - host: "kestra.${BASE_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
          - host: "kestra-hydra.${BASE_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        integrations:
          enabled: true
          certManager:
            certificateIssuer: "cloudflare-prod"
            enabled: true
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: "allowlist-private"
                namespace: "traefik"