---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: collabora
  namespace: collabora
spec:
  interval: 15m
  chart:
    spec:
      chart: collabora
      version: 7.2.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 30m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    collabora:
      server_name: "collabora.${BASE_DOMAIN_EXT}"
      aliasgroup1: "https://collabora.${BASE_DOMAIN_EXT}"
      password: "${COLLABORA_ADMIN_PASS}"
    ingress:
      main:
        enabled: true
        hosts:
          - host: "collabora.${BASE_DOMAIN_EXT}"
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: cloudflare-prod
            enabled: true
          homepage:
            enabled: false
          traefik:
            enabled: true
            entrypoints:
              - websecure
