apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:/0XQMbJ5Q7qTUhu6ILYvaefG2P5+rRr73MJXd/wsjT4C1ne5xueEV8Ft31tY+vkY62PxU2eLme8f4Dnz1UXjQRM=,iv:s8f48E5mtyfFcW1cVwry2gciuCGBmCq1ZEKPntJFaFU=,tag:w3fNakn+RbwQWOfP68LcCQ==,type:comment]
    #ENC[AES256_GCM,data:tzKoVXaENOY9NVVf8/Co61bWahfenqdYRSUEKkWp8EBH/2I0eWrpUjHpTUE=,iv:lPEerqZeoZMfp5tEiMtHlaWSajW2QvB6dKtQHG1zpMc=,tag:JqJo9tIMqQxMmJ7yRyOcIw==,type:comment]
    VIP: ENC[AES256_GCM,data:kF7FwPFXG85uFq4=,iv:ZBopMrIW8UZF1oSiglyA4XPjctm6jXJdLeZLKtP9Iqc=,tag:yH2vMbxg03sSvHPaqpAK0A==,type:str]
    #ENC[AES256_GCM,data:lh8HzI5pWxQVzFGnuRyDyZV+hDJKXfJUD3Q=,iv:v02ztj4pOMWJRA44mQGM7konRJiBq5+M+Zw2JIgxJps=,tag:J2rcuAYNg0Br8umOQIdaAw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:BOFtRiP8UrRV0Xg=,iv:Uphl+0mCZU8s/P3/HNCVo1finOLDO3AQzbVmCDGqS2Q=,tag:cUumq9wc4uYe0sbIWC4NNQ==,type:str]
    #ENC[AES256_GCM,data:O8rRCa1hpkiGHmYz/OQa0BJuZHTxvAP7Rzf/RabA6RtJDw==,iv:SiO9phPZkJbp9mwMVI30rV7v0xFapQhS3Ip3zJDuY54=,tag:c9L1Y8toPbG2649qHH8O1Q==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:Dr1Ix/sm3FMc9w==,iv:elPscWVJPYW01AAsL8gwn1zUxY/9gGWAJAx01S+PR2s=,tag:ZPGNNglWl0ndrWDEJJ5dsg==,type:str]
    #ENC[AES256_GCM,data:N7XNl1bsIp4VIAJvYLS0YeE4iyxbnoBx+pKGgdzQSGSXc6565K8OrqqBUWfKwRo=,iv:emDAcJFaH7+db8+5oyVYKcbM3CaepCVRpoz4rUjmkNQ=,tag:evlmz3PaSOhUZVShdCPJiw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:XAY5iqu1rB/wonrDDVnPC4LTPRQ6+lM=,iv:faJ5UewL/BzgUrz9PZHZge6HWCMrfqX8dMKmJ0bw4Bk=,tag:aOgzHh6x+pcmINpP0L0Wkg==,type:str]
    #ENC[AES256_GCM,data:P/2BnCoDH0B/95jSrO/XETPtKv7uRYki5pXDODjXTfImpyCVC3dNWwj7wm4dZ9WE4X3xBaa77QAf4XXklVEw8N5tAQItJjKq9+DMgexDAhw=,iv:FZYxrmPKfWH3RxXzxAKmy6Lu9YYlPQ/YAiTYLDohw8w=,tag:oZzhq+qHkmV9acD0I0KE5A==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:XXbtSymb1h/A4nM=,iv:Q3GQWq1ob2VMqJOMwLTLz7zDfuX8WJfdr7Xf1M8ChUA=,tag:epwPlQLlnhCAJDEWLgjMIw==,type:str]
    #ENC[AES256_GCM,data:nhPWZRULNeWfcPOCZbQ7bwB4Fdb+w6nes2MJgnPysL116plv0hrbZlZNyg5XhzMy9Kr3TCFXGs0=,iv:mj2a10EqKoL4wRSdO1uXmGC2lLsopm/OQ1W5ypbOSb0=,tag:1uSya/5p7IHfQT/UUEfa9w==,type:comment]
    #ENC[AES256_GCM,data:7Q/vNRJr5M1tE4W1d8H/5vk3GV/uizqWbQ==,iv:C346ZPNMrH+J0jJj9cYd5D5CtqdzW485wGy1mSEUmvc=,tag:gzQ3dDlPQmVzDlQhWK4OWQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:wRyIdTVSdoCqpMEKMqQmaFa6ZAwCzsf3LfJf9jWyTl1pJ/V0S6Y5x5d7S0Ke8io=,iv:f4qDEsMmyJdGjtz3ZmfegRnGTK18fEmCMI7X/y79gIg=,tag:+aIiO3cvSeLKANaibBjcQQ==,type:str]
    #ENC[AES256_GCM,data:7qFTYRqp9EfzdSf19g==,iv:pG/QFFknvqEJucqS7vnlK1TP2DhONRTQwEg6ppHXps0=,tag:pC7REq+cuwnwRxT1HK7a2g==,type:comment]
    PODNET: ENC[AES256_GCM,data:AFbm0JLSUuPFMMnqyA==,iv:0H1YIrZXzN4VWzMoYqUNjqYvo4jQGx2vk9zKhrrKe3A=,tag:bUu7fyzjOTZDCYXy047LxA==,type:str]
    SVCNET: ENC[AES256_GCM,data:Y0aTcqEIw1knI6mimQ==,iv:bNrZBGq8+zBMzuxW7IUrqHtL3BhZ6TY3JR5N/nMN8Dg=,tag:4lCOTwllssYsSkt6bw1+rA==,type:str]
    #ENC[AES256_GCM,data:BqzoOw==,iv:slv6z66jcL7sanIBvNy+i0o1mEUlp2GZT/lKQBRGJFY=,tag:X0OwWNi1HztGPtfW60XVrA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:Nrw3wUnPzCbz+j8=,iv:L3h8ddSfrkUbdt5sfa0mjtMrGfZifyVwITF7/6+DQUc=,tag:3rnnmWvD/rpzzTsyhUnOQA==,type:str]
    DNS_IP: ENC[AES256_GCM,data:VNqYPTKKSmDCLU8=,iv:wgYXsMJsd7HDC9XM9AaFhBdQWWamNN93gQVmghmoLXA=,tag:F0I7DOvcPYRUaXp5lBKfXw==,type:str]
    CHARON_IP: ENC[AES256_GCM,data:igcyYq9TomgYuekq,iv:N5awK1SolsutK+qs5I0GVQsiQZW+0cPNxsvrpZNzX/A=,tag:Sfv+jZefCFKm4zVoVAwOkQ==,type:str]
    PLUTO_IP: ENC[AES256_GCM,data:0Du1H0bNUrchtnUc,iv:B+YPLeA0gdMuDMlbRmPzICCmG5onJRACA+HZUITy/zw=,tag:BMYTY4xlGBbN+/LZ/0CaUw==,type:str]
    #ENC[AES256_GCM,data:oemQHBqb4oTWr/nOP7lGEA==,iv:y/WZWTECBoGZQyKoRzzuQY1Tz4/CYPhOVBW2en4yx4I=,tag:TR81OM8qbCE0i+D5XSFt+g==,type:comment]
    EMAIL1: ENC[AES256_GCM,data:eSB0mZFFOiRa8kqDR8C9Rw==,iv:zl/R9Z0YC/+6KPjbMvu/0pWU0RuiLbQ8WDu9qGtl23M=,tag:vuujqVoFqvtRfrjmuVAarQ==,type:str]
    PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:8WqA6j4v1pTTzcaUIFdJPif/xmQcwko=,iv:ETKkJbX9Yrpu9gyKk6zBQTwDulQ4ue8SO8ImksnCyTk=,tag:OnWWvEwv7LBl9TWoSG2ICw==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:W9QyQvhSU9NJ+PuNsg==,iv:fPjgO7wl2m0dG6r4zx/bunkvOBexGHW2Iup2LraGQPI=,tag:ytBbxyqGM3qkahEiwK00aw==,type:str]
    BASE_DOMAIN_EXT: ENC[AES256_GCM,data:NssOynaPP/QKaHpYH8w=,iv:cORUIO/ndrQ1W/BgMgwuzf1CTDo5KZzr5+eAZx1LLA4=,tag:zD4S8Dcqbr/iPmH6uFhh9A==,type:str]
    #ENC[AES256_GCM,data:kO9Jxko=,iv:CVMV4rO2b/lpP93/Ovc+zAkRKassqF94FFyCKXx3uGI=,tag:k4nVRhECg0joa/ulv/Ga+w==,type:comment]
    B2_BUCKET: ENC[AES256_GCM,data:qeWVbV/Bt6Al,iv:Xp4E7DxgO/IhDRA+u/cfp/RBDWEnW36pJALG3Bi6OrM=,tag:b5DJANVTwLJFeCpuhf75KA==,type:str]
    B2_ACCESSKEY: ENC[AES256_GCM,data:Qxwa8xa0we+FxfcWlN3hnFbTiEEefWIJFg==,iv:R2Qx7mZEDmJLsD9xhlyBkbtimVV07nc6y7uKZZqzqdI=,tag:hJOjEAbUrVyk1hlmaNKTDg==,type:str]
    B2_ENCRKEY: ENC[AES256_GCM,data:AKPbhz1Grt8UgJ4EEg7EAenBf0rpstRp59iOzyVcwUs=,iv:ufkGtWwFhKaJ0HAxK0MckppZfnoWAIzbN6xrziDRLIM=,tag:17hZXf2vCGt/rz67CsouWw==,type:str]
    B2_SECRETKEY: ENC[AES256_GCM,data:YeivOUaQ6MmyIiVG8HU1XQuAGE+WzDjmxfBGBuHTiA==,iv:p2J5ceN//w90SblfCA4RzFK0l2SGO2QBrQldB8BM9oI=,tag:7rx1ccF4K7dXMo+S7btEag==,type:str]
    B2_URL: ENC[AES256_GCM,data:+I23i8ooimFH2roAiyenVdbRietc9tODOcQI/1JBQzB7YYWpA8k=,iv:gpq3mqFowMfDim46LS+LHw6HnvzUYRvCrIn3NGxLrIg=,tag:OmWyobI4wrrofpmumk2D+A==,type:str]
    COLLABORA_ADMIN_PASS: ENC[AES256_GCM,data:zmleAhXH/BLH/fTz,iv:Ffi+GeMZKTTR8eRC2nWrwu4b5seToEug6+qAnbF+rYo=,tag:D8r4FPW4DevfSTv+TIH+rA==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:s1H1GgL4y3c9z/1Ef6MLa6KVluONHJmKooLhMV6AhCNc7kZ93aKMaQ==,iv:HkhdX2NWohe2I5UBjfI+kTU2uJegYAWHaSZBxi7n4pw=,tag:5iA35b9KZoWYqk4qXEULlQ==,type:str]
    PIHOLE_PASSWORD: ENC[AES256_GCM,data:HNxMOFHuuQuBXv/kv5xQDzPeCoU6dEdcZT27L2diA/g=,iv:OCpOD3yuKLDpXbFuAzImlRRhHNaDIqpPV1SG7ENkyz4=,tag:t/UPEMafFxQUuI9rsrlxog==,type:str]
    PIHOLE_SERVER: ENC[AES256_GCM,data:nSVk+ZgQ0FdIyyJUTRK12kEu41heZHIlmw1Jn0eR,iv:rZbQ4JPNs5HmkieeilWMZcC16x76XLZAn2ZU0+ofXcI=,tag:ChUzqnCdZPOonmbTdDu87w==,type:str]
    AUDIOBOOKSHELF_API_KEY: ENC[AES256_GCM,data:mBmWYVxDGQWdWvNyMaPr1AkpIegml7BCyDe7Gc8v8Aa/oVbWRxhMemdp+pvwPqm73z3pFT3muPkUhE0U8F823dWMNZuWDnqxXFOSLfgBGoa8+LLmJm8jIFTpenjBRz09NKPTq6afLPio5IGC2FDbjMhP7T8KRd5X+YOxqnLWxAVSZ/c7CC4RhVT42gYSXQICZpYfVnWpFl8WifB1O+x8Wdm448oP48c7vUZOclFeM+uc9Nc9VHvBqoL+k5+/Uihi/diYavk59A==,iv:SemwGC122SgKFW+gGsDuuCwNFurI5c5vEpd6sgD8/UY=,tag:hMOOx0kWxUlgHg2KC1mQVg==,type:str]
    PAPERLESS_API_KEY: ENC[AES256_GCM,data:GaBr71s0MQyyNt11qOCLg2yjI3Dvhi7JuYEjyd2oPUIiuqybwv/fzQ==,iv:NEl9QIvfDSWUcHM5ixiDgcByRWPq2yyOcp2qlxM7OQs=,tag:hzxK4JvwfMT7wh11SLZzDA==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:Jem7zX2iElOxkyUBuwWYIa7mbFBLoQ==,iv:yXpBO+iGRiFc+vf3qc7G2agpfB4ToWjjX4LcHAlHQYg=,tag:/nASneC5Nl//Vedx7Za7YQ==,type:str]
    #ENC[AES256_GCM,data:SXoq5gUtL4ICUkJc,iv:MJgVvAAde2k5To5mySR3f7auwcPCSJTw9oIfHG30Jl8=,tag:WlAa0qnbipjvLwZeZ95Crg==,type:comment]
    NUT1_HOST: ENC[AES256_GCM,data:cDGbmtAwX1d2sQ==,iv:49Exuymi0yUlMaa0M4NjVBlkxXrMUAZwJwbXBgwloas=,tag:fHvKaPn7i0gZxXAMeO3yRg==,type:str]
    NUT1_PASSWORD: ENC[AES256_GCM,data:ke+Viv2t9g4yL4G7GCnawr6ND+U=,iv:NvoWW4zshAjt7woDQqN1vWPH3K4SF7S3gYhYSWOWT20=,tag:bRyvNNPNQiOn6H8/+mG3jw==,type:str]
    NUT2_HOST: ENC[AES256_GCM,data:/Eh3HRokPEilwhQc,iv:2HZNwr3Mai9yLvqgCunNFRvr24Byy4vt7jx9Lr7DYrU=,tag:VU4uBeXmbJJUC2ECMWgPbA==,type:str]
    NUT2_PASSWORD: ENC[AES256_GCM,data:lmuwqpFTuR/iTG88PdOTkPhSju1fuMdc5QHOl/WAtA==,iv:l9fF+MLft8V14aIgHg5+FtbzKcyvx2JV3L65T3c/a2I=,tag:95g5bhBXuI4gtAJwx60EnQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:AHMkXg==,iv:QmgyH5qyD36sDUvQ5e48OibRvAtzfeQ+ZfK6NF89BS8=,tag:ALvQ6x+jIziJhcrZ3T155w==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scrc83rw7k5a49vvmke2r87ug22a6e6vk02dqpfsxas73llz95uq8pkx4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTFRaOGpzQ1lqaTJGcGQv
            N0xRNEhLUGpoWHNCR21XNktpblljUFl3WjB3CmpWNTE4QnBWY05hY3hYbGNVV094
            U0Vqc1NXcks0NWtIUXFIaGFQKy9TUFUKLS0tIDJqQU93citIak9HeU5IRFNMWS9m
            SWxBUHJuZ2J5cnlwdFlKOVZMVENSY1kKG83kKGKWgg3TDBKJdNXCf4LpXzLQUXc5
            p1IUg/DLTJQMrhtArMMQQ5KjcH8Po9OOShm6+mfS/as3AtMitFSr5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T16:53:30Z"
    mac: ENC[AES256_GCM,data:P2k8p04V4m0PfbmiAumHkO+1m0cEMcSt0sJaq+CM6Qs+u2QePgsKR1fMtTVpzSC3AV8IZy9rVYmPcabze+EYVaKIqsFdHH16uJhYFP6aBOQzaAI+5fXVbkg5JRHBCKIxmxrKWMTFivcze9nq9u5S1UlFjhNaNdqsRr7BWpo3XIA=,iv:5cKoqo3CjcMYaIirp0BpySYSg8UOW4mgKazMv74tKwA=,tag:BKNmR+elRiGhuzbUwwQngA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
