apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:04OrIA611HEGDRNKZ2nilOhg/xWAwd82gdj3QyX4SFKvoHxNXxDkHXjK5Qg3Qu78F82sRoNjPzdD+VhYcWTTKx8=,iv:lQ0rn9TECCH/vo4+mQdLb4hIyZ+R3YNquSeZyhOSwv8=,tag:UnNybH+nkkgdNtxA2fmuUA==,type:comment]
    #ENC[AES256_GCM,data:sLGHxTuSJzTiYjmqGNgCXnQHIcRy79weMbRXlpjPNbCYleoM6o5k4ZHrMBo=,iv:BEMjEzTJUuRyvsp7c/q5gm5yjXjPf86G/tLAZe8bBoc=,tag:ubrpIQV8DubsYysetpnyjg==,type:comment]
    VIP: ENC[AES256_GCM,data:tShnXOYFfWy0NTM=,iv:PbmRFtwt3G+0Wtdb8m6aafeV/enSQ03euQaJp7cG7IA=,tag:LvJPENLR1PG4knoF416nkw==,type:str]
    #ENC[AES256_GCM,data:nwSr0wMA4f9TeWQmX81z3JFcN5h2rMBfkIQ=,iv:p8hDqQgRNrKD7rsfuTLdCtzJk5MRbBn4o9s9qSu7DjA=,tag:DMVhz8tMQkBCAw0/MKE3zQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:ymTXfw60A/wff9M=,iv:HWyxTm8wkoWlHgG4FapcM5Z0gZqS5F+AmG7szV15bT4=,tag:ebOv8uShenNjgzIEw37+jw==,type:str]
    #ENC[AES256_GCM,data:JjE+wmglVSlrb0mmowJLrR/FG1ioqhUmOgofhrgpFyE1SA==,iv:fpBEcxOiXUOftFs+eA8TZjqBRsE6LJmd5SGG3rNcaJs=,tag:EAq1bja/LF0sS8zirBd42Q==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:gxNUZwArqZqLbQ==,iv:/QpP9CKfFgYTH1QXFwK9+1UP60T1hed3h4SRc3k0tNw=,tag:Metm80rzbGeIeXOAOhusvg==,type:str]
    #ENC[AES256_GCM,data:p0T6XqLqs1ybZ7X4HLRxRDGEtvABeSDYZ1LevKrxSymyNq9V+DtMtydCXE8+kfY=,iv:cDulYLUoHkzSKUZeHTe7ki0spnwxtQr2Ngh8/t7fFsU=,tag:EKg7MAWRaapCE9R4nTXbiQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:4i0aubob9I05kG3wqFGYYR6Gvh8c5xk=,iv:4nXNc4vRw2/WuJPfYVCQJY/lopdngxgpf8oiXN5PpRk=,tag:IDqeLwYPgGJe+6oz2FZipQ==,type:str]
    #ENC[AES256_GCM,data:CxA6l3dU8P6WanIcNT/aUbkPuX+ZSGS5enrfDao9GyFJmjTMnhBb1ZXZLgbe65rdfS4m7IxBSFkMup3p1+R2Oxww21eEc0B4kE2wtEynano=,iv:sdbuho8MqROqX5z8dm78FTNDwWkaqAM7U5dSzsW0mlk=,tag:cJqsDJJ2ax3/Si72VwR6Sw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:06lS+PZu+kPe+2c=,iv:Srv7EnIqI0GHBdj2kUkDOtRiFGrHymqXimyKMNyyw3Y=,tag:FhgPzeEVSkYA5yOdkV2KQQ==,type:str]
    #ENC[AES256_GCM,data:Uux/8W7Us/TaF9dT6y4dTHBQVfJH8rPiF+9vyAcC56SW7ZH7bEg2YdKLxXmy8lcKfEur8uXiDqk=,iv:8Er0kfPz6r8VkZ3O3xF42Qinr18MNq+DDjFavaEwITc=,tag:ms/YfAnA+8prDiQfFU7yEQ==,type:comment]
    #ENC[AES256_GCM,data:OP4TAvyq99QITgk2Emwenor9CO7D/qZ6lA==,iv:ySSjaj9QId2fjXzv2DHvowgt1pGjTVjmsUXq1K2NhO0=,tag:H/60Uktx0XyaMTVZg+N9DQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:aUDyQ+sJmFZJuuKJool3YGNETUM1ajC/89xS8bfXt7LDr6++PN2S92M=,iv:XAhNrLeFQcRfhpSTAtNBXtbN0bXDN4EzvEhwXbd1yC0=,tag:uJ3a5UblOXLwCvTd3tssUg==,type:str]
    #ENC[AES256_GCM,data:Ryp0jbhlrHu+92yl1Q==,iv:nNfGlHEf6tSs/8eLZHfDf6Ejz9TdWTH+mzsXAzrwODA=,tag:n8txdLZiAtjD0WmxYK70PQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:oXriuaExMilbkrg/hw==,iv:lAtiNfL22jSkmgrTGa9IZzZLrUbFSANZUR0/8Cdf6wI=,tag:64GJVp81msoHJ6+ucwvZbw==,type:str]
    SVCNET: ENC[AES256_GCM,data:Zz96mAeYmPvH81I9FA==,iv:bsEdhIAbMio14udtSn8pri0E/+TuEbKvVmpOtmebaKM=,tag:AZ8+pTuCGD20ol8qjntL5g==,type:str]
    #ENC[AES256_GCM,data:Zrel5A==,iv:336gF2U76zp3zvmqtVPmwiliL9DAvX+dxgIwYMvvOvI=,tag:Cn3t9zntx5ENzq/XbFiRzg==,type:comment]
    SPEEDTEST_IP: ENC[AES256_GCM,data:v9v1FKtmeZfhezQ=,iv:0cVrJx7AGwMHJ3Oo6CrMPeHQxq8MAHsx81b+RZyqENI=,tag:wlzH7L4CzyaiqZq/To9pnw==,type:str]
    HOMEPAGE_IP: ENC[AES256_GCM,data:/T+0v4hB0VFAmlU=,iv:IgHrLmM4WtHxLxujxY1jAZfgv1BA+vEbbe98c2+cA04=,tag:2wrw/sNxm+AkH7VijqNwZg==,type:str]
    HASS_IP: ENC[AES256_GCM,data:nuG2FGfgHUTH9mw=,iv:rxdo8QJ/o0I/OM7L9dM6QNAVJ2cus2I4ImsuXSAbjV8=,tag:ZWje4R63iWQKVbkCgcZFgw==,type:str]
    JELLYFIN_IP: ENC[AES256_GCM,data:axOQZp8Gu1t6gTE=,iv:7RCrRxTmjMhd9cUFFAnKyA1gMwQErvX+X5CoX1kn5fA=,tag:fb0h83m/QFgxkQI4oy6mtw==,type:str]
    NEXTCLOUD_IP: ENC[AES256_GCM,data:AZ2MLqU99/VVpN0=,iv:AtFmWU0KsmgbgJL/8y6Z/uTroh7HlLs7XZoJDGHYU5o=,tag:VNfqW7vd960AMVgfuGYRPg==,type:str]
    MINECRAFT_IP: ENC[AES256_GCM,data:RR3h1bDznftTrlk=,iv:Ym/oytBIzs54nEObnkJVa6zfeLiW2cqY2AOtXofP6QM=,tag:FgfAipm1YHHrklprHk4DZQ==,type:str]
    HANDBRAKE_IP: ENC[AES256_GCM,data:MbTtgCxIs5jJ5aI=,iv:eeyJU9RJxfpYmBpS9iMBSvz4hTZFOCvdtSUU4WCAlyk=,tag:7JIyl50E+q5IgoujTlJQeg==,type:str]
    DNS_IP: ENC[AES256_GCM,data:/HivLRrnOyy5w6w=,iv:eGA2fqEkBz8mozOCkvq69VTec7GtYb9TXdn9tF8oOJc=,tag:30gQ9pyNR+VY3M5ClEu79Q==,type:str]
    MAKEMKV_IP: ENC[AES256_GCM,data:GUFJPEdGQDTYTQc=,iv:NBHbkbMRyBWF8YngebBI/i1p9zEQnzpZuhm071qiEe8=,tag:elAnpSLC1YM9mLTUXr8dSw==,type:str]
    PAPERLESS_IP: ENC[AES256_GCM,data:3uCw7rLuzU08BbU=,iv:OujjTgq3n5gC9rZR+KSFFFT3PysHKr+1JwUzoOj1RPE=,tag:pdlJgZK28o6e2j1UkN3VoA==,type:str]
    COLLABORA_IP: ENC[AES256_GCM,data:cksuqyK3UjHrM0c=,iv:+5kaW/ZPfLd59kf8jpoTBJpOM8ojrLAdmRPXoPi8d5o=,tag:TQhMUS2+sLwQVDftoTKA/g==,type:str]
    AUDIOBOOKSHELF_IP: ENC[AES256_GCM,data:2/FGU5fe58IY1oc=,iv:aCAmtfRs9q2cY1+YRj5JcV7i77ecjm5CYxhBh9URGB4=,tag:LNcGyCXAZBser8CVcHvvXA==,type:str]
    UPTIMEKUMA_IP: ENC[AES256_GCM,data:06ekrKmf4exynlg=,iv:QB5LsnoyksASzB+1jyxPb3OUWmefVqumHwTB+8kbAAI=,tag:4F3LCwcNOOeaD0SbsiNeOA==,type:str]
    PEANUTUPSTAIRS_IP: ENC[AES256_GCM,data:vQGJiTDnSRFKRGw=,iv:0Ri9qBtYgVcXLceIilCf1HmZG62d7bba6eXPQuikamw=,tag:BFgS5YG4mlIC3XVNYS5wag==,type:str]
    PEANUTDOWNSTAIRS_IP: ENC[AES256_GCM,data:4MzK3wpfKGd2eak=,iv:5KvY0Jm4/oJKYKyP5SqA4Y3h6Hv9orgjT/41SoNu2zo=,tag:HBzYA3jMj1LKtUJ50bRpsA==,type:str]
    #ENC[AES256_GCM,data:7KOZxB7vvQ==,iv:zLlk0V8cDd9IHdeZh2LWJCg6DqoPN5se9c+VclLvuqs=,tag:EsYgmC1HAHp9NeiPaBIPgw==,type:comment]
    EMAIL1: ENC[AES256_GCM,data:HLrpFwvryq3Fbh5gDMoyMA==,iv:SZxk2tb+meFSRYPJB2OtyOPnzVjRW/JWOzEwTBZv5gs=,tag:ePA4gXueHpYkj4rjjmybXw==,type:str]
    #ENC[AES256_GCM,data:3MyLhts=,iv:Kb3+MYD+yCec6+gghJd7XBuuOn5oK5vVFBC8HBhzSO8=,tag:1QGuEc2zmOH7PEtj4XOOoA==,type:comment]
    B2_BUCKET: ENC[AES256_GCM,data:0RFvUyEcIUjj,iv:pZ0tEZCKBBm0EphaUyM54clZYTHRUksCQtFdceRI1nU=,tag:yGoRUI2UOo1D7paUDGGZkw==,type:str]
    B2_ACCESSKEY: ENC[AES256_GCM,data:evbv4wi9yCQU1w6LmQQTq/1PBK3hIEeWyw==,iv:oGoIOA6e5RpUJ8CR2WMylO21XvZ+iMi83wEwA0vZmRg=,tag:QLd2PA6uni5doelJ8+oEeA==,type:str]
    B2_ENCRKEY: ENC[AES256_GCM,data:uMZMlrVjUJv15hHFoG+SzcszqH1zE1G0nER+ErXeJvs=,iv:uwfpEyOwvqUW+JalPWPUu0dFPN5mrbPE3IuD299lIUQ=,tag:aqkhVKVGzVn11E4piK8NNw==,type:str]
    B2_SECRETKEY: ENC[AES256_GCM,data:nnYthYz7SbMt7aEUQiafXaFMjnZnhyQ84ttyJARVXg==,iv:Nz/9BiqNw2yRnwIP9ln6l+3rUGzEYlm5RZ/powCZN6Q=,tag:UmeWY/VnJwOCH2Vn3A6egg==,type:str]
    B2_URL: ENC[AES256_GCM,data:a5Ye7ApxCUjJ39WNkEuF6RvAeFh7U7r/yr9wEUjxzD+WofFcqHs=,iv:e0B0Dcoey5ccQ2ThIUKd7lF4mHooMh8N3OpqWV1p49c=,tag:08b4nDzpI0l+qPyTNV7BXg==,type:str]
    COLLABORA_ADMIN_PASS: ENC[AES256_GCM,data:xjo9Le3B1yoYO4nU,iv:0QDOtKboyD6bfwy60WihsZTinWFk+FN2i0v16+joD3k=,tag:Kf5ZXowlseGk5QDK3ksDBQ==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:zkBobw+l7Sx0ok+idVIaHJ9tmI1YIrEEafekWN+4CBxEqFDbzyLTXA==,iv:UrhVie7DJeMREwF1U5XMLHwWjuWLrpqACEsFb23M/F0=,tag:Mstd+FaZ4fgmt4kJHBgnkg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:QWgqug==,iv:qTuOELsgH6mZkl5PMCqnCJ0+gpM6DoDv4HK7/foFCBY=,tag:/KiGRHhJ5u8+5EcqNBvDCQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKR2NjUFVUZ2xGOFBsOW5a
            OGMzNGFPS0Q2Lzg3QVFTWmFRaVZZUDRjVDE4CjdVZWd5TmxpYTI3S1NYWlVVaHZZ
            SThzUkM2cFpuVWYweFdaTzAxcjQ2OHMKLS0tIGdmZlVCUnU5WkEwTzJQaTV1K2hN
            aDFkM0tsc3F1eUUya3dVU0JxSzlQcWsKLQIZCqzGvtGf/iavCca0Hl1c0fo054lP
            rESfdgUBYfzTG0mLdh+xG6v+tgiy6shodcMoaQiWYApZIZhcJg+m+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T12:14:56Z"
    mac: ENC[AES256_GCM,data:LYk4dkFMrZMb5DjNuGIle+xmr8ALnoTJVWJrkhBqNGhmzs4CA5nnLB+qV1pbWYS74qpnp2etu/GEOHDnySZZxCDqSOeMUUCozuZjSdgnuisCb9yI2tk6DFsn5JUSLKKrahATWgcjrdWZrkQlbPq30kWldAcRgWZ3rPXCpD74ehg=,iv:YPnt2bDkiH0qUYhEuXdypGSG2yLA0DrjfKB8g028bfk=,tag:XEV22okFgpZBg5rEEWj1fA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
