apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:zmNYZHQiGimrKH0hh+2Kk2b24S+j+9VaXeInkWsk6tD2dJtWs6d2Z41sS7DEyLYdH6iRVCQoHabXzBp1izDKzl0=,iv:AtV0ecQnESl4xoV7zLqD+5ABg37owEOT+MEJyf9csdE=,tag:hmBRqwTw+3cYcTJ+LDHnng==,type:comment]
    #ENC[AES256_GCM,data:B/HUGPyculWxwYlkwQlcUvgqnphoD0gLf1Qw3AYAZINnqbCOErg7lmbGmnA=,iv:X1V9DUCWL4m+y8lM0/lPGSML0frf6qOFhdoUk+ImE7Q=,tag:r6/pdg/OBwKhYNJKxisrDA==,type:comment]
    VIP: ENC[AES256_GCM,data:99GpO1GzVWicnAo=,iv:jPcgffXaIPn1aPNPHMNT7w0SwSlmh8tzK2b9Gj4idg0=,tag:u4vBl6pngIVgetnOQG2Q1w==,type:str]
    #ENC[AES256_GCM,data:qQa24rRr/DYjuBZCyxcrlNte5mJUu0+msPQ=,iv:ssGlt8oyXp9WatYz+n5ogVmFetvzG1snNk4I14NzFQ8=,tag:J9qCJsNxKI8gXyRinZjBdg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:QG9BQOIPhUvThXs=,iv:zBO2FjQgJ4Bx5ep/OQJoxEdPTgBmJ4E8AKmiM6p7Yx0=,tag:q/hzI8HPUFJoNf/Ig32sCA==,type:str]
    #ENC[AES256_GCM,data:UW7B22vrwEtq6Rc/KbZVV6XwummMdyzDXNMfG9mg4xzCmg==,iv:fRL4biWRKxwcVvLsKBPkq7UrB6tWABC03GA88mxoxGQ=,tag:ped9LT8A1VpizvBCtiUv0g==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:H/OPzjGce9hKjw==,iv:LMR5D8uDgzzAxSYYdBOZNQQBI6QkGOZZu2PNkmhVt0Y=,tag:b4nActc2Hz+Kn5GkedbpKw==,type:str]
    #ENC[AES256_GCM,data:HjbzcBRQGTZOSusrYjcuprj82SmW9n0qP8MOm5V8zFqCzrcgJQTOb9PW2gtoP0Y=,iv:pxipWaqVSAlYRHt0nH5ryeQhisV4lIHxa65eRkev6ps=,tag:ha4WthDeRfsZ04kQAc6+Nw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:PdCpCiQhwOusq8qnPI9AgzS0aRiDKEE=,iv:tArkrXghu5Emahnw97OV9j/N4zCYubOk7uXxDifMCiA=,tag:5nsBEmAJoDrdIKiwcEx/iw==,type:str]
    #ENC[AES256_GCM,data:yJXebVeIkP9pW2pNUYmMjHsn8a7fZIJSErzbDqNMzpIj5wOKyfMsxtgec655pm+Tm26y9LKLgpKuXqr96271zYMRKuc3B774vE6XsY0gi+E=,iv:+9H8olR0ew4o9hnbGMkQPMJ4MFtVM7Mqy9RY1hO+FZs=,tag:1GhJaw99wW0Gsp8A6bY3xw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:UP9mjqUcSz6rdg0=,iv:kB3Bf1dNIAQe8s9fsK+fyEadzJlBUUVosLATiuHg9PE=,tag:zfZGEEFUey53Jbf/lb/wgQ==,type:str]
    #ENC[AES256_GCM,data:JVnqfH2p05xeW3taSuoYPigmbFLd+WeTz+qI4pC5gbDAICIm3enNH3XAm69Bf2+dnyyQxou/MOw=,iv:7IFV4XubsfdHddaUrCkBOhCYXj4QeiKEgp/eavsQ0yI=,tag:9Dn27ROS0tXeMrZsga7tuA==,type:comment]
    #ENC[AES256_GCM,data:nEeYnMUUWs28dl/p46c7Mf9MrKNWxHSzXQ==,iv:BaikOqf+9gWho5T8uQiktXuNrfpO3TJBsoG/1SjuoUA=,tag:wOlIpVZXmnwaSqLLK/1HmQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:XKpsPQuWbLRX1gk/YIf1ts1dkIeHqqQ1s+DpK46neHl1k/2uY5RCyOwtfdd7A3U=,iv:oBJVfWuNxSd6CbQ8hJOY84VxIXoN4bthFzkgVUPDUiQ=,tag:1OCNAj7qbxaIMN3H2aqnSw==,type:str]
    #ENC[AES256_GCM,data:kkRfgDZurH0Iz7L8dQ==,iv:AO5nUsKYq+uxWNNals0GNolzCqjWC7l3rUPO+o96L5k=,tag:ILsEIUtPAfOwoUOlZTZIrA==,type:comment]
    PODNET: ENC[AES256_GCM,data:7cn1KqP7OOFO7aknjw==,iv:D9lx0pGYWRr8Ezo5SglU1ens/lxTgVqJ6fdVs6QI5Kw=,tag:QXvIY3sTn/ZIwdbizWeFtQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:28zB+e39KR0gvFz6Xw==,iv:/Ma5ftKdUEpldGXdWSv7ENjGtKD8xR8x2ghUBEDO63M=,tag:VyCb1C9ddGJliP90/RhMGA==,type:str]
    #ENC[AES256_GCM,data:mp5QWA==,iv:/oXeNrXCeodAiVCXE7L3Bsq32r8u5iPB2g0HZchgYkE=,tag:mQF6baYI5V1jjI4hWmPW7Q==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:FQHLOWFQViFmhGw=,iv:KzHpBw9TXg57NCygWOVsYw6aFxv1h58/GBHaGVCiHMY=,tag:2Jhi1N2LgHnVaXPTEryO5w==,type:str]
    HOMEPAGE_IP: ENC[AES256_GCM,data:3kOQ8YNiMRZiv+U=,iv:07vuIIOO0/u3uJf4HU5yP1KblFYDDHsZAhyKQEaQI+U=,tag:gG0YsnplafDcAAkqL4MPkw==,type:str]
    HASS_IP: ENC[AES256_GCM,data:iBXrGofqk0Y2VZo=,iv:UO7ghc/q7Edtt/rswi4O+SQcByp2hIc8pVf7Mt01hQA=,tag:NvQsO+QCnUHZHDstax1Gew==,type:str]
    JELLYFIN_IP: ENC[AES256_GCM,data:BT9uZmYFlR4rVZk=,iv:x/4J09l5OLvpym1ygzacxWrjqqzEUdmeh4CaM13OhVc=,tag:ofh6wax+WndwoXU7VcAdtg==,type:str]
    NEXTCLOUD_IP: ENC[AES256_GCM,data:jropgcAI3hZX6Yc=,iv:dS5M69dqmJ6Awk+57h39GxUoJvzqKtAAziSkvkOTJGg=,tag:bq7BjDpGKPMjBR4EUs3OCw==,type:str]
    MINECRAFT_IP: ENC[AES256_GCM,data:iU1MsB4LIjwKvPQ=,iv:RBtVIMj0FgyrHLdRq5/MLYxCPuxnJkTKEutH8uBKiig=,tag:wCYzzvky5819ueAmPuwi5w==,type:str]
    SPEEDTEST_IP: ENC[AES256_GCM,data:vhxso6fb2AIo5UQ=,iv:Vi/sfwv9ab+1O2E4r+YCY+fy+A9MLPdEG0HbP8bTd5Q=,tag:KHwfhIEibWSwj1L0GUSYxA==,type:str]
    DNS_IP: ENC[AES256_GCM,data:WxNAYPFKqGy4AEA=,iv:UxfrqG3VMr0FYa5DvgLY7VAlfk+rxlwK/GBNyl/ciXs=,tag:P5Mi2/bAJlK9zFMlHP2VtA==,type:str]
    HANDBRAKE_IP: ENC[AES256_GCM,data:YjWxeiM8iMkZjfE=,iv:5PUiyN5qCMKXQZlL908L4kc1QQiVqR0C6T58vrGxHNE=,tag:XwZcDwD+T4KZ7/Y5uX4aFQ==,type:str]
    #ENC[AES256_GCM,data:K40uB+ERdQ==,iv:ue7/thVMtocYxJ5AU+qzeHxydWyAaK8mxO4R3CD9Kdk=,tag:Ge2cTn0rzn4DQ6BhoZcS7w==,type:comment]
    EMAIL1: ENC[AES256_GCM,data:7VYDnrZQSPJGseeEypiEDg==,iv:V80LYT4ORabB17ECkDUJmhUC0EqEcpl1RpOROYnkLf8=,tag:/WAzdn+pIntTT+G0AjsPdg==,type:str]
    #ENC[AES256_GCM,data:/D2R+cA=,iv:WBwiYQForo/N4gQ01AmMxjDSnup4+p8T6aU1xVF1HNY=,tag:bVxMXtri/DpmfVE/JHhdsQ==,type:comment]
    B2_BUCKET: ENC[AES256_GCM,data:fFXjJupJeVxL,iv:bsROhM6ZK7WnxRVpKK96CELMVyXzEpxzgDS02X90W2o=,tag:z2+zT1mCCTEIKiHz8M4haA==,type:str]
    B2_ACCESSKEY: ENC[AES256_GCM,data:SfHsOsdtj13/Y/W1JJ+olHK6lzix77yPJw==,iv:/HQFGHyI76CPL0zDZtGg1OIKvshl91aW94/7/CGbHoA=,tag:UOWQhsHRrUZkD2wR0sLp1g==,type:str]
    B2_ENCRKEY: ENC[AES256_GCM,data:ukO1oDywHAHEmo2wTX9S2teVHau/+554Ws/6p0KVy7o=,iv:spvLt6FmBBaGZfWsV9CS2Wc3iAgse7Lmaoll9lyNXMI=,tag:RQGVbbl6TjvfMEJEDNXORA==,type:str]
    B2_SECRETKEY: ENC[AES256_GCM,data:fxtB94I12g/oXCk5nOs/T8PVm1q91D64uvfL4MiKBA==,iv:Vrl90LKAI7TOhFqMn/AOCMqw7AouoyfmUsTeBNPYlJw=,tag:u9q12U71GTJkwGplqfNXFw==,type:str]
    B2_URL: ENC[AES256_GCM,data:bYi7qTGVEoOJPhDGlfgjR6fIFINst7zH9TePGgqWVr9JjPHHCPY=,iv:8ZWZgyl5tu7g9Chf7prrCvcU3/DC96Ve2ux3uvWaBSw=,tag:Rle62SNwodsww87F+GwEIg==,type:str]
    COLLABORA_ADMIN_PASS: ENC[AES256_GCM,data:Q+JDpXtwD4URCh2w,iv:rNkuFaN/nZLiriT2szAWdwhZm4Pi+qxlMc+wu7nxnqo=,tag:NN69a5Zlzvv0CoBkbS/x/w==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:AFwt8aK8+8B5A5a6eSZnP0AqbjtGbZuBI978dQIpUw49ycOPmxnzNQ==,iv:s4gryrImcd9DmgIlyZzhSb51eInbwLrVVumNMN6LJHU=,tag:6TVt1XhH3KyJgf1R/C7hfg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:IQl/NQ==,iv:Lcci35kHW+8VflZhWoYDJ5lb4Mwl5zAcg0AeWOdWrKE=,tag:TLs+gQRn/VcY9pCCZu1IwA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUHRKVTd5ZEV6QVBFTlRE
            OGlKSFVMQXMvVHkwWjBOVkNCVTdsRU04QVE4CkQ1TzFMaWpVb0dySUZKSGVGM0dO
            WHFKeFAzZHJtS3c4NzJURkdFa0hDeGcKLS0tIElBeWpIOTlDZEhRZXBRT2xYQUE1
            Q0xKQnhwUXBZa1dvdWhvem9yTTRZT0UKqVwAZmqEMz+AQbl2yCefzV274Zv76Cbr
            il/55pORuwJcTYWJNIQuxObEzQXuTQFRZTjcX4f8Ufblq5KW4D9fMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T18:12:51Z"
    mac: ENC[AES256_GCM,data:V0yOIuURWYm0N2WogOt7NXSsjkV/mDJ7Wb2qNGCyC2hwTLwwgUQ2NXkBdpo5WMbaPka3EKuzideTY6kC1VFmpVc1932gsrSIAd+CjriTh/6oMlCKyu8PKeEwN48URlUEYx3odQ7QUk5rzRwqz7/5nt1+1yR9+M6UT8V1NrfkGY0=,iv:TtvOqwRbeIt6lnNvd3PR3OhrifOR9O+DvIZTkQBeF/Q=,tag:LPWdkZqnqqzMbrgEvUwQ3g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
