apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:FweMKFetANcnNywMcUX6kehUc8kPFB+onnv0USozrDJlLRkEdeAJuPjAJBJ59Cn/ecnx2hvxE3L5BzgLvUiY2ww=,iv:sl6N3VoL7fouhNbjfj1uQ/E83loQNZDDcpy0Gn05gWk=,tag:l+s39z/h5gTogfjx4Phynw==,type:comment]
    #ENC[AES256_GCM,data:6wtyW7ar7PE/L6Y3qASFrcJxncqvc7mSOq+ncUz1ux4klSWYV7vysmZg0Ys=,iv:yhggVPYjW9+0LViqVaQww41m/6XrEThgbtABdUree4c=,tag:SFv3EBuOQjEsMl+BbTpdOg==,type:comment]
    VIP: ENC[AES256_GCM,data:gYBHZ0eXcxix4/w=,iv:lqZ6UQ3fRSdb/4Mz6bxVXGWVe79+u3/Fx4T8dR7ZVCw=,tag:BIZyIJwwe2n31k9CdjEzgw==,type:str]
    #ENC[AES256_GCM,data:+B/4yR7jFUudr6e8qDGyy6i44hfa5xLMN3Q=,iv:F3MAsV6G/Gstd4VPCPGTcwyWcNtEDTtMQJ55iAO4k9w=,tag:YN4/KRv0CIbJNNn32NlTRQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:JVKOnaRjebViiRo=,iv:GnzoSeaaIcMFPeku3Eage6IDrVcMgyTjS4OTCJkCl+4=,tag:xMWtAb3kPtCHAlDxqQbCIw==,type:str]
    #ENC[AES256_GCM,data:2WXQPY6r/Jw9QUK8KfSDkz1hxHNTfv+t9vj2AzgNlRO0gA==,iv:Zgg44LuTc9iBOKkqBr/sMqr3yL8zOwkApgV64qjMsbM=,tag:6ReEKRagd0AdrykURXvRyA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:KsYwkKJfluuSgQ==,iv:hG8qHdN+ekMR4wNzqtfHwSGOj95IuQ7gG7/MLpMuxKs=,tag:NpY8msTB3ep5NhTbNzDNXw==,type:str]
    #ENC[AES256_GCM,data:KX5R+L5NPgupWYpwCEHou0M69xNcmDXfe9bd4QQ1tjg/CAVn3J11MGqB7oo0EcY=,iv:zOW05A7G/u8D1Rqin2dL2VpCHY+nRORgnec4FGBdDpI=,tag:fEiAP6DVqw1PQJyxm/EnDw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:McKTcQAZwJbHODNuhfEipaEbznDTpFI=,iv:A7vbS6WaerxKyzfji2FQWPKrznt2fyvk7RSNJsdDfwo=,tag:gsXmXjBniKM9KsmT3Koyzw==,type:str]
    #ENC[AES256_GCM,data:Qv+AZEoaQpRNl6T+ZUufQGRPSMqoDYligSazQn59cLFrLCOISn7/m2DVdJCycBY03vZld8VHZREFq3Nc0yMkvJCZYSs8i8F/6AbTWIV9Nes=,iv:lVJFpzMGW413rqrLOUtzanQHkRZFowffuDRPu9WFJbU=,tag:h7wERuwBAuT7mNmHoJMQ/w==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:JoW1kIf0y9czMqM=,iv:ybNFpBWUYotUpSQxweciqO181ccwgGsqU3R5QfokGhs=,tag:qEGCU+6NWmyZZvTJnWdyPQ==,type:str]
    #ENC[AES256_GCM,data:6euVPHOxATfYAIWZNn8lBwwsHdtTqbmRn2Q+JntInVAqXEFm67lm6yYKZxmtnypMSyy8HXkvwCA=,iv:Up+8Vk22z7kqEmSMcFENTwx4W/tVAWHGbx0wvCLW744=,tag:jt5LODqZZxQCizFE6/oWtA==,type:comment]
    #ENC[AES256_GCM,data:wE0HjQd3KCEMOdA3O/Xv2b73VuSCry6mPQ==,iv:bJ/vpMoJ3MysmGHVjaLeahGNBQykirdAQOHnPj93vtw=,tag:Q9EnflT4tTv5ZGn/mULNmg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:ysOY3+6vQ0uYmhtk8BtE/Ir8zphRshUHdBot8M8Dba6UzSxwMzEzSf9UoVmZnSg=,iv:POdIfFAFdlXkeRJTygV1zfXDvQchJeC7gVKkekYuCxE=,tag:OA+9/4cYc+abaASHOQzhhQ==,type:str]
    #ENC[AES256_GCM,data:RQoRlwTABSe1m/VVKQ==,iv:/KRvaP1QED8ICsTuSGQTOZMVX7lRAh43Zr24J1IDgKU=,tag:mf1lB3g4rF+8jsutV7IqqQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:HY1x7Pj4tuwhgumPhQ==,iv:ZVYqmmj4L7136mpidJcf8kx0sLzNAyhH0OjKPUJQElU=,tag:tp3HclN+urBo+/+Q9etkJA==,type:str]
    SVCNET: ENC[AES256_GCM,data:28WDYa7dYASDsomIFA==,iv:9NHRnP2madIEp5YRLe24tJJ4e7evlbOyE0tjjIFJZ0g=,tag:OZdJbU90IeNQQK4zrbgDLA==,type:str]
    #ENC[AES256_GCM,data:xIl1ZQ==,iv:0Xr2GGwUBCHpD7KF1/IYG2C85c0xx751M20+c/00h2k=,tag:+bRf7XjUmhu0RBnpXVa/8g==,type:comment]
    SPEEDTEST_IP: ENC[AES256_GCM,data:liwRSuhjwv71bBo=,iv:cvsAMSmwH5A7OaQ2Y+sstyLML0QIeMJOpO8zouRkcbs=,tag:HA59TLxxSIx1nog3K6JpkQ==,type:str]
    HOMEPAGE_IP: ENC[AES256_GCM,data:FuPiIqzaCG15RTA=,iv:eAaQcR/J7wK3IKyATt36CSiXCIb1oM3caWrArXS7W58=,tag:W+7KA3h+cy+VUgw29rI2GQ==,type:str]
    HASS_IP: ENC[AES256_GCM,data:wNaEEQaiwB9zU5c=,iv:6SoCXpQCioCX55INQCDwBsoQ9+Oa7/VnA+V1oocyHZ8=,tag:UJrrUVlPAwJ64/p8sEqnbg==,type:str]
    JELLYFIN_IP: ENC[AES256_GCM,data:0gLAr9d3HUAFIZc=,iv:q3TnUck7zXcEI8qj8LlxSaZvJ36lHcz+g+y0jcp2CUM=,tag:qmPKszwSVs2JjFtbVCvXrg==,type:str]
    NEXTCLOUD_IP: ENC[AES256_GCM,data:4ZBq2tk6ZRFtfY8=,iv:9pnK013j9tNeUZut/htenmc3Zg60248iLN8oTqDreRg=,tag:0CokwjlV86RggT13KMER1Q==,type:str]
    MINECRAFT_IP: ENC[AES256_GCM,data:M4gQrBVUoLjAPPw=,iv:bSm3Si/WUyEpkDUuA0f4jEhV2+/asQhXizhW6y8A55Y=,tag:xfo3OLjJJ6ounqRMqQ9RIg==,type:str]
    HANDBRAKE_IP: ENC[AES256_GCM,data:NamS+eUNnRIoo3o=,iv:WALJzX3Wm/w1qu6Ky6xIanMEPdYirQM/D+Kw3EcUI8I=,tag:lwBIG1lB6u1yZC3HQtOsUQ==,type:str]
    DNS_IP: ENC[AES256_GCM,data:j6hdu6CRZqoPVXI=,iv:d6wCIPS88wYMdGMAlniTFB7iErh8EwAZIvDbuNxmlfM=,tag:k0l+OTJWu3c1MRUEuHr0Jg==,type:str]
    MAKEMKV_IP: ENC[AES256_GCM,data:btqCA8m4yT4e0xM=,iv:/0bzspDHgJTVuYn9J688klrQ9Oj0S2gPpFIdj07NxwQ=,tag:EjN2ZkeBATkazLO1ekreBQ==,type:str]
    PAPERLESS_IP: ENC[AES256_GCM,data:K/Zzi7sFO8E2R4I=,iv:mfMIT5bu9LhWhx/fwM91Zb1yranzKZqSSTTYgGKZCHw=,tag:U408LEVncyuy8m6VQHjdag==,type:str]
    COLLABORA_IP: ENC[AES256_GCM,data:WdPSX+sK3jtmwdQ=,iv:6XWUGi7xZMMrqKB6gfu5Tg09G96Vmvm8qbJ1gce6JOQ=,tag:y/oUN83tcIR1uulKzCG60g==,type:str]
    AUDIOBOOKSHELF_IP: ENC[AES256_GCM,data:76/zKUHv7Eg1Imk=,iv:b9Y47EFL31aFK9CMONlonz2o36CGXjqfG29we4cAamc=,tag:EMbAy5Z2pHh8GHrjisbRjg==,type:str]
    UPTIMEKUMA_IP: ENC[AES256_GCM,data:8DHvPt2azUSOzfw=,iv:LXzD6gCw2tmqrSICAeWfmELA0Ra68dBfD57Lpn4QX7k=,tag:rMVSaxjZns3/m+H3nXwq2A==,type:str]
    PEANUTUPSTAIRS_IP: ENC[AES256_GCM,data:a/PX6UkQ1F7gnlY=,iv:Db71szVkO2wC5zIWt+O1DTB27t8yYmLJ+JwZVMA/qGY=,tag:XmRbF86nLFh0xlnv/AXvIg==,type:str]
    PEANUTDOWNSTAIRS_IP: ENC[AES256_GCM,data:e8CnN04ALLfKNeo=,iv:0UQ212mnU5tCS6hjY70raKjFtawAHaI/a2+QMAwdl2g=,tag:gFK9h9tvRagrFECYBQEZGg==,type:str]
    #ENC[AES256_GCM,data:hAZToHVjqw==,iv:822yP2D6DTj5iCf/SAmuzYWapjfNUbB6gjvOwkive7c=,tag:s2PHrrn5sv08NPzDXYsXkQ==,type:comment]
    EMAIL1: ENC[AES256_GCM,data:NuV8pWcGEvPDIwbWK86vsA==,iv:0zsjt6a9SYAWWqYnwKAU6nKubavheKGrvkpwmGAFCT0=,tag:T6UEjE+fTwa0zie12iLYhg==,type:str]
    #ENC[AES256_GCM,data:lgXWPb4=,iv:XiDgYp5IZFw3DDDWjGrtMZUeeFVpb6MGZ49/HiI+D5Q=,tag:1cuSS5OSs3v9ufgjn/NObQ==,type:comment]
    B2_BUCKET: ENC[AES256_GCM,data:rl/Z1aWZUsB5,iv:+iwYgP0qOgStmTcm52U+5vBggG5sVgFrKj19VZ9ueDI=,tag:pVnR0YStM64DR5fzj4YcWg==,type:str]
    B2_ACCESSKEY: ENC[AES256_GCM,data:Dw1/6BuOdhw2oEdtKlRmR0iKIBd1LbhkaA==,iv:mKy7yALu8nxE/dCB2M82Hu2SVeudTGUU2YgAHH0Yyl8=,tag:PKVWaNxAxWILMlWOD2qxtw==,type:str]
    B2_ENCRKEY: ENC[AES256_GCM,data:L4VmqFWp0qMoKVuZiixe7vc1xu18V+tV9x87t33SucU=,iv:3MEQCnMJXsrlXwOO4Xy0BMpdH5pxTOHLhABqScpx8Ww=,tag:pL2uQiKjGj8S3qQGpU98jg==,type:str]
    B2_SECRETKEY: ENC[AES256_GCM,data:enqSilvlq/EaZlJWEGS609BzTST5+ZqxAeEaGvYiZg==,iv:7f3fQ/T/5CRIpIVkvNp66CpUildMwplQXUFDeCLI1mM=,tag:wh7Ecok7XwDgEYoH0N/r2A==,type:str]
    B2_URL: ENC[AES256_GCM,data:XSxK6Na3IUGZ7RwMjK2Xi+PTOdCFjSrLl9FYkUsjTVoRWraPOjg=,iv:FUpMg8jIfKEyLESkJr/5IOwIW/NNQafDwSBrIVOtaCY=,tag:k56R04vkA1mNBLv4b+rAlg==,type:str]
    COLLABORA_ADMIN_PASS: ENC[AES256_GCM,data:qqxMwj0MiYB5Gt91,iv:83nv8+GjNRRu0nCvpheM0iIoQe/Cl+2ZmWuLfyIdXds=,tag:EfBjBB7D3UycWRv1/px84g==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:ogbioG8Ykkk2eFis+6zMhXTSgWxlVhbRfUadpQ2P/gEx1+1ra8N+zw==,iv:Gu28TEiQdvx3y3lG95ASlVwao6nehAQWhIvvwvLbnpo=,tag:nHdJqLmF5XT6V/rF51Ur9A==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:d6v8WQ==,iv:TzyrCysnHcf8YmoCalL/S7YFMiL30Sif41nTeajZB88=,tag:3KzXMEcipYQqRwjOCh2XIw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUUgwWWxjMmZqQzRXRzF5
            RVhEVVludERRelNSbzM5NkIvSzJ3UER3c0hNCi80MkttZC96OE1vQTA4VnkvRStm
            OXhIRXFzZVpwcDR4LzZkcnFtOThYUG8KLS0tIDIwWnQ3UlJldHJFU2xoc3U1Mnpy
            c1hkUzZwckwwa3BBRXBiOWk1K0lZZ0kKHXViw02BXIGor48qvMcasxj+TqThNNKp
            31gKuKNXPFslmoyfVwLuu4Rdw397XaMinx1tRX/CF++Kft8YFbZoCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T16:30:52Z"
    mac: ENC[AES256_GCM,data:O30MGl0xEAqlJKoqZ6j+0RWBOrXm+2ksx3hDbn5IuQtYslNy2xY074rVyZPGBMY1UbJOp2yqt+8oEx3VGbAmw3vcM4PyXmG6guz/KvqwnFgYE/s1WNMFLPUI0c197YZ2V/5yZs83cClLb/+YOa6NGOk2LgyNu2pSS0KAqcXucas=,iv:hmRMUYYc3PchgDTOaT9PT4ouF9u8Td0V0lHfetWlsp0=,tag:sIsuXljQMvr0ruWTy1jdRg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
