apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:tDCbDUDisckADmxY3kOtYXf9Fs+O1lYaKEJWQKEKSK/XHbwIVRJnbu3CtzzTzl4YWINlYwUHWCqd2NK9E+J4eY4=,iv:aBYlmd878X4SoHB7mpBeOrWfqFFR6NPKfc5mN8saYXs=,tag:lWQG1XS/bpYLBpsLbZifIw==,type:comment]
    #ENC[AES256_GCM,data:GxvIDMTm/oWqXHRlihwCswS95FRutavKZCbBPPkKJ3MUniKrPBzIIjRMee0=,iv:MkjMBiqT14Gx7drszVrhCSScVNYrVXbDqFJWLffkCC4=,tag:F0WKMFolrTId9/6bhaiTbQ==,type:comment]
    VIP: ENC[AES256_GCM,data:fq3HsqosfLwDkyU=,iv:1XuSGjIMSEce4+mC/C3K+bZ1xLu75JsCiGhQ7uKslFQ=,tag:rmr5fdK/VgvV5zGcmt8IEA==,type:str]
    #ENC[AES256_GCM,data:6AbxKSlQhI7f5klol265J+Efdj6DDXO9j4w=,iv:wtuPU/7gJtYdKuZoBV7EMlWtjr2nMwv70F8Elc5A7Is=,tag:tVXH9KgbGiN0kwK5WWPaZA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:M+rwyJDd+7SO8jo=,iv:E1PJvHuvPPJb9k2TJ7/jmCbvSM4YR+SFkNb5k+/e9U0=,tag:cwVweb52Yum5I28QhQZKCQ==,type:str]
    #ENC[AES256_GCM,data:UtTskx78GIg/qqziUxkwUFacpAaiNwjYhvXFleL/09GniA==,iv:zZ02jPMsT4uusaw2hF9SnldHqlWg4EDunB0P7QWWjVI=,tag:EIQVq9fHybtMq8CF9QlnsQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:O52n3BmOSVpeYA==,iv:dLJ4JImOEd/Vu+EXnPW8LGkk17pd1pAt3PY0d3hvsDU=,tag:k8TFp0qjg3P1qCcWa5P+Sw==,type:str]
    #ENC[AES256_GCM,data:0NEH9wnBr8ja9SEIocgtRkJZnV9vR8xrmNSKQjPzotHne/SaG+blQNGi2oSs/Ls=,iv:qbbdpHJAQPVwvv5UuzsdVsOeQmJU0U8Rrj43Ups1FEo=,tag:UudJzh6b0MFlbLSLpxTWRg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:5U3dUlM10meNh0MClkk/D772PnhKpSQ=,iv:ki47Uil9hh/EOo7RO+h1YgP+vaKvuE1WYaON6/7E3FM=,tag:G/Cqnhe+Ypw0+IyUGr1fxg==,type:str]
    #ENC[AES256_GCM,data:JHHFkEYbFh7E0a8vVF/z1DmD+8ZRJiRVacdiB+YSJfu0Z/ARayxUU4rVy6cu3e1xG1qgzUN//7SXJFUpGLrTKLUtKgy+JbsvmPO4ctm63FA=,iv:IiATnLs3xw+dqFTOgRW+Ai15eYviEbFEoYQJ2YynkTE=,tag:PR48orQZOz4stD1oHiHHBQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:zZ99h2KuOtgU+lU=,iv:rS0mFqSQPmdH+GR6D6o/5AUCxFFSeXx34FSZDCOfm+0=,tag:temQm16Ja56aQHS33DfA0A==,type:str]
    #ENC[AES256_GCM,data:6uxdLgng/Q6Aj8UWFPMY7YafxnxJtv49IfZHIH16X7zTMHgAC3yeEydj0X7voJZgO3PF2FypbtI=,iv:P34TjYu5IGNbz7Wbs3d9Raeka/aN49mxoeFw6P3AywE=,tag:T7IX3imOL7Gh3FnXwuBpjw==,type:comment]
    #ENC[AES256_GCM,data:AjH/Ow0KDNLwax6EfX9kO+7xLCT27WiOWw==,iv:rxGeGLIMWPsrjhvFCnou9zBAZj1k9pmeVHAUFa7XKYk=,tag:bLbDsPVqJ3VDFZILBFy5pw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:+DbhxQcCTmf+TZMt3fU3yPCdnuyvhCBazGTiwKWdTwFMK1RHCHPgiS8sM97gcmA=,iv:QIxZLGFSShKxbkEfyd5fjxBw/9giJWwJCGwA/Noj05g=,tag:/Q5Es/nE6fQ7LIFt8A3nyg==,type:str]
    #ENC[AES256_GCM,data:9y+u0jhKazqm7fdbmA==,iv:fpp3gA+1qQv1B2NSKo/aAa7SwrJQZRxRnnwiRUVVi4U=,tag:ZEmuh40Q+KN121OiTExOvQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:OmcOakJuJ2XiG5K3Kw==,iv:jshP/yzTYT7mdAV04fA/RLDE83rY2Misufudejj0/ic=,tag:t5u2IJkMo/IZRGguWvBK4A==,type:str]
    SVCNET: ENC[AES256_GCM,data:ZduOdPh1QsETw0ynNA==,iv:3Qpn3j4Kk65uYvPGL89ID4vTMT6Krb2szq3cwjufhJ4=,tag:Dz6FVLbGCqjUie75kKRvcg==,type:str]
    #ENC[AES256_GCM,data:w0w/Dg==,iv:PKGMq0ebUk6uhnoOm2HM3siOgo0nx14WJ7b+Mfvk1L8=,tag:Kdrhzwl+w5JD0OQHG01RuA==,type:comment]
    SPEEDTEST_IP: ENC[AES256_GCM,data:N6m/z6c9Y/MdNSY=,iv:0sXtG7iIfLfiYPagBjku0wWT6C76s8+TEOHsONL1EkM=,tag:UTUkbZuaCnuB/4miBGdlvg==,type:str]
    HOMEPAGE_IP: ENC[AES256_GCM,data:05jbG8qehyCbo2U=,iv:nk0uoqJtwVIPPeqHxijA0YzWqVwuqJlxR+WnSCMGHCg=,tag:BHhKwpOdaUt6p13zSffiow==,type:str]
    HASS_IP: ENC[AES256_GCM,data:gdcLIF8gn9PCnsc=,iv:O70q5NTg5EsmbhH5uzB6NYmk9kAlTMBDxajF+8nsaBg=,tag:ihm3kCwwl916mgulQ27m9Q==,type:str]
    JELLYFIN_IP: ENC[AES256_GCM,data:ABeT8OP5NGSBPDM=,iv:rmccB0L/bFI1TZ62I1vPuBTdFjGil9SlyHSWHo6inkM=,tag:7g0iSs+qNrl/GTZP+/zqnw==,type:str]
    NEXTCLOUD_IP: ENC[AES256_GCM,data:HtQoAL3SrGmWolI=,iv:G604B62DRwXCsWy4+GJ+UbFIKGe7CvhfUJcpaWA5GYk=,tag:i+6Xvk+FZgizj0auGDn4Iw==,type:str]
    MINECRAFT_IP: ENC[AES256_GCM,data:MB8Td0Y98RTM3J0=,iv:Z68xLq7qKRIeg2mPD/vVyrn8NYzPbszPA2H6WXivgRU=,tag:QrjNhxLc1/cl6vn2Tsotfg==,type:str]
    HANDBRAKE_IP: ENC[AES256_GCM,data:unsetIAZz1NtQ1Q=,iv:5H8rTQ/ORaQGrqbHctbHZymv5ey76IlSVdrPumskmiQ=,tag:TJPUAReZIOUNNqsG0bljrA==,type:str]
    DNS_IP: ENC[AES256_GCM,data:g7r/E0wASmBWQNs=,iv:CTp8S/YQgzLMT3CCEJokoD3a4xaR9RK56mHWGvRLZpw=,tag:piPDGPfJvc0OZuZqem41Qg==,type:str]
    MAKEMKV_IP: ENC[AES256_GCM,data:YQGVXxeywhhpBas=,iv:g2OYzfuui1L2H4sC3rOCgma06l6mncCMDdwSH1NjREI=,tag:/3DEpmFQ1UtdQQpqcoe4sw==,type:str]
    PAPERLESS_IP: ENC[AES256_GCM,data:AkPon+XVyf8NucM=,iv:z9yjwg54Fb9z2weH0pVztn7mP2PSV4KYeK1MeIJkdpM=,tag:i8m8Ykt/K2bXrX8iavB1AQ==,type:str]
    COLLABORA_IP: ENC[AES256_GCM,data:/JXwHORrXN+OHG8=,iv:Pajq/RTh/E0oLPdY4R4lY9t2lL1e96p7za27hTAjF78=,tag:aDnCVcFG+aavvmaLzD5I1g==,type:str]
    AUDIOBOOKSHELF_IP: ENC[AES256_GCM,data:wI584x3IjXz7plQ=,iv:BR74eJySTrP148LPQU9izqk4eCEqSlyzW+Hqz/nxpuY=,tag:wNgH1cP4GL6ECsYRKObSmg==,type:str]
    UPTIMEKUMA_IP: ENC[AES256_GCM,data:pKdluOuA9a4ajcY=,iv:MimCsxE8gQWGXDkak16PbD7aDxNKMD67oc5vrnzQuAU=,tag:veEL4dCtaRUcXaLBSWY1Bg==,type:str]
    PEANUTUPSTAIRS_IP: ENC[AES256_GCM,data:o0chNcVm7oyYG7k=,iv:gH5Bgn4mwNkGa2guDExPxPF02SgJBt8RRF7X8ZLQmZI=,tag:vm4JHyabcL8gTJrIHTKIyg==,type:str]
    PEANUTDOWNSTAIRS_IP: ENC[AES256_GCM,data:bc4I2eWJksnyY00=,iv:VuPsumRm8p0WHC/Kvx5Fcl4mc59T3gCwuIQanQ+eaEA=,tag:GcJFHDlDfyhiTXR2hjSjWA==,type:str]
    NTFY_IP: ENC[AES256_GCM,data:DZO9tqiM2ZpqDL0=,iv:aXS/qqeWmcn5WYnqhmqVZikJathy5OuF57O2Tl3zngY=,tag:dGW5WGfZB63hgjvQfNGrLg==,type:str]
    #ENC[AES256_GCM,data:cRkxZQBfMw==,iv:0AURcxgGoP7KxvPScYvICCFlyUE1pQYF5QlAThBhFzg=,tag:f7R0XUlEFfM8ilawoi/yxw==,type:comment]
    EMAIL1: ENC[AES256_GCM,data:jwuT0R4k1V2DsmHUo7ylZA==,iv:nKGfdJ/1fN5C+eaIHdwmFeMJ8RfJtUwyMhdnQuhulo8=,tag:T8cP55iheH+F0gmY3ThoDw==,type:str]
    #ENC[AES256_GCM,data:b61+2U8=,iv:aiW/rU72Q7TI1QbEhLECbEuUswV1ujZYjEE4syHEItI=,tag:ySoN2X5tb/FxiNZ5zVE4Hw==,type:comment]
    B2_BUCKET: ENC[AES256_GCM,data:x7rVF8Kw88sV,iv:9Tx0RkVPL3e1i1BkfDYJyYjPTc46III6ecRdMx+9edY=,tag:hItiNGTLd9eCKdcbK8B4Eg==,type:str]
    B2_ACCESSKEY: ENC[AES256_GCM,data:h0nu0A33FF3FHCyvsQYwlmwzBmGp+3IR3A==,iv:wvwREkhNNuwYW24DL1EOqaPTmXesnqAfnIUBTdlwqRA=,tag:+7yARkoaslHyC8HmVgZQtA==,type:str]
    B2_ENCRKEY: ENC[AES256_GCM,data:JtAaqudknRTcIrMYkzzRKV2iK0IeGLsd5wJ3trkBH0E=,iv:1RNOHzeZtYzze7DFfIBKNeHf2ssnrLD4SXVrHnUwKpI=,tag:bGOCaVU1ROYvyjf6zhDOyQ==,type:str]
    B2_SECRETKEY: ENC[AES256_GCM,data:Xvvv1muYeA1R3Dg69Om/WlxX1xbXts8P4+9KXx96pA==,iv:fEkg0zBt0a3fkbIPt/sXryiYP/ZRBeWmG3bs6oS/3xo=,tag:HthQC9/Z0s1kySUioFGs3g==,type:str]
    B2_URL: ENC[AES256_GCM,data:w18FAZwTLDoJY3z9pMZUTrwBnopFN/jj6CalGC3za7nDLazC55g=,iv:8jUilFl3bgz2CiIv6WUF7BeF8PHfzvF0Qa44VBi6Ksk=,tag:lV7CVSMFKRQ4TFlEt4lzAg==,type:str]
    COLLABORA_ADMIN_PASS: ENC[AES256_GCM,data:v4jJc7gxPVOgOPrS,iv:sRXqE27/HGU0tzgBI3pkuB4nafuGr8WxqwZw+6UaCl0=,tag:A9BYts4d8H/O6QKd/YlNYg==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:6mO3nNBd+DYviOmbsfqa42PM5LGNnWU/M0ETyko4L9Y+N3FGNrSELA==,iv:sXDt0rohm3grTUy7o6AMEc1P5kxfL8I9dHZZkjtVwgk=,tag:44I7FaH6woAwPNbHci8Y2w==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:akPvRQ==,iv:mmG/gOp5/OYPZxJUYAxPrWgz6R42OwISiiEbDOyA5Vk=,tag:If958ZUR4kX9Ko+XTFK4Dg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSFJldGdQbFkvZ3o2ekl3
            akVKRks5eXl0QmJlbkhmTkhWTXZpS2l4ZUFNCitJdUlmNUFramMrOCtwT3hzVnV0
            RjcxNTNYcW5vdmgzOG4rU0RxZktPemMKLS0tIEt2cjRtTFNYS1htVEhjOVVQaElD
            OHl6d2VDUDI5anlVRlZNMWZQMWVqSWcKqZ9db+R5U+0fReWN4iROwGQfdAazlpbD
            yuCPqTVcHdlC6nuPrQ1l4ERGtY6lCotKck0dYp/eB0EMNMwc9Unraw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T20:14:42Z"
    mac: ENC[AES256_GCM,data:xofa0O66kVVXow5KFUD34KDHm4W63VOfvVh3v6CS1AkT+JHTTRQNVmZmVeNqA2hWejCrF7Q04JSd7Q38i7CDM/+ZvAGzMHRl2CtdukIV3putDj0ZjVx/UzPwgESOfPpnoMJfJjqaPqMOm05lKQgFOIY9wLLwYVW4NlNplA8oEPI=,iv:QLT7RB/I6cn2b7KHPiNEwZR57/xQuZDOvMEm/8kakI4=,tag:kxYXB05mx0AmZg7+0vhmiQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
