apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:YAcIBdIC9rOnGKYiNKZTagUWtoN80YKcPfakv2jjKAZjo6+ZYOGsw+AOSmamN1w2X/qTlwrBVIIYLGRqOMsgnDk=,iv:AvrhenInY133ZHQg278hsEwaqKPaaHI2dErOhEzDNsE=,tag:O6SV9ungjE/DZUz2Z1wdDw==,type:comment]
    #ENC[AES256_GCM,data:WoXl7EWAkoIqvhuHBNfMk5x1gufhW/96INaQ5N4E+P30rz16nbeKTgf7Vhc=,iv:0/qmGUkll4gqCPfn46S9DYZSc3HsOTN2rkzfvopEQR0=,tag:pbdRMWYnaI3gcw3OqBG73A==,type:comment]
    VIP: ENC[AES256_GCM,data:NQPkg4+eHVtcVb4=,iv:XLEfsUGy3sdEIZ7sIjZixmRiwNVnqfJtuqYTAbglmu0=,tag:ZeI2jbTeO9+1x7cCWMGjUQ==,type:str]
    #ENC[AES256_GCM,data:3WHPhx3yg9oZdvM9dzSHFHQSjgWDMsO5qrA=,iv:QsYupJ3dZUloGipSycKBYRiqymmA8R8RAybUISGklFk=,tag:gYDKCgoEBSzeh+Ipa4QR1A==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:/GCm/jaS9PodMb8=,iv:maEdWS/rcekq1dR0JQb0gMVbjRQU43ESBjbrmdT13ac=,tag:GwV5nwOPsO/epCvXx1V0lg==,type:str]
    #ENC[AES256_GCM,data:oCepjmLM24UGOczjs3tcmBrez1dM3yYOSE6IS59D+G1+qg==,iv:JrVmHZDlN/jxuZb8VnidUW4B43GxQ3Ni2XE/mxuvRes=,tag:aqX2hP8VVKo78EwtQD3ZCg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:nVKkYI4Qrdy6Fw==,iv:4mx9ra0WX/m2qjtweztjaj9S9pcFWA215IdzYF9hREI=,tag:dgA1APZSmlyWq2RZfYN9AQ==,type:str]
    #ENC[AES256_GCM,data:+GDmmiPw8DM+eNhACSw2TnZHr8JOyd79KMLa3zJQX/SzEl5UG8tiwT0bVvMQ4Mg=,iv:JnO89Jfcar+pCN0th3TnEQ2uYMj/RFEeV1jDIXBgqFQ=,tag:gPgqSmumf8DtH9imHH6Irg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:v/Ym/6m6KaWmTp+ZzMa/wIlaOUYbvsE=,iv:yv5gtZxyeXDg69NNvPVRSdFEQN36N1V6lEbMaOMZv2k=,tag:ygAv6vuzTOWp+MI+mYzhOQ==,type:str]
    #ENC[AES256_GCM,data:XF6Gs1fkq0AmDQQg1iQT+sSpCetFyIYFt/K3U7IGg+O/bZTcVFdstvM+/FJ+8UUpiNhL7zyZLI0BIGUwbbVVYqjl6JgZaiqBa0pkHIdHxzY=,iv:pR+A6gFWwapa19YMLIxw1+VXlegM8aJFJu1MFHnqRPc=,tag:qndvCCWSNBdYX18lmj6xkw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:x3MX4SmktR6DUyQ=,iv:liKnJqc8irrV64Yl4r0q9jJLBG4eUZxctCnOIXb1Mmk=,tag:y9zlRYkLNES3W/NiClrBtw==,type:str]
    #ENC[AES256_GCM,data:uKeER0P/7Jo77jauGPEyMnqoCcvOYSZ+GyGSy93cjk5KS/V6W3I5pE26Fiegx0w/4pMg8TcNpR4=,iv:/pVtypZU/spCeXc3nQYkTa9/h2YpjNpIhLwapmJOzZE=,tag:vAHylmD9Au3TxFJBV1ojow==,type:comment]
    #ENC[AES256_GCM,data:J6KEgyfBZs+8GHYqvEpmcQyIjNjY+grUrQ==,iv:ArAIYh/4SvoEZIx/tMbgyWfGYcVhVDtohHzBxoY6Ki4=,tag:yLVc+GvXMkr2lYwYBY/Y+A==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:ed6DcdQ4dRwPIXHrnn7VJ/TNk4vE/BzvoPCf2TsO7br73RJlxE4WCaxPC6n+S7I=,iv:EqFPRhgqh2MVrzh7fpW+BlzrC8z/CZe3tA2WFHOV2Eg=,tag:DI6mdCA12rs5akBptarlhg==,type:str]
    #ENC[AES256_GCM,data:1wKFiHsBknfwU2Znvg==,iv:EDQy5sjwqGOFv+ElSQiGgXkEi9/VK/oCPv5X2DuVJO4=,tag:fxLrMFEKObEzsgoviGsOzw==,type:comment]
    PODNET: ENC[AES256_GCM,data:FcyIAF+R7vbcrUL4Ag==,iv:p26fD2Nm+FfQKfTsfl2BFLg0L8JGnBF9hU0zYjxzPW4=,tag:GecJ7mcFKJWKz7B1RlHreg==,type:str]
    SVCNET: ENC[AES256_GCM,data:EYE3hcf5Sx+83lXS1Q==,iv:93q8uKKCs88uWaT09/Ouln1r7cI51zKbCjBsFdmx3Do=,tag:4rfcgjwO0xpJvUJJXqpv5g==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:iWv/8g==,iv:ENI3HihsgOOIfU6JJmvRVJRNItN3wtVw5A10FZgIFiQ=,tag:1yT6CohELdEOnpJ72YQqMg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYkVCZUdOc05xMnhoZGVO
            UDNUVjRlVGJUTVk4enlTeHErdDJZS2RCWjNrCnVtUUhsK0xrdUprS2xkbUxWdVZw
            S3JuOUM4OEVGMkU5bzNmSmd5U0VDdUEKLS0tIDJyM2xmY1pPSVFIZ0J4RXJmN29Q
            Q1BNWGw3ejhqVFJCQ3J4T0lRL3hqZDAKP1xxsjURRImkcFSOzyWtUvlFzRz3nI0r
            aC6uNcGAALl9JXnJ1G4/cNygYxlh2pyxt2OTokL+aCxTJbO6gfu0qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T13:24:01Z"
    mac: ENC[AES256_GCM,data:Rz2fiJAs1Lgh8OUIWDi3sN4YFjddUSwVXuy+D67Bj6BhiPeGVF4nwZ9oprR/USaw+DEn23bXdo+OiCNgie8yQitJrRT09djX9KlePYnKf4GKnytbLdukYI3oAURnko3TekeXYAZdhb0roxThGiGz2ddyVqX7q2exrRGsXfWkQEU=,iv:rTMrohhAVd5KODlmuc3uhMZAc591vEh5xbEuZ5sPNT4=,tag:y61UeD+TthqdWi0VzX/gIw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
