apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:80NoMGLVxM0pVne92gY+L18kQ8vEKV0s8TJkFqT3mLZhtsQBEZSORtCXl9uM8U3jqN0fhsKDZm9TYCY3ckKrZSs=,iv:oak3jR+V2DeJI8IRDnNPatTeBAHo3US/IzQbiwjlCm4=,tag:pGKdROkbBnPCExW9528coA==,type:comment]
    #ENC[AES256_GCM,data:ksCXd9tqBMdgPLof67AMDD0MFys0NdzkJT0ntWnpFX959pI4nzWPx816vIg=,iv:uNUUzrx4DfpbUfu2nnPfJLqq9YMOCfVrefRCY6vPGbE=,tag:RBx4uBvtZmImSb3b+TFY+g==,type:comment]
    VIP: ENC[AES256_GCM,data:6U8fLUCIihEJkVc=,iv:6vzYJ/G1SnrQcCaUHBVyjRCTE91LCJC3Dj+USErJv5w=,tag:74mm0KHrRElJQPqp46/yzw==,type:str]
    #ENC[AES256_GCM,data:xGxdion+aWhj0mw//LeV3ozNPcNjOysn41k=,iv:kTcbpCa5AdQIBc2obnu7eUSMNOEX2E4O/mKjLE8CyuM=,tag:gU4JrpKG1xe9WlWWZdC8TA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:d7+OqffRXqcGakE=,iv:M5D0qAUqW0FD0IUcM66KSVNeBrbED9+QvHeZ5A4vuWQ=,tag:iyvV3awEacts8VVg9oEF+Q==,type:str]
    #ENC[AES256_GCM,data:YZ4HXMv14xFtbYuxjU8ily1aTSBUJXxgmTs719CPjSPIvg==,iv:e0S/7TZEbvMJUaXOJIcpg2jxMp8+wnrenoioQvGrTXo=,tag:TjU+G3WpkaT9OD/42FuydQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:W2rJoVYbd3x81A==,iv:fwVdzHu+I4QEECBhWabdzSNeeT/C14j+fsZFjX5BpmM=,tag:Sz+QLlBL5pH3AbNGkpuQeA==,type:str]
    #ENC[AES256_GCM,data:IZ6c01MO4lUg0rjufP8C2EyYQ/qWsblCLsFYvtGkg+ezQ9qfitrRbZq0dqZRrlY=,iv:jfKViYx6Iy2E4RTOmafSEjLfwY6MwJdyx4Vb4/iDpw8=,tag:r6JDFODc6J35Otb7yeOvyA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:5+T7PqwlE55OxOwO6VBopSSFf2o/wy0=,iv:QD/wsVfpWGnGT6488t3VqxPkMBiKUgptHfeo0i7HS/0=,tag:y6omxZg3X5FnVkTk9z380g==,type:str]
    #ENC[AES256_GCM,data:+B9vvCUv8E9819pubumkguTAQz/6hHm2pvNGdwy4tN+1VmvJ/U8738cwvsoYi1Pgf0a8Uw982y0ie1GYNmK9JgrbLyHjCnOkNG8rtGp8pb4=,iv:7H+4y9MW5Vt79bdzPfslyrFiy48wvZsKVVaj2Jh79LY=,tag:PPxd4skKyFHcyZmzRiaXSQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:r+fjdLwKc/LKWf4=,iv:VjzlbF3PfwO6y5q9VIuZv+Q39nmAmgCGT1L8dk6sX8I=,tag:i70ui2gir7IFF3maq+YNww==,type:str]
    #ENC[AES256_GCM,data:NacyVVZqRCBO86MEvVlAcbCZ/pEKwQGwrRBAqLVoH0mALGDXWyfkBN5gvYFwGtJ9koLZfN2UX+w=,iv:uOYBORQ0/tsz+dAV4AVR7EuYkSB8uqWpSieWQc36BAU=,tag:kqoCo9D9u11lhwJfd6sx7w==,type:comment]
    #ENC[AES256_GCM,data:f25XeKSKmcIHj6EXAdD7Ar3PexwqnxUmhg==,iv:04LEtHQsgSPrYfQ14lvuX95Hl0h9CglQ2qLW1S34f1M=,tag:AVkt2DcbM8BCYpIG7/P7JA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:M5pb0kPRlAWcdXfeQc3ybv0MwRWCcuVTuw8gtOAOcGw/6/c/qtr5+iqRWJBhjdM=,iv:sc20pJjrvhnXZwhd5AexXa9RXjF4b+DUU+AZB3U8Qrg=,tag:wWNwlXPneQG/z/dQ9nxkFQ==,type:str]
    #ENC[AES256_GCM,data:9zSm4jsuSWR+JIS9qA==,iv:AfZgBnRctLWIHuuRVXulFUgkEKdqUbc+h3OMz7SwLtE=,tag:yuEfHYymYIRo3W0kszxOSw==,type:comment]
    PODNET: ENC[AES256_GCM,data:UAgHGzrQajVn5wCpeA==,iv:1K8Nosfk5aVr39u6/ZNKf/5Jyt2QLmEaTsk7Br0x77M=,tag:8CWXPdkuDDKU3yTAvpre4Q==,type:str]
    SVCNET: ENC[AES256_GCM,data:hpwejWdIu0nPxngdZg==,iv:qklgIttoSpY2nR3JxqxhbMc2mkbabjvO68+Ei+C/bm8=,tag:US04Jg5+erY7yFhgM14wpw==,type:str]
    #ENC[AES256_GCM,data:6Z3D8w==,iv:dGOMsrSwMy4tTreopxtSTIMHTrpkmF/qSLUIOeL2vM0=,tag:EGkiWZZvdT+wfRcaDD6/4Q==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:gtGR6HGzYhaAdEU=,iv:61Kp2sH6YlSUvW3fWlvDJMr7+USKFcNWkB9Co9OafWQ=,tag:UhFC7PZCono2D0ZmLWa1wQ==,type:str]
    HOMEPAGE_IP: ENC[AES256_GCM,data:3su2kEd3YRIOomA=,iv:09D45UXOieGJQADyDEftKEIDgCAnS/oG9z/RzA0CPeE=,tag:i6Y11/UPufXwki+7jk2/yw==,type:str]
    HASS_IP: ENC[AES256_GCM,data:sWRZrcrdlPyvXSQ=,iv:FyAQcEE8t+Lp9LysJ+ESjXdR2QrCJPbNbSznmzqOptQ=,tag:EFyRaPf3hVE6eQYAdCR4iw==,type:str]
    JELLYFIN_IP: ENC[AES256_GCM,data:C3++uSrkIzkOXB4=,iv:72m1DKOgMq2EOUR3H2J6w0vmnITrS/nvWeXpWTXv5QU=,tag:W/cyi7mp/iA/xKoSXAg0mQ==,type:str]
    NEXTCLOUD_IP: ENC[AES256_GCM,data:vVkIwejrM5FX8ss=,iv:Rskcf3SLbU55+6s1hID++eVdPwCGpKVl0/0ZN2ctsFs=,tag:5WR4bdhGBqCgx3Ye8ImEgw==,type:str]
    MINECRAFT_IP: ENC[AES256_GCM,data:XTfBX7hjBPEbmdE=,iv:c61Pp7fxKewvyqqCk3v8xZPxza4W4mjetU4sSMpEZXg=,tag:WY/lA9L4LraJx74XHUa7yg==,type:str]
    SPEEDTEST_IP: ENC[AES256_GCM,data:evK+JbVQGAkEYDQ=,iv:GAeQSml6dNgzdo/8a4C1o0D2sL6u2L5ahy+isBiTTAA=,tag:Kb9y4xvoEKNytgUiTpazXQ==,type:str]
    DNS_IP: ENC[AES256_GCM,data:gHi+LXlalZpj2nQ=,iv:i9sA5Ut/73hUtRPew31iuiPoPIyTLxNEdHe1DkYl4uc=,tag:jkY2w3vdOThboBXP+Ak3nQ==,type:str]
    HANDBRAKE_IP: ENC[AES256_GCM,data:XZmt9ngVcxw3+KM=,iv:3vDoa1RX8ym7qAWAesDHf8AJ270lkpU0g2ukEOQ5HgY=,tag:53ZVoAWCEUm/Fdx15nY88g==,type:str]
    #ENC[AES256_GCM,data:eepgpuss4g==,iv:0xdoOaQ9u7uc8TJ+rfULm5ANjxureCf0v3uYFB2YgVs=,tag:QF4g2LpEARdpGhCtBdxzww==,type:comment]
    EMAIL1: ENC[AES256_GCM,data:COI8xWJ2QVKzUfFloGjvAQ==,iv:xUNKvxesVJdH3RyVVuhWXz097aiVH+czCqX6VVqVjZE=,tag:Wx1XDXIwVKNB4CXC7+RXqA==,type:str]
    #ENC[AES256_GCM,data:YxqMdcQ=,iv:mgIt1GTSpDbfBfJ9VNKz5y5I6pWKTNvWo/047fhTdgI=,tag:PNzNO8JKUHAO3+wTix0mLA==,type:comment]
    B2_BUCKET: ENC[AES256_GCM,data:AbVrzO7qyvO2,iv:F9v0FNUy6S8m2j0v3tOtt33TQGapKbe3JSIfRHXooTI=,tag:QL7iWVpcQKoXTUICt+hCFw==,type:str]
    B2_ACCESSKEY: ENC[AES256_GCM,data:hpw74iOQPP6nIA0P3QGE669TPyzZgChjVw==,iv:AhHKni0pnlYEz5KOVqzlOm/iVnn5raDryMga217JDsA=,tag:pjeccGSh0aKXzPX3ournAQ==,type:str]
    B2_ENCRKEY: ENC[AES256_GCM,data:f0TooxYfRTWgL6jYvTltvnx26sCRNJPIz/NFd9lBjMA=,iv:d2qcbVRochVqsQmvbZ2iXS6xxzHpOEpWHa+JttM2rZ4=,tag:8NRCHOhaw5hYr7vzQ4Ifrw==,type:str]
    B2_SECRETKEY: ENC[AES256_GCM,data:/YQ+VknaPubUAPPXBdLz37eDDMohiRS3jC3b1ubeKQ==,iv:Wvu7HTGoENzxAKYZuGHWn0+mFIi0E9NZagYMzJW1im4=,tag:4ONnRuRfiZl/4ulSGtofLA==,type:str]
    B2_URL: ENC[AES256_GCM,data:ODvHqdRL7BsqqSFGYBy2U67MU6ZbFIyJjqQ9FTcK5fJaL6xC43E=,iv:BUAG9bQusObcBs4PcGzg1nsn1LAg/ObEA3MHgwKPkpk=,tag:VSPf3qk5zqRph5AVdHN2hQ==,type:str]
    COLLABORA_ADMIN_PASS: ENC[AES256_GCM,data:1ZFs7vcaYRAg9U/o,iv:u0HS2KnNM49jb27ROSdkdz+wjF0WeTduKd4v9TLpouY=,tag:87DKSfRUElpIwO8uVzzYTw==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:MOwJxWm3Kp14HYE4YsCGsRgAOrJj/KD4zBMT5I3V5Cq4HNWspTv1zg==,iv:1/onzoO+7WoXfP1eEKH59fjcQq1p2oXGIVXzN7ssUGo=,tag:mxP3eUgJ4KQMD2ACDv3tWQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:3eMmkQ==,iv:QFTfGtedSFJzDNx/vlXGmxiYJTqAIsST2WDC0HaSVUw=,tag:hGrgLp/wLrzx4yl3/PdWng==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNkwvQkhCWnhFcGE0SVp0
            V0ZoNnN5b1k1K2ZYTE5aL3NlcWVna3J5bmo0CmMrNThVVU9CcFZLWXVyZ3R3c0lh
            UkE1WGVRc3hIdEVUb0VnL3J5QkJxM00KLS0tIExKOWhGT3htTWVnSDh5SENHakhs
            Sm9wTGxnNS92b0tmQ2lPNkU1MDFLSjAKeNSufFCDj73xFL472DwHcTQrUhkoG8V6
            jFQOvxZB7Wr+u2hvTev9eu86rnjgzdi62sC2Kn7mT09S2WZiCogGjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T16:52:52Z"
    mac: ENC[AES256_GCM,data:qUBRNb6tLrPyZCc9qaW4jEMjv4RmN2+92Di+zK9GlDh09jSSQlUyeuETVrHlREdcxWbmnAd/mPezYPoOMoITzELiVTdFBYQe2Ef5HB7fpdelF87CXgJ+umKVCQ9LABxfmV3YM2hW8OMUevY8YOdixnFO0p7JP0vh4DWmE4F1/L0=,iv:lCcJFurbiSnq+m/VOzX0jMqXCDErDWLLlYSxJoKldaI=,tag:C+Z4OmpI8hVrH8/Uy7aQqA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
