apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:HjoKnMMGUIyZr8Wbils04vr6FZD+E0qPB52yJ5X94EUfIb0Fp43XT1jauacH1Z+AZFHPRNffKXBqIaXIzWCY9N8=,iv:I0rdTaAklmGdgiR66Vn30VclfRpZxiYOI/w6t2hKqa4=,tag:GEdEb4UCNq15p5Fq7lD9EA==,type:comment]
    #ENC[AES256_GCM,data:Qhj3wfb8QNa2eJ8i5WrMscE3TzKiFE8dYu8hec7x2ygfYVs5zsf2vwws828=,iv:KqoMBphG9IKZQrrdLiPtlKSrgoXI48QDjceZ7evnb24=,tag:dFUhJce39nJ7bR5CxSGXhg==,type:comment]
    VIP: ENC[AES256_GCM,data:5bdIcUFiZTB4ErY=,iv:FZoURf3fZrRi9umH6zcrcovimo/1Iu6Pao979FN5Dh8=,tag:LEQ1KWtEL2g8P3P7j2Df4g==,type:str]
    #ENC[AES256_GCM,data:0Ana2Y73+bqrAbR6eQ10gHlKtHAQjlgUdss=,iv:0CfHb1+hMqZqUnwfG+h5pmQ0MphX4C55Rn2Wi1LXUzs=,tag:HAwIyy99tglfLppDE8GRUA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:5pt/n5hdDmWtc34=,iv:aqNpzPhyFRMBSS+g+i5XS7WDYQO1kULcxGfFTKyakO0=,tag:YXxz7TOSAZaMmq+HufSpsQ==,type:str]
    #ENC[AES256_GCM,data:B5ldEwN+d1mh3A0DU2KkHDkjS6Jwp+fwzv6saqZ1FYvCLg==,iv:jRkrC8/ugbmHKUhwvzoDvUGGyCNcTgt1iJufujy68l8=,tag:OEqh0dMslfJa2hKV0c4dAw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:9JbQQPGsYcO1Zw==,iv:CRa7dhM5SbM/eRHaY2u3MFRmcVEs3DA+Ts9Z0cNUIZU=,tag:T7h/ozZINz9dIbxBMUGUkg==,type:str]
    #ENC[AES256_GCM,data:MO/nESW9dds4Wd2Q/6726Xl0yo+peQ73gS+qVaA5IkYDq8jLaQmjnbHnogqvcWU=,iv:pvVmhDmk7xhkWBN7PwCZ8n1n6y0a5n73He9065XAVTk=,tag:wpYHjuV2/cRAtMUbPmVADw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:Fs+ZaErNWT4CgZnOj2Du0MHDi63QKiA=,iv:yfsUsl3pSFLQha5zbZrmlzOmklxJqA9IOcHcV7zUUKQ=,tag:GIPbk3Vp+IyFx7EGn7YPQQ==,type:str]
    #ENC[AES256_GCM,data:NQIl+DstkvDSt2KhP0AykMLWSv7xG9D9yC+qFeW0uv9TNGwPu8+fQxWF1gPtnKr0lghQvhxYFuHmeDr0W6hRHsPcCqZi4OuGx5fyqQN7f/g=,iv:2kPNEwES1yfg6UREPHcNtGwwfySKS1C6CsxX00qHOF8=,tag:hTjc3MBp/1Jr7iA98GdjTw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:xrYAoLkv0coYw7Q=,iv:mIm4FiPAjNziChkvSXA0qVy3eBIy5uVfQQWIDluwdgY=,tag:WFNzO+EpqwntnHAEc3RdxQ==,type:str]
    #ENC[AES256_GCM,data:/OlfQy8MGW3RRHWoNuTkEZKd4cJvzlzubcoTuipHjbAPbwRoTUFhO95cvbriWIZGKVpyxWqLrUs=,iv:Ez6UHFAyLM76ifgQIaA1zHaO968OElFMpF4hBQIxt9k=,tag:rmY76trJUOVZqs3gaQYpaQ==,type:comment]
    #ENC[AES256_GCM,data:FmhQUeX27/v1KFg1VRooJx2ctT+0aoF9kw==,iv:0PMRSvL7arJboflMKOYz3flyOhSs6G3rHLZRDGRbYaU=,tag:eVjlehUakzuY1hQD1zEX6A==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:P7HV1PrRbP3qsAqfSd3oEbDRjYWKRODm41O7jKLsFe5GfnV1I8wFRikg0/sZy2E=,iv:TRzFELQzLdyrcXpLVwVc3Z4A1mi7H5INtcckKIOoTE0=,tag:Y/ynfLSev2LJ5hM1do9IFQ==,type:str]
    #ENC[AES256_GCM,data:CVVuD2F2ATOaCFCyhQ==,iv:G7IjBkSSWXTB0ZdLZpq82EJTEclQIhEBzmjrqrm/j8U=,tag:uUWexbMqqsg2Y8qmCn9QIA==,type:comment]
    PODNET: ENC[AES256_GCM,data:QiKDjbEipopzidcIzQ==,iv:hHDE/SHAz9ZVh65mJ647loX+fO9ycxxtXF7zdph3Yus=,tag:A9eEBpmEZd/JrnNobqQsJA==,type:str]
    SVCNET: ENC[AES256_GCM,data:+WlLFiDLhQZEtBonaQ==,iv:TNHZAemq743P48DKwMag4txV9OqaOngDlnla12qiPH0=,tag:hdOTMPYANS9nnOaNfv2IWg==,type:str]
    FIREFOX_IP: ENC[AES256_GCM,data:oaRidVxHrlsVrFU=,iv:9QxOYVCEWUuw5srDWdKd7Nxy90ITKsF/nBJ9nTPtfys=,tag:4OiEeNZYd6qhxb8eL3mDOg==,type:str]
    SPEEDTEST_IP: ENC[AES256_GCM,data:KCRRTGw7YlarZ64=,iv:D/Lwmtebdm7KGNTmw1NKzSQKnQ+zSmTODbW90aZOI+8=,tag:4V64E1v7gBZdj81GlsWPng==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:TtWVZw==,iv:csfj8OKiREQRRlU2/GbEBQdjaB3NK+4zB2dloTRniJI=,tag:Qe9CYUV6Zw5L6u2CM8vMaQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRXhJdFFSZUM3TFAyOGZU
            TWI0bGRMZ042d2tJcDdKVHJuY1dobDB0dWlvCnNsQWVIRHhkUnBaQUNIb0pRZTBs
            L3k2NWI5dFRZQ09rSDhtNjN5SUlnNVEKLS0tIHZDUEhUZ1R5RS9JanZmczNjbnpy
            L0NTOHVKcnJZZHhGNTdKbXpPZGp3VGMKhqwjjfVL6qNBIwG/1kfLGzPyPLe6xw+X
            9+owEGRYaZz7vS42zoiyVH8yUxdvEEQg4crWLkfQj62fnDmOvIK0FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T07:19:53Z"
    mac: ENC[AES256_GCM,data:0gi5KRF0922NRJdNrs2Yz3LR/Ml67swduy3Q23bznJr2jgS7uF/Q64qmenTCMhF8KMn7TPc99CKUpT23HI9kRfXRdrMSCA0359JKfQIBGsk3gmHT8MFoREpk+Ui0X+EDz6I25XE1dpTJu1F7XcaI+GpevnEZtmY8L6kQCJibJsI=,iv:BOSKyFMM/uOoZyNFQc425uc8amVeIVK1JK0DEEiuU54=,tag:wjU3gztcZ0GwfZMJ8AGQnQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
