apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:W/PlRQW3lhNlkrD+3BzCq8XmPDNeqy4GfwrXyGtFROh3mjPqweEGxzfC+pgzd/viJgopCJ2l1I9gE5KG78/QUH4=,iv:wnQQTbqiTwSSBhCAw0KAOg60/F77W3AZmkda0Xk7opI=,tag:Q9UC79hzIlUM8l/ZL5zdPA==,type:comment]
    #ENC[AES256_GCM,data:Qyvz7y0uhK5sCdcTcAAIJluCWHHKYGpVl7iT9FDrVaLrHE07NBOtje8pr5E=,iv:rGSB/xcgbiCM4MtUwDUEtiDNgWv/O246XMlo+rfkdMQ=,tag:TH1c/IJKeVqG52ZO3ivg6Q==,type:comment]
    VIP: ENC[AES256_GCM,data:wB+AXBRNKODl1ZouL1w=,iv:STNO3aJaXy71U1ADEErDdXFwHHhkMjCsnxziV3pGELA=,tag:oqB362podvxP4oth6HfPlg==,type:str]
    #ENC[AES256_GCM,data:hvuHpVkkzuMJ0Vmb4FAUxN9Gqq1MWcgoybE=,iv:gJrjW38zotLBgR4JP7MqVBvPCDdQ2O7opTE3Fueg1NE=,tag:jUvD9I4qoGflZtF9aqb7Iw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:Oh8dwOV2lG5g7BRr02Y=,iv:d+Wwn9AR0MeiD7FJKEqKyB9ilGUqRV2gMp5WCX+Pskg=,tag:bcmVVNLONG81LKd8NjNTnQ==,type:str]
    #ENC[AES256_GCM,data:qs4wzIWyDUXp3+9ABnZ3GdA/O0KVRORzSOBz5aY2lMiZgQ==,iv:qNxVyPP742tiNKDI3nBz+ssSNvsUoeoZcoUayDGlrVY=,tag:qYUaOoyxGRdYm0xqdG6QEw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:51CH0+wsWsWEwCJX,iv:suNwSfLZA0uh/pfOmk7fK/CYC3R8R556MXO1KopENFY=,tag:YGBApI56bhBsl8k/sC1jJw==,type:str]
    #ENC[AES256_GCM,data:4dWmkiqNpf5B3Y3dCNrg3ejMg3ie90dI1D7oXptxYR2+ouYVQK/CtOnDzbBd0v4=,iv:dPnD6799DqDZi6DVAJyhRSyObhAVtUH/SlurhNuhJ+M=,tag:7URQhCq39LdBuennqwEl+g==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:X19qb+9VTa7DG1LN5diZpajXS5mKVtPNtD2Ik4g=,iv:3AyGHdOlD1YFg943uIAcIqU5d9fbbleUxD6zMU1cdjc=,tag:bEQGUNAgIQBVkL5c97sM+A==,type:str]
    #ENC[AES256_GCM,data:0qnZNStNXmB1YYL7CzWv3DhB/tn2rvkaplyhiLRlb1uqzUV6NeLP40XaVODQZ81KilIy0cFMhavX9QvH4WEiLfesRvKA3YM8dx9iXVoilGw=,iv:iG9ZnaGNIESRVK4hQdBlWjBUOtLrLsQylIgt8xmJjzs=,tag:cbaT3eqCirlSPf9ooZKKUQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:NSA7aybldgAOCHjd9F0=,iv:q2KpTF4HkzTcVVUn+esj6gzb9SNnVWdvr5RgraF3EFY=,tag:bwqjQiQDQS0WZ/fj3znyWw==,type:str]
    #ENC[AES256_GCM,data:8UV9RSPQC5Z0Xnct+xZlQULooj1uuBIOsAstCoX7Q3+u+Oaft9tKJ4yKIIQqVe7Y8wV5+4/mspg=,iv:rB1m9blToXOGlcLqTVtH26FvqaXyfwNCP1ztLif4prY=,tag:uXHM12T3r0bsN4gj5jpDIw==,type:comment]
    #ENC[AES256_GCM,data:L0ABI2wf4MLLsq7CGRqw/T95d0OHphjTiA==,iv:S7Ws7Rg8CsmbkmlWFdCxHACww0wg55VgCDQyzrVfANk=,tag:r9tMBIUtU+7NjOxCQRlhEA==,type:comment]
    GITHUB_REPOSITORY: ""
    #ENC[AES256_GCM,data:HUW8HDcN5Td8BUb/qg==,iv:jgKKuajByqd2TSYec3tw1jg2/sXXsqjJK9JDVYLSSTA=,tag:RCKRb0jU4tf31vb8y7I3Rg==,type:comment]
    PODNET: ENC[AES256_GCM,data:3qeQwII6HhsuzCm0Eg==,iv:6ryIiZyvAIGlxQo7HmXwY/9CkKKLsRM83Mj9iHwVLh8=,tag:oMCoJf0zJNH7OmI4kwMqDg==,type:str]
    SVCNET: ENC[AES256_GCM,data:9jr72CESseh3EjA0cg==,iv:5a3cA03POCQWWUvwq3yq2CMh2jorEd0gKalh7C6mruo=,tag:8xBgIWqC1gFfVcs9sjpCXw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:ClC+eg==,iv:xrgvVtGW0GsKD8B67nvX/tU4HzTzL/yxBZ8HqGLbydw=,tag:gejsXdQLHF5+8WL7V+TDIA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQ0x2eEh2TkN5ZytxbXRQ
            SU13RmNYUVlmQm1STmFvcWpPNDVjZmVSbGhzCkpsdkozYmY4czJXV0tSMmx6c09O
            TnBKZlR4djUwbW5ERldTZk9NenVNRHMKLS0tIFN1YWd5SitBR2RkNEdIZlVRRTZV
            aEhZallXZ05GWmQvRitDbWtZWm5sVEkKrMnTGkfB+d8DO5V0emOlp8WVt0wuV+w9
            gPFKUFWasryhMniuOI1LR1FLXWP3tsKXgiy4griwOJGjkO8Vv+fvTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T16:29:11Z"
    mac: ENC[AES256_GCM,data:+wLvUx1MfEjW+ZSzV3M8pZRknzGAVr0DBhKyJWb5w5DCgMQS4iwLKVFxZmyjBF6FvcBxOyeBepoEgNSiFTY9+ap3/EyOjDHdST1aAfu8FwNMB8gVzE6OkPTYEttSDrP5s8Fn8/ztN3J/enYCot1xyt0kLeu8nr27jXjAOzkKL9w=,iv:T1trRc/O7nRFJCEihnWswxMuNmfDbD0SF3CuAI60Os0=,tag:iMueQWyER7enIHGuT5aKGw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
