apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:p02Kod/Am4wVsPQ93VIZP/j1lVDsbS1y0NUCv0BjTzeayP81pRhaljdjxMkqZJPBN3gtO7qVDNIcrvaiAe7b/mc=,iv:mWKevS1rYaMrLfhkZiFO5ck/KWb91VyAtE4JxtY36sY=,tag:VWjE76qsxS4Nbz0fhkXB7g==,type:comment]
    #ENC[AES256_GCM,data:mDX9gnQXAZyq2mR5scCKog46reIrWQIVySrLVQMpOiBpnGyz0dxFma2dhxY=,iv:4ph1h2fNoKyijy5RCgXlvbIF/u9UsvM0j4IALqGxGig=,tag:ZdELY+wDjpXIM3v2lAM67g==,type:comment]
    VIP: ENC[AES256_GCM,data:NDgLAI/kGOx4xNI=,iv:Y6F3IR/5c/t10RUsoo3iqTTzDeP5otAutYJGU/ovfsY=,tag:yU4JzCW5gGF3CEAwWn4tBQ==,type:str]
    #ENC[AES256_GCM,data:uzckwN+ErfbH+V6q/8vsqC8JiLmBSp5moxQ=,iv:8H3q/lKFo+g2vfBRmV+PUqg+RCIBwSeY7+LPW2mpCU8=,tag:glAVzf4QGdrhgnaAZukwtA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:hSsagIyjVskbvw4=,iv:zd8eVQ90qjAteNfzlFnIYNPanOCOENfX6Y+YxQ7XGEs=,tag:OVgOPz2c8PFHGyunJbSXKQ==,type:str]
    #ENC[AES256_GCM,data:/WQuexi8LL/HV5cWchLQUpQs4/2oW+y+8M1FIvpuEZHaMw==,iv:eYxHO5+ec63nHFGwdZfJ1rWqZAMFRbaw+bG8xuYLn4k=,tag:u25Ero0HXQciSWRKURWMcA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:5zRGWJ2/YrhngQ==,iv:h6GOMi4gYyNL9aGl/6jAIPkTKxGH8vaQl2YAtNnmQ/4=,tag:QFAuifxolg0B8AFCDEq6Vg==,type:str]
    #ENC[AES256_GCM,data:iKrXb5BGHqQjBnI6NQeNcWDAsZ+ClvDBzInKGOUD/a37UYovA2omK2YRx/tZTh4=,iv:pGxEQj6MvKcHVYvd8iO8A9V8dhw8RFjMGcf0/Glbd5k=,tag:g8UNj4lLj3Oes4HR+OHT3g==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:XAGM+HGf1fJbmGe6mJBMOHfLCNLqqtM=,iv:xYKXrN7KRBsphd7B9MzTCEkt8/JBXJaLLF9g84GvHvs=,tag:ETldQV5IfnXIZ2jFsjn/Cw==,type:str]
    #ENC[AES256_GCM,data:MmG1JpNCjUaa0D7hmomkZhkry70li3+M5Rjjm+8MHL/fempguk2OpstY7VHi102iP6x/3eIvenfMDkKWHAIG4yLq797e6ymW7ncssPTTT5E=,iv:pwMoRNFdhIamR5UqkomA/OSfF/PLiDiQq8YxidiUIy0=,tag:pmUZHhnWyXp6MCysRZyIGg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:pjyo6TGCNEt6ioY=,iv:2uF9bj2o3XhEBi37Vq2Xfk6nuBabmjd9DGXYy3KFH3M=,tag:wQqTx7CHRR0koRDeSzFySg==,type:str]
    #ENC[AES256_GCM,data:O404fH/YqwaZUsiI318jgd9QSQHkQDWwy1NCcTTzDm+hq/5S5OY59nfKyX2Pnfgs39uDbnkgykk=,iv:aBIXk/FQ2CPkzZf11Vq64bujouoGVWJBIDRnEfWf7Lw=,tag:JWPRP9XnA9BFYI6CqClCiw==,type:comment]
    #ENC[AES256_GCM,data:9f1dFPw8ZAcl2KlbimDDRETHq7mofoJMyw==,iv:a6wg7Q4F6HwkaM3Bjdf7BTTW6WUMP0p6MJmKOudf0SY=,tag:IyPCdVs7sF8RnIVpIjYNLg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:GW7uZOwkyG7EJhuARJ2hUBU2RalueGGJ7tdYijMc7tAqd8976m4dQ18BhFNzJGk=,iv:P6LTutPyBd2a79IbBcGL9IO7f1UvyF1YuygwVuTkn/I=,tag:yBIImbIbdH9K9732t3ApcQ==,type:str]
    #ENC[AES256_GCM,data:lpexbGHtxv8XFaue0Q==,iv:QSS1CSP0G9Jz6mtBIJnNrPCq3UcwcuAk8oIiSNLBSVE=,tag:gIeC9dqZyNT27BBjlDdW6w==,type:comment]
    PODNET: ENC[AES256_GCM,data:ZbcwrHpEUttPOcySmQ==,iv:90JA9hmzrV7AYPLpypbDUwafU498g9lp0c7raBzGdbk=,tag:3bqQNb0iVdYvq4+x8MI5mw==,type:str]
    SVCNET: ENC[AES256_GCM,data:wzetFYzzUxvIpECczw==,iv:9BQkezFgKCpOTJVbBUHf7l/zAci+EhHss44Eh6ZBG3o=,tag:io6QA9w8q8to7akrW1jeYA==,type:str]
    #ENC[AES256_GCM,data:Uh6q4Q==,iv:YqqcPtOWvFV5IKRwylbz2IB59s4xKdA17z8togKZJOw=,tag:FwxWu78/YbxhcGbZR2Luww==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:Ptiu2SPqSMRszjE=,iv:weab6fclS5BNk/TRe6N8Tp6/mgJJ3XeR/O18brud7Ww=,tag:LB2xSPLoycrRNBTv5mY3OQ==,type:str]
    HOMEPAGE_IP: ENC[AES256_GCM,data:YuDOAQWNYW3NEw0=,iv:QEXNssg4SewHcyazZ8IWBlkycyU/syLasn+++dtLgos=,tag:bYWVm4bwyDPWqesqoN9Z0w==,type:str]
    HASS_IP: ENC[AES256_GCM,data:izyzlvF2i9cRHW8=,iv:JPUJE9BghBXTj/OLIG1ZHlTLExnov+iQ99XywAXPnUI=,tag:0CiQHqGlnqXOywr2ARLxOg==,type:str]
    JELLYFIN_IP: ENC[AES256_GCM,data:Lm4ExRfRffihgeM=,iv:9ebAG/fV3vszmD7tpwwhfu3KV3WZQWSDj2yxhpn6hwc=,tag:P4IxPiGtsGmYfT68oKqKpQ==,type:str]
    NEXTCLOUD_IP: ENC[AES256_GCM,data:juP1JT915zagX9I=,iv:fx6tzZoVZ5y+6kp/z+BqiV0p+rNAgx1IQUYiC7Q5JzI=,tag:0rk0SlB5NSRCBLQ/KRwKdA==,type:str]
    MINECRAFT_IP: ENC[AES256_GCM,data:qYFO6sXCS3JU5uM=,iv:9m7qcnIoF7pEq32NnC9ge0DkOUR4tYBbZJXfksvWFec=,tag:xG4nzcJskrMCNCum4Yd7/A==,type:str]
    SPEEDTEST_IP: ENC[AES256_GCM,data:S00dsTdfRXk9VM8=,iv:mvbX4k0c0ggS1n9nGUhoFStIs3kqe9UwknVxm435XvY=,tag:+uXQuFirUPQ7zn3uDcU3zg==,type:str]
    DNS_IP: ENC[AES256_GCM,data:6KkQ7pt5Kj/LGVo=,iv:Usng/JqgEeFpPe+jXeiUE3V/V8Yd8tJKNt8qyrfXKTk=,tag:YURjCqp3cKWzlD5kEnGTpQ==,type:str]
    HANDBRAKE_IP: ENC[AES256_GCM,data:dUDE6F5qxmwiaVY=,iv:6eRMXH5q4qIYDHeZDK1auLnVJ3k3QQvXoX0TyNp7lyE=,tag:5jpXT6P7vJMtcvNzEhzpGQ==,type:str]
    #ENC[AES256_GCM,data:5BlwLc/Kxw==,iv:7dLmpgpQU3zc/4+pQA10Yuux++J5Nk/n7fV7SFpTV2s=,tag:bNsDbWuFWr0jbfUW0QN6cw==,type:comment]
    EMAIL1: ENC[AES256_GCM,data:sAlHSgnje+ok5igkKoDUoA==,iv:PO+l6f/FFse0XQzFhQBywJJPvvZPMEw9r4gFxuchTT0=,tag:foNu/kd7tJXdWtYVDIBqUA==,type:str]
    #ENC[AES256_GCM,data:A2TVMao=,iv:iOWg1rL4TPvRqbjVYo8xDKZlQLoqbN+r+xCjKJUPjCk=,tag:3StixJXKQm5fGXBKhkgapA==,type:comment]
    B2_BUCKET: ENC[AES256_GCM,data:/4TtYq34vRlM,iv:cgZnlQucCNe1id0A/3mLhNqAYUvtc01i1TfnOGbwfUc=,tag:wEGcLHgSDDJjt8jQFZthlQ==,type:str]
    B2_ACCESSKEY: ENC[AES256_GCM,data:/qFVVZugG6Pfc+cdvDNcLfwY7KZ/gQF5wg==,iv:SGs4aZvR/g2sH1RqS6xBkXZEbUD0wU3xoiFi2FjfzHY=,tag:i7faEv+Mu0NVU/JXLpzrBg==,type:str]
    B2_ENCRKEY: ENC[AES256_GCM,data:H5QVP4BOglr1YJgYOIFuTTG41EN8OuDsPSm5jmwDr+o=,iv:kppXVIxikj9B7o8NfuzST/Er8EgmOmb7MSzc/7JF3G8=,tag:WC0L/ZIuSefuk61tBTEHFA==,type:str]
    B2_SECRETKEY: ENC[AES256_GCM,data:31nhSXu21JIuKafjnakMRtqTSBydXuMc7h7SkC18aw==,iv:KKhqIS5rHIBPDtKLlLFsNJ5uLxCpw+6LoOnbqgiBqPU=,tag:pXty5OeJTcaJgmuMt5TnNg==,type:str]
    B2_URL: ENC[AES256_GCM,data:CUJQxjkrjJ0wWM618xBPHm0vNt0TKU5hmy9/WbQ6MzDgwFEylww=,iv:zVvjDdNibjqUJ6ciljPJzdGuxs/1o8BCBuETnIkWKrs=,tag:K3FxmYB5/KP5GCzba3KRbw==,type:str]
    COLLABORA_ADMIN_PASS: ENC[AES256_GCM,data:/mxufSZ9BJ9F+IEH,iv:2zUQaUEpix/9RmIe4XsJNlCiIMfQSpcT2y4y0xFyeJ4=,tag:Rj6qbbyPpk8760KTCny+sg==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:zpB2UEyzPr9d6z1sSnE8PPZFfm7+LW4yI6JWCwUzoIbdRGvE6F3cAw==,iv:4AmyUgZvUG1wM/M40umaY832uILHvlg5Be/YDOUuUe0=,tag:6UF4qhb9MvZ1VAZ1aNlv/A==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:l7ilog==,iv:zg/pjXxIoKhyquiLHJa5o8A7YXmwmXTOQCQ3HqH5KjI=,tag:vebQqSMjA9J2KlkAXDR4Dw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTjc5UG80emttOXlHcVVw
            cXc5SDFLdDJwcENGU0tTZWVnWjNLZUdXeW5NCkJKejRpN1hpd2tQOWxjb1c3ODBY
            a2U3aVMraGhYYjlFOHRISlpLVzdtSmMKLS0tIFZsU2N5ekFVRzM3NkdYSlE5Q2hQ
            MUNWN1MrUjZZNHhJNGZMZE45WHMrbWcKCqyQLKfeuPxtZ75k4XSaFD7k6mjkUujd
            akZYyIt1hhoKg2LNQbxm52PsxNdcSDu1BA5800FUGuFsRdr4reBv6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T10:08:55Z"
    mac: ENC[AES256_GCM,data:wuJN0QGhQu/qYRVkxg8vPAeYNe4uXDjbs1dQgwm0A6aXzZq6JOcN91ZonBjOs8hy2RJw51vu1rYGeJPzQZW9eiFHg39FGTFL5TKtar9UK1b1YiY0/zmiIY9nalOl3VXYpF8VVzeQRYUS0pk0lu0L++7Xp5oyWJuUywbiXrMIJPA=,iv:+PjaQeH+cXXDIdcoEo/dPVmbCiXFYVZaqG9A0g69Lnw=,tag:w20Rquvg1zuFrq0cEVuJQw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
