apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:MidrB4xh7X6hAskjfES0/0pQY79JT1rYuENor85a3w2TOyNK30KiakkdN2U1m0dRbOX6IdkKjA4Haq8mjMRiHLY=,iv:pTEiiov5lw/goCvlBYRkiU/Y8GDZhbQlFvyLOYRfT/I=,tag:VogzsXMmpy2p0CAmIGwTyw==,type:comment]
    #ENC[AES256_GCM,data:fCmZCtQnD0OUAI31UM+1QVeJv6ttJdot5jqG5T8W41xD9NEQRliwo5sdUsk=,iv:EwQiSc+cuIWY09PEKsij8taL8Hv1qum+CUqoZjftYVc=,tag:oPiKnjYjXdd8i/tz6FtcFw==,type:comment]
    VIP: ENC[AES256_GCM,data:Gckhr7dnGHEbWp8=,iv:wuo80lPvVWJgl+VMMau4wNliME3C0L5zpUYSjV1Bg/o=,tag:jBDaiDMuTIc9JnMdixeTPQ==,type:str]
    #ENC[AES256_GCM,data:oKlvZX233eR3ROCP3aw4s6xdnrUTr2CLk5M=,iv:uYHXDcOUUnX/PfU8Z0FnpGjgDj6Fyhosdq4TdXxeGsA=,tag:bE8K50KuuW9wguaJYcLoqA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:ZNSYcTYymPTRjs0=,iv:a9nt7OsCrLddVYPlfc4slMOOEJJFKMqc3GyUUa2ZpHs=,tag:jS/NJD1m4gqTrxmQ5kzlrA==,type:str]
    #ENC[AES256_GCM,data:C/+hwwX34D6CGCqOY4k+3+OriQIgNActQVFwoz7cNx9dhA==,iv:AXNQ+FegOMz+AoRvX/dA7/uaaeFaBRiNdO/Ap6vVQXY=,tag:bMvHin8MFYbc2JJOiFYOCA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:JTs4hV95R8JOQg==,iv:Tme8I6t7o72lEYIsBF1kMM1UNrXTe4Ry/eWAoy8/MMw=,tag:NKuxIePawR4uxU1diwJwSw==,type:str]
    #ENC[AES256_GCM,data:vTl8ngvKN4LG9mBRGO79Zm+thaeYyUS0M7NVYnAydKsf0Rt//XcIHnzgYubLi/Q=,iv:4yHD6GMH6NmCVqjPGgT2/A4IbDqvl/J2d+gMPuXby20=,tag:AdX0gW396hd+mwra/Jszcg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:XU4mSHNGnAOZGGjfpQxldwaroxZoUbg=,iv:s9Tbw78uoeR+NqPZYgQtAGvZn0EZSbXhR7cc5+EZ4vY=,tag:Z0jta+pyCaUSDvmjnAjhVg==,type:str]
    #ENC[AES256_GCM,data:TeWGnzTvc3J/TWlIC5y1HDBKc/ZZOiasAq4E+zldhpFJfEpJwaLmK0pqWQFWtJILeXlqQtfMwNDXzGRFb5JAXXIVKrHz0a5xZelJUkO42l4=,iv:WCiYpUwIPSuEWFsrX6bjQ5bVg24yzPQnF0suPuTFtrA=,tag:LaE5Wty9t8SJdxLoEzjxuw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:sF0G8N6JxHjYZ18=,iv:gM71JYHR/9/ZGP5p09XvnYV2VNjJIEvD4gv/DYoA518=,tag:JrUFDBLpz4Jd55U40RViWg==,type:str]
    #ENC[AES256_GCM,data:zzdRvweGz3iR5sqDD5FKDh+zTx4bJZqbbxVXuSyw4ki7g+dT2LIjJG0Y4eTPWhKDmsWmYKezvQs=,iv:w2keqqwDd/rxJtZpf2WgbC+aHXlEPCP0jdJKeH/IQR0=,tag:XISwij6aJAJyob8MAmpN1Q==,type:comment]
    #ENC[AES256_GCM,data:bsCKuuepgwit60orBvEB987f7AW8kGjpYw==,iv:KnpQYai7DLO1ONLoM/6ee5s9C7PhN1ARWmhcxbFGpyM=,tag:iDGqIKurWkKgpbeHiLq0Sg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:Fcu/kchnj1w3VB46bH4/qshvyqr6VFE7xIuXijMRAXKS3RK0MWZKHMChzyNDXkg=,iv:dVvcNgX8XdxjKP+1jV6XJNh6zqSbkyjclqfdgs8rSR8=,tag:7wC7mK1NTcTomnXP23OIIA==,type:str]
    #ENC[AES256_GCM,data:7Fnho8yOZXpY8d80rA==,iv:KbogvdUfWg0/tBaKarMs6OQ7wNboxrqoUk4+WB1PHpo=,tag:zQMNlYZID/X6T/9cy6t6lw==,type:comment]
    PODNET: ENC[AES256_GCM,data:wU5QZpfjgE24SnQtIg==,iv:LujdH203SGyFmt8QzblOSn62cy10ZIFExpmkdJW3o7s=,tag:rK3RFvfg1v31TeFoJdJxTg==,type:str]
    SVCNET: ENC[AES256_GCM,data:SM39c14jzAf7Hb914w==,iv:PK6jz9v84EJRdxPOQYhe7vk135VfYWDly9UG2Z2SHbU=,tag:1By48sx/FFqxljtF+8WW6w==,type:str]
    #ENC[AES256_GCM,data:Bn2Tvg==,iv:YfXySS6CrGCDUK2uDoR5P7Jn5N96wi1PWfYL/4qFv8g=,tag:P93o5GQApj8BEZSzzwfVvA==,type:comment]
    SPEEDTEST_IP: ENC[AES256_GCM,data:0t5efcd+t95Xsrc=,iv:yku595Mabg1nileo46sZKemWKIVV5c6iWusYL9QevT0=,tag:01a16+Yxfe7ah3xHgXpOTQ==,type:str]
    HOMEPAGE_IP: ENC[AES256_GCM,data:hm39MZIAsL3EZy8=,iv:V0uLML+AsO/O3hQMK6lUce+A6mlN4ITIKr/S5JBiHfE=,tag:hsSYrwcYcJ7xkXJU5FAwDw==,type:str]
    HASS_IP: ENC[AES256_GCM,data:mbvmVSFGyEKB6G8=,iv:9Euqr58GWVEmsN7uWL1OpMdewOdSjUlpRNJy1Praax0=,tag:1uEcFrPKM5tyf7SJz9DHow==,type:str]
    JELLYFIN_IP: ENC[AES256_GCM,data:aX/EF4jwi/kLtLQ=,iv:WtkLbnrN1M1YnXuooiNR1i2BRxNFaUlrSx5Ie3Qs3HI=,tag:muQZC32F7MHxec3SV9zuqA==,type:str]
    NEXTCLOUD_IP: ENC[AES256_GCM,data:VNXLxZLEKQYc1Gw=,iv:hHAh7p8Pvu6odi2UTIH5vNTA910pT9MUZwBzHisMubg=,tag:z3RfnNlUNSu7TmARlJwSlA==,type:str]
    MINECRAFT_IP: ENC[AES256_GCM,data:gr9zqupzj4zXyCw=,iv:trYho026m1KhrFoQcA+IAQI5RBHEBPIESrBef+HBFAo=,tag:5CrtZEsMKh01i90hHQ9uPg==,type:str]
    HANDBRAKE_IP: ENC[AES256_GCM,data:wt0KtBujo4Xieno=,iv:FX0yro3Xu+/FMF+50kfbt91C6CRf0OG6UTwjYkcSj4A=,tag:pyGmHR5DnD5okmx/zv+7oA==,type:str]
    DNS_IP: ENC[AES256_GCM,data:P8xaEbjMjxfj5yo=,iv:bdvN+ztmpBOyTVw2szZ3TLQC5sPqAkeF9uSgtn3oZaU=,tag:BtRwxHnkPQvBOWntofk93w==,type:str]
    MAKEMKV_IP: ENC[AES256_GCM,data:ajJhT3IfPM8B7wg=,iv:xceWVEGuH2mEBK9HYexKnO0fC3PSZZr8AuRoCT1i4lo=,tag:kmHCE3qagb8xCvjqfj3hmQ==,type:str]
    PAPERLESS_IP: ENC[AES256_GCM,data:M95tnr/FgGLcg3Q=,iv:uTNbVMxphABKCsgj0zcow/MPM2Xlap5zlPbz6Z5BJos=,tag:MjE6uknc76cMP8d6sOLaFA==,type:str]
    COLLABORA_IP: ENC[AES256_GCM,data:Owdg6L7WocHdODA=,iv:tdOvjdr2M+VPPnjwu1FsyDNj/1PkGNfpGEeRd6q6pig=,tag:q7ZGGYqRoVP8qFGPbaPoyQ==,type:str]
    AUDIOBOOKSHELF_IP: ENC[AES256_GCM,data:3QvA8QC4RBgZdj8=,iv:YY/w9+/GvROLZ1ch9did/iJOs/ZlOdn35mFAgXJdvJo=,tag:TMgjmgYXM1gXS7gVsPT20g==,type:str]
    UPTIMEKUMA_IP: ENC[AES256_GCM,data:/zF4g4SEiRwcoF4=,iv:DvfrhyPaws747QgYxFdWaIWOpTK3MVsNnT30hI1bi1k=,tag:DajyJYqyAJ03YpA/nTIocw==,type:str]
    PEANUTUPSTAIRS_IP: ENC[AES256_GCM,data:FmAGwKCLnAWCheQ=,iv:KQg8VmFY0UhUx0pki3A+hGj2wASDQQViQUxC2v8U5+Y=,tag:MIsAwJs2+WZ7G1603h258w==,type:str]
    PEANUTDOWNSTAIRS_IP: ENC[AES256_GCM,data:U0pUjwDmzkxgUuw=,iv:p7RyFKREG7TtodI6UPp9sDdI+Cpc4jeQOv8Usj/REhU=,tag:9XJnH00AvULEYqsT6Dr/rQ==,type:str]
    NTFY_IP: ENC[AES256_GCM,data:snK9NX+rK/jfcB0=,iv:JMeq90867XbyrQ1Q+ptjjpLurgQb2Czos7/FgykQOV8=,tag:DRJYQpXWuHHOtWxymJ9QcQ==,type:str]
    #ENC[AES256_GCM,data:9oQm+KBfNw==,iv:Olnad699CJUd+3oi0diky7H35nv6LUGUKCKEk6MCcXQ=,tag:OeVA3Td2EsbIrUjMQf3wcw==,type:comment]
    EMAIL1: ENC[AES256_GCM,data:nE+taXAADOUj+bOSStaEWw==,iv:FO+i7CuHIV+4/aXfJOkKRWGIpjVjkbgOv3z2BnRIgsw=,tag:0YzdTqplElbUGik2eFgVlA==,type:str]
    #ENC[AES256_GCM,data:nB0mGAU=,iv:upjZWbDlhX428fXkeyku7CaEw/yf8wVMOClKMpRS17s=,tag:swZVja4dho9djnlUIUVJQQ==,type:comment]
    B2_BUCKET: ENC[AES256_GCM,data:gnQJAH1UXxU2,iv:7OZtQCEswexdoH6ixW1vfVEcWTvaedZ8W8pp27Lpujs=,tag:xosDZXwU5cHFRyNSo1abSw==,type:str]
    B2_ACCESSKEY: ENC[AES256_GCM,data:3qEzTx5IUafBpclcHn54Hya1WiyGiFh+nQ==,iv:dNJETKiHbhj9h0PZ/OVOAbEa3yPkxIydI7QR/m0WV4Y=,tag:PspNhhDUiQHkHFrAG5AwJQ==,type:str]
    B2_ENCRKEY: ENC[AES256_GCM,data:i3NfJ/AyRzH7Mzi4TqZQ67m7KGVxaClgXLj/Hoqwj0o=,iv:P0EiJBumBNj/vBsya5PlVSj+qGZ/N+x2TvD79zYZSdE=,tag:qsprObekg9BhlGv5IgDrMw==,type:str]
    B2_SECRETKEY: ENC[AES256_GCM,data:M3zcDwV291re+sNBuEPbBbtPrEpYpmQcTB/tCQVlIg==,iv:tCTdnu1ABaPDoyzKmcRGbrJqW/+KMSOd+rARStafnG8=,tag:GS/5IBoCzEL5HLvfRQHrmA==,type:str]
    B2_URL: ENC[AES256_GCM,data:iWGQX4BKqyZ3aGNlYHPxFeInvcJRF+pfSiyhkcL3wgj8UEXR4Gs=,iv:PD4e25OKC7W8imHmMUFAGGQwh0z3T0bEkIbRZK3FnFI=,tag:yhzziuj/uovbILdVMHf5xA==,type:str]
    COLLABORA_ADMIN_PASS: ENC[AES256_GCM,data:7g6FALsQkQYSCS5k,iv:YY1HbvI76Eg245zyQmyQaqMkYUXpcEYmuU7ExL+PJXg=,tag:/7xUIvcSu8XUCp/bMMxYsw==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:rxhaSXrpwExB47YFrkhr3AnoVWnYMkAZhI4fhl8NqMnJSmt4LaSTMQ==,iv:xxvCE1rO+ICHQnO8M5FvEN2AGLuy8GKntlg2wcigwno=,tag:/sxX8SwDT5aawg6jBUhh2w==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:lJGCLA==,iv:Ttu0ICmqxsmFqnMwKgka5CHbRkiUB1jlL2JUPxrssgw=,tag:vpj2YZBgVXISRNq8Bn8ZNQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbVRMZGJlRTlEVmlLUE1y
            WEJKd2NxdnFEaUIzUmt4YWJPSmhNSWdDcGljCkwzRUlhTDRvMzI5a2xsbWsyZ1ZP
            SmM1NXZnakl4b0ttYXJud1VuRFZINFkKLS0tIGlma09WT1BTZjNaSytiUUtGcEtk
            YlJITUV5TGpDZVVkdVY2czhEbUQwVmMKBmDOoDtJDSjGppW/ZKSDW0Yoand3wdat
            hmJ7w48TnyX6Zpv21ZePfd/zYRB687wuNI2YGZmk69vJFE2xZUxSyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T17:58:54Z"
    mac: ENC[AES256_GCM,data:3bJ1mKShXO0arQqUf1h40YdnQ0BRR8bVrU7qPRggMVJPzgQPxYGCBCqmXfjIlXRO+6ygQG+RouP5LYPD3Qbju49Et5xlkxRenuA9qzc/DSvzxyoGabKr08RpUvtW2ycqE+WXB9lVEUoPzFaIU3ooQqTvCi+Yn2QDPOvah2ze5AM=,iv:N82H643bxhrqN+J1igsQqMTDQAI0dPEF3rjSQ0S9TlA=,tag:LS+Am3jx/FnpHw3iKNdLAw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
