apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:8gJ+eokx+2+WotZ10ng6jcucsFoYGy/WOKeAoLrdLJJ0SuUpy010rccw9ZMVn4Pxt7cOHDPHl34BOVHeSNrwDUc=,iv:vhz8Yj52Osg5fatPBiys1L9GPNGZajtSzKFpW/eaIIY=,tag:GcsITcX/lk6OXMEXVksqJA==,type:comment]
    #ENC[AES256_GCM,data:RJOBNq5fDXPByFvseFflHTu8SmtyGIvTHroDhMEUwoD+q+02ZHNHZJNXnJM=,iv:CXt2bIMsMpe9aavpd8hZQjd4KByCIYKmQCKN57yRX1g=,tag:5h36zRiI1noJ/oU094uivw==,type:comment]
    VIP: ENC[AES256_GCM,data:kMqexMmDtc8DH7o=,iv:JqSOL9nhkJPvbnv+NjEQN8evqa5lKnNTebZzHPQjW+o=,tag:NhLu2AnY2EZYKZYw7VaMNw==,type:str]
    #ENC[AES256_GCM,data:Vnjji2WYqcxd+mVRDTFNx5DzFh0tHwGEwRA=,iv:8icLqpmprGODKozlo7JBikVlHDSoAhPZHasEmF2p4tQ=,tag:4ueSiMpepm12dfR64F6C4g==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:LtcxovA7WepqS4Y=,iv:Hlzq+I33/PI9g8NfYNBujvPvEKQmuDyaehDzGd7C0IA=,tag:pbXoshy9Mf6gk3TTEhVHTA==,type:str]
    #ENC[AES256_GCM,data:FL+YST5xrDDt7k1WgQzSjlr1xRV5SFXK1EGjeNN2uecFGA==,iv:cnl2T2LoZOvBajEcXs5rYI254Sewxfcr4sgDgBnDCdo=,tag:Aamyt+UeQpORUYVS3U2wsw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:qRoKZee0iwBy5Q==,iv:vdAc2yxIRJQOjo+de2heamZnNvMtOXlRW2Tv0VaAwG4=,tag:4HJxnwpSvGIGqJSTMbLMAA==,type:str]
    #ENC[AES256_GCM,data:45ys3G4vQXHTpd/99798PXqXwT4xppJtpE4D+lOUC2OpkerFJnTWcvaSQIfxd+Q=,iv:6f0Kc+ZyyOaGBoQaOonrocFGpOsvFogDoxgx0kDcLes=,tag:+Nt0XOpajJkU8m1qXhpLow==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:XhZnrkBbdiH30T7xMEP2x3Z1nqNwBrM=,iv:aWL2ecd4aYzhTDIHbRkRoLnypI2RFZLOXxQkW3yAqAM=,tag:23uTPqwDwRsG0uhh1+aJKw==,type:str]
    #ENC[AES256_GCM,data:YsAgjXlF4lbNtEpfDCjuyAJHmEl8TuNHmZCckRvY3g14bvsRlHV/kqY3HuxMV+viY5MGYJS4FqmhXgvkq2kIDrM0SrYq9IMZHjB4bP3d1YQ=,iv:xgNOE3knwI/JHiArAKwfjUk1+RkOyxzAm1tf1WVeo2o=,tag:CFZvBUwmjTB/hMH+jDe/0g==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:6mjh73ZiLk/jMkQ=,iv:h9T3ezzSz/4N4vLn7X820/D3UXGQZi9HldQMLK1XQLo=,tag:NqLrMnij+T4PrLpqljhT5g==,type:str]
    #ENC[AES256_GCM,data:KiYG9/x+Kh8aTUXMDS9IKCYs/wEYhvazP+bwuhdcxZ/vrg8ziDbQnx99FZtcyRO7eXW1feS7y2c=,iv:i4/2Zv4YimVsSjCB9USQCaPjgOlactIqpzCwD5QZ/U0=,tag:bDuQZ2EvD9J6XOh5iOrc4A==,type:comment]
    #ENC[AES256_GCM,data:WOGXreFHfx6L/F11DbznnpoTNZB8pdXuGQ==,iv:yMRu6ZnW6k3KhI2aeyZW2jwaeMEBZGMiNxRKU6uNyvM=,tag:ScKj3cb7xaO/4n3k/2srQA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:gPua7CeIqjaOo+0PPADSeDGKLDqr+5cvfMA24ECF/sy1bpnPjmW9fL729bhSKPY=,iv:noTwB7l2hpH9pMpuY6GivremiMn5qmBfozmzQM5tjwo=,tag:dgegwkX6mWEZYOna018MuA==,type:str]
    #ENC[AES256_GCM,data:GNqoPIoyh0Mdoylm3g==,iv:biEYjNAufLPPPHgH6+WYhPNy+xi1v3PUBfodxWI5Voo=,tag:qY+HsH20Hz95nXSPfrOh8A==,type:comment]
    PODNET: ENC[AES256_GCM,data:w4RznyQ8NUitKx9WXg==,iv:AVImVKLIrH80m/3/Z02evlSyvpX2bpfCrhpSxyS5jHw=,tag:toykITHMD+eydMeuWEdTbA==,type:str]
    SVCNET: ENC[AES256_GCM,data:29gaGQGVwnvMNd7BLA==,iv:7+wJW21clUg9TLLyEO75d1KUwHlUfTquDaS/aDMqurY=,tag:Fo005K2F4Mj3BsmeRIax5Q==,type:str]
    FIREFOX_IP: ENC[AES256_GCM,data:UnUXrlHPZHuWWUc=,iv:uGADo8IZnQZcFaSW41QrnKs8ZfkgkpUK2zvXwtwzxd0=,tag:OufIKnwRieMDzdgpkgnivg==,type:str]
    SPEEDTEST_IP: ENC[AES256_GCM,data:5E+jnb/YXqPe/XQ=,iv:fVXAuzylUncjTfcPhuD3mx3wmrOeyrv6lXQamVhqh08=,tag:Rv4VgE/G3UfPvdnZTZTDZg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:k8i4LQ==,iv:XCghsL6PyetdhOB2Etv/4buKau1z00Mmi5iT5UQ1ouQ=,tag:Q7O4AMK8336eM5kPGZ/VdQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFc1V1VkxZUTNXTUhEMTdn
            MW56dE1YTDZ1bzJ5NUhEdGhZWHBRcWJHQTFnCktKeUhPTVRyMXhZV0JlWVlYMmM2
            NVNsOHpqY3ZObWQ0bXVQQ245bm1pMlkKLS0tIDJBZmRQYWxrOXhhZ2dybnk4akp3
            TXVKNG9WQTFrK3A3OUhZM2FsTnl2c0UKouquy9nT2oMEptM767TqIITNo2l8rBlo
            1ntbZLzE3gAwyhrB3wBZtzc2D+rSCctSdoPAtrhmZ28jy9RC2hrKNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T07:26:06Z"
    mac: ENC[AES256_GCM,data:eq12rGcD7UQJN88GGfxaSYJl9poj6jPFVAZ7lDcYIHlwgJT2lN4fwgeBFEoSXImWY/J1IO9EPtZ9HTTCRrWA1z8bmkJRWPR+WVo4MQ0ocIscKEO87xkO+z5z3SKGfkAYLGQ0nTg3T2MiLRr9wMpYoqaHznxke99Bf1aXqBymBAk=,iv:fJDDJhZ3SYgzfzR1VlLm/OyUixFqMshgpmaqMIXizBI=,tag:yJqQ6RUazv8hcHrqbT5kwA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
