apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:ueproLvJ9wZRlB7JPs6DRUfDMHsFWaozPePzmco7EQVO0c84HQ4TsmvJpKQKsi3WN6i3v5kW+Zq9FZBTVbDhxA4=,iv:hAChupw+Eohc7zfGyQ3umxYYgxG+yaAswlcjvAgyl7c=,tag:mb9eOjPGdkdOPKsbQQy8PQ==,type:comment]
    #ENC[AES256_GCM,data:ckBSb2HxKiH3VZlfWr1gG0nbwnmBX5esHYWYX9zx4TsRNnWNS5uSnTdubJQ=,iv:pm26BnrK9m7BCgLZ1jRanVmXastZxE9WLZbuEbXR0nA=,tag:97HVoGsr/VzRjwsmCFWwaQ==,type:comment]
    VIP: ENC[AES256_GCM,data:WFosYrOEbHaUkC4=,iv:KtmBjidO1Ow25CqQm8LLyVdB9nzAMpwhiU15mWihCO4=,tag:IHxxBKflq/cbJ72tsAf0pA==,type:str]
    #ENC[AES256_GCM,data:1+WyI2ccMQTtZKwuyv81FruXEp2Jk+8avMs=,iv:fWVth9vXma1BV4joh9EpMRcU5B0+u5tMZSmfm5MqMlw=,tag:AtWM+ppa5eLh0Q5M0VUD5w==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:6JaFo92HnCJTz6Q=,iv:est47C4Cc76IZeq9nIALr6wpwplk9mphgSzevcS+4wM=,tag:iTfA/SB8YQsuvFYTOhkViw==,type:str]
    #ENC[AES256_GCM,data:A1Sk2/w1A9MpIw5m0RqR3demlGo9yTzDYzhLLvfybUSSWg==,iv:MiunYtW/8opayWE53C8zLEmyislS8v1y8Kb+yfTamuA=,tag:D+BJfM50tTVKBAfUiUFV7A==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:5T88RX2Ky6y2KQ==,iv:Euatxaityy/4nZxCje4KsGB1o0HlFlezOXsSfS5ZGzA=,tag:+1Zd9Zt5RAzkw38P0el9qQ==,type:str]
    #ENC[AES256_GCM,data:BBTz0NFFNzxRFfZ2HOW7F12Ns8TL1fPG3bk8SNPkcSuz4Z7cBHDYnbIWhEBvQkY=,iv:D3zfBUbXUsE3HClfqtcd/48Xwr9SatOGNMjXB6blisg=,tag:9Wf2uVVI1IWIhj5Jz3n6Ug==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:mz1AcdHDmX/9kZZS/iPp8wD48rzCJyw=,iv:mzybbfg1zWBY8jMnsDgx3o00qa0Oy85YlmxR/xvnEA0=,tag:VzkRssJ0iTgGH1JIN1QUEw==,type:str]
    #ENC[AES256_GCM,data:lzu2+vVE52FvhfV4xpm021hflXsejACHxFje+H/V6Yx3oPAZfdP6SY03gP+CH5zMH0Bhra1862x9yTJsnBqqRJ8l8a7SXxiAnxoiYsqnO+g=,iv:V76fGGlZRbybF/A9MbWBhmlZDU5JbF2FK4Om4Kql060=,tag:3WEDm5muOmnOXkhrDg/mOw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:+KUhSK73JWoSg5M=,iv:G3wwHvCZUUNvjAMQRfyVKKFmpZrydumz1yaey06aDI0=,tag:+M7Nox3FnVQufA76pi+OUg==,type:str]
    #ENC[AES256_GCM,data:SJlVr4A4MAM7vj8D7WAfUjB8s8SV9jWuh/3enGIfhwIDDcQrlHbRfYIayMNAoit1ZiuDZH3vuEs=,iv:/iQdk/lMBMGAqZkdUIYAQZSMK0aPVybBD6UPXXxgvqw=,tag:aPhAHdRRUwq9lz+oLKPa+g==,type:comment]
    #ENC[AES256_GCM,data:rH/5PirrBPWihq1sYaDvjBFNoGIpNqNF1Q==,iv:AhMz5EmyP+bqifdz2k+hySwLvGPPqzwrUYia68mo3SM=,tag:8h+B390pkTLhL2FwIR8OPw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:5XdCCM/tHwSZ7tBE6woo5jCZsDqtbLNqV44fVvoXsN2PyH6+MFxQRsNWWIMvGrE=,iv:ofRWPKbe1XabhpjauNDD5S+273ubF9yGT8lRffiltoQ=,tag:o0k+TCfVzhsMPiDqA4Pn1Q==,type:str]
    #ENC[AES256_GCM,data:kk3aEufIJuVmM66cQw==,iv:ZkKezfFSJkoyaKJjFTxlLxEDEvAEIdi8e/uLaOVCMi8=,tag:ZXh/RKoP8PCKy9OWNXgWlg==,type:comment]
    PODNET: ENC[AES256_GCM,data:6jgfapVvB5hNWoJZQg==,iv:/YLMefPoDZCDZXN+mjEcjVnc4CUsNBEFq9r+y78Zhw4=,tag:Nl0svh/vZrGzmuJTVNoFzw==,type:str]
    SVCNET: ENC[AES256_GCM,data:+MT2HUILHCHG59M0og==,iv:oJrbpON7PF0WHYs5hcq3lKJwaQh9oc71lEM6yM5JWKM=,tag:wAGTugPitA3Cai+u1cN2Kw==,type:str]
    #ENC[AES256_GCM,data:6SQeLg==,iv:ixX4vcjszotfjT5JX0BJQuMLkcDaSmBdr3rqRkqUukk=,tag:jz7f27iUfd0aRIFHopHtew==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:Y8oelfIaOtG0270=,iv:gUVOCnFczbkxTLLAh2vbC2Kizg8KtgT5fsXC6ebgSrs=,tag:RLYXZ2lYRjopf+5QtamlUA==,type:str]
    HOMEPAGE_IP: ENC[AES256_GCM,data:fq45PZZgyIXoaEQ=,iv:35zVaij0vNUeOZGV4VU2mz5tuw8mzBOtfArgu/a3s6g=,tag:jc3bbd1m/+MHFAIM6hVTvw==,type:str]
    HASS_IP: ENC[AES256_GCM,data:iooyLgji/MOLDys=,iv:t+FQgxUX+5Aabwndh25WX+s5p7DqLLM8hZXlk3plPQY=,tag:qZL8FmVv00PIpzl2m4vwrw==,type:str]
    JELLYFIN_IP: ENC[AES256_GCM,data:/NHAAY7Nf3A75qk=,iv:jYaqNIl5Dq9ZxIvCtm/fiAIqc6LP0ZOaJcR92fa0Mlc=,tag:+O9Lc2U1T2A7c9yoPLdS3w==,type:str]
    NEXTCLOUD_IP: ENC[AES256_GCM,data:zS0ZjCtCNdBJewY=,iv:DjfMg4dfI+1+Y380Ve4b/WfMPGCvapciaSWlg5q7rXE=,tag:Bcb3UeBYvdpyhQr4KW8+5A==,type:str]
    MINECRAFT_IP: ENC[AES256_GCM,data:lPb6iYABQ1uaOgI=,iv:+zxbuRA3oZaAub02OnKjoR+ySmKiNiSuMa7PLxp6gmU=,tag:o9h8rSUkGwfwZlF9QoWLuw==,type:str]
    SPEEDTEST_IP: ENC[AES256_GCM,data:/f9DNWrWK+1PGSs=,iv:O171BXShM/doYUAj4r0lmLudKMPQc1vL8QfOGZB2tF0=,tag:TBVMLR7v1x0GNhd8nTLLQg==,type:str]
    DNS_IP: ENC[AES256_GCM,data:HMJuNZQ2AqApP4c=,iv:DyPlpug2a2ghe1AZATbPiFP83JxxqyIiApsj73owolA=,tag:eg8oNC4WfIRe0HQ8S2BhGw==,type:str]
    HANDBRAKE_IP: ENC[AES256_GCM,data:d1y+bh7X2/2nJ3I=,iv:TxLLbNCEsnhB/GFxZC+p01Bi6BXy0pdI5Iz+pKwpn5E=,tag:FxD9dJ0yAxxRxFCeStpl3w==,type:str]
    #ENC[AES256_GCM,data:dx4/z4IF3A==,iv:FglYGJRudTwYTTPdJl2WgujNwxBewU+0ReIvVFMF58w=,tag:8AxKjKp838uMUAM4DHDf+w==,type:comment]
    EMAIL1: ENC[AES256_GCM,data:l78ZUj1qY1GU0DH0bnZ4/g==,iv:5rZZdwqB/MqjecuiAlfoO0E3EOGxIFXEbdwigo54nFw=,tag:mZLiA48QuxpHDEqSv2DYRw==,type:str]
    #ENC[AES256_GCM,data:w3LeWy4=,iv:oRGJHPEOjL74/+5yHCIj0u9fftJ8kKlR8gdt7VjgXm4=,tag:LFzsEXjYgBLAbsMGfaUF7Q==,type:comment]
    B2_BUCKET: ENC[AES256_GCM,data:vAcw3PARCKLl,iv:H7T7LOhnumtRaZ9K7MqNhIuDKlFUKitBGJzQoB4/41U=,tag:ZytOPJkHpcCUeTe/56hExQ==,type:str]
    B2_ACCESSKEY: ENC[AES256_GCM,data:xEEgg6HMk2xCCoG1HGI2ce6nBW50f3jJVg==,iv:Xa4KBtdMglRXflRN4Fzjq13jIrfXauRItUVkVLfF3ug=,tag:ir4adXkJEmoS4TssD6kdQA==,type:str]
    B2_ENCRKEY: ENC[AES256_GCM,data:DhTrddQrlhsEkkqs7KMq8yc2YFAj7doAubQ8ov0mTT4=,iv:LGRgLCu0i+WLoaDE4swXnbOoHHT/6Jwzchn4tRZEAlQ=,tag:MwZc6Bex7njU7BV2kKBwWw==,type:str]
    B2_SECRETKEY: ENC[AES256_GCM,data:aAnHY6NAYtIta89emW+QvtEuCRFDqL0jMHvlo+t2VQ==,iv:Mb9KJ6PXIFnAyQAlFGOJUiqZRoA8PN9atBwEN6tTNhE=,tag:jo6lurNkahjOx4VW6kiITQ==,type:str]
    B2_URL: ENC[AES256_GCM,data:3jwNGzn2nyZHPCVhfy3sefx8OQWQbNsPXnvdEEUDqzRbKO1hYs8=,iv:1Wk5oCB2/cKy9pOTYHscBgPqr2bD6b0oCmo3km8QsII=,tag:srf10bUxIcaSio9p0+HqCQ==,type:str]
    COLLABORA_ADMIN_PASS: ENC[AES256_GCM,data:lnNvvQftxf5JiPuu,iv:YU6K5YjBBjCV6SKPrdN3bGOsrWrgH2dx32zZlsLhCAQ=,tag:DqqsPTvNvXzjvUsWXbaD5g==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:hZFoBoM2phXr/xhfvyzgkZjF/n2gSBqHrX5z/+DekqXUX/5IHPy6CQ==,iv:8EcbuWFOyLgwTCX5La/hSDZZ15Rs57IcpTZmQixXNtY=,tag:QU2rcUPVypy2fjA1PJa/+Q==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:Iekn0w==,iv:/c4fzNpq6ly5LhyoJyyql9xac8uBQonJM1gV0lbOnK4=,tag:+bup0qornugCLcwb5P68UA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZWRNMC9pLzI3ckR3ZGZR
            dzNYK2p0ellUT3hTNVZ4dUlQb0FhN2l5c3pZCnhqSXMzV05Ud3dURkE1Y1FQYmU3
            bkJ4Q1RmeFhtdlRRa1R0N3huMzVZU3cKLS0tIGV2ODRPQ0dLdkxjV0ZwWjdyWVhz
            RWl0cFE4QUFNWTRZbldqV1dycHZJc3cKAst5wslfVBBuFyp6SeJ0YHPvMjtqdkIc
            L8Y2rt/WxB8/SMkn/WDh+/E/Cz8C8mGLkRdUoU8kw9XA6k8usXf1gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T19:06:56Z"
    mac: ENC[AES256_GCM,data:didHHwrHaw5d6NxI5bcgL7uTZMnDt+V27qVNS9KZsRzxSCXcgHhpmKH2zs83g+Wx55HejfKbRAetSlCbE4bkhE/dkWP16oO9O58zfVD3PgTBcMxcc8b3NnBEO8P/cYQPW3asnxYTlWeDAaLW+RrWWm66srPkLDOY/bh53n/P08w=,iv:BsYeCP4vtmgJelcV+68yLptUuc5jzl8PhZMlR/FuAQU=,tag:5COzTLJigr/+E+ZYwSZ72A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
