apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:gLNHdKvtur3M7Sazto2Jwtmos60dAqJ7fCq2kYRd/7rCexgY1GZsBtVC1CPFbu8mM78kIPqLLV1DpxZ1BCtkZw4=,iv:9NggqSapYlq2Xsj6ZzW2eUHt2p7oTCNpFvTiozE1Vrk=,tag:hR4YEq3CKtzZssPzK2DAww==,type:comment]
    #ENC[AES256_GCM,data:PgSyQ1wMKakadFY5b/CWJpdURWui7npVLQ2HhX4ejg88CuFwCdtrdfFJrf4=,iv:tPZNNaBMpEOGuqhiWzuSS7L4DeRhYcyBYTTL2SQ3U+U=,tag:GVMxVP8J+ffWGtRk3t2KfA==,type:comment]
    VIP: ENC[AES256_GCM,data:k00+XQ3CFvebLh0=,iv:PJZb7yl7+Qgv+xFyT+OyWUGkn7V/CxI07uBg3EMNFx4=,tag:vztnLnhATx+krr9daYyAcg==,type:str]
    #ENC[AES256_GCM,data:wDidrhRnE/oSdUoy+CGxRIr1RbpXO2GFm7w=,iv:Mf53dLYyB3fK5SNYPXXenjY5j/eY/2fiXx0qUeKMgVE=,tag:/e6aCb/rgAIkjctKz63Y9A==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:Tb44pyHUW8MqAD8=,iv:qoEj2nyUuMfsNejW7EfAyJvkEXT0JGUynaX3I1RNtAk=,tag:6uCgY3J/n5RUxEs9ZvSKwQ==,type:str]
    #ENC[AES256_GCM,data:3j0Mo3rjZgjOy0lIBCUpGPy6Lmlyjt7vBd+oQUv7cN0RiA==,iv:cLWTXh2NFnGLYfH8L0tlhaBrcxlSJ3Mb1XIm2tmJycM=,tag:wNQdX1SeN7Vac0wfIGVo8A==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:OpEDhtcQ0EvPqg==,iv:ADJsYIQJiS7qC3uEJ798m0I8yzNsmpwLFf815HLUMrE=,tag:RlEV9O6d/qj31D7sua9Gug==,type:str]
    #ENC[AES256_GCM,data:k1nZi7UGiJg6FADCU0Mhq2FIf0SwSAo/wST6R6OB/xi0ztfKMjsq/97TeQC4MgU=,iv:FK/avWYB7lwLvxhDKG/0y4deQHqhj49Oo2cBWrU5fQQ=,tag:JPUweBi/XKGJHZS++MGElg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:oVHuV+Sq6cl5VLKMYfHQCX0csVisNZU=,iv:KVqErTGJw3fkMbecikkfW7PgGbox+GosbQN3QXviMAg=,tag:eBDELkiIB8QZZLNyqnpm8g==,type:str]
    #ENC[AES256_GCM,data:r3zRTnz5/Kv1qdVv7IO8ikzK6lGjgbhY5UNAISkMLJjxDFRWwg4+QVIAJyDxvWsLPMWoOCWqmdcr1TlPRUXYmm+ERs4WoR2gq+VF2+g89TM=,iv:Rt9FUpR22PymZu1FBvJmX8i0esZR5pyEBW8t2pzdAbA=,tag:RH9W/m6lni4gpgCs3+jJkw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:PD7nOiewipQSbkQ=,iv:evlnZIxJ4JZG5RbP80s2GYYXObJX7Bege656VmFnnGA=,tag:CUF3EGfyMtos3KP4efUB/A==,type:str]
    #ENC[AES256_GCM,data:99xdVf1saaJJpbmAP9celdEqlJ7cPLd1TiwDFC+jgGXm51UMW5pBTKo9ax8ZfP2hQl6KDrkX6pY=,iv:sXTneBlZSUeUADJSlEAsmKhfWdmZUb6gHsSce62itys=,tag:8L9jkZwhbnNJLBna99Gfow==,type:comment]
    #ENC[AES256_GCM,data:8p+8+nSGfYEU2DrUgiWDHSnddjYdR2DOWQ==,iv:Ei+eiR7UNSiCnklV/OrpE8wN572EYaRZ2R2LbIW7EuI=,tag:od1zbTWVlcJQdhpV6vFzOw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:78U2EUgt+uvWvWspIyU3x2+6vRXLu5J+KAMTr0qfj4bIwzyHtXt+Fk0BEeJa6Bk=,iv:C7OLEF6hnqH+KcoSB/WxA19c8MJUxo55ay5rH6F10CE=,tag:MXKvTzhfSU92qP0PdrM5Yg==,type:str]
    #ENC[AES256_GCM,data:I1QTra6dCp7BnJywzQ==,iv:QrB6xFd6yLx7d14MbSTYRMrRBUlcLIlOWc/DLGgfGMo=,tag:0e9bmnufoFfa72ncIBSQPw==,type:comment]
    PODNET: ENC[AES256_GCM,data:/33Fg9MNBKcW6dBnyA==,iv:nqvLahVDu4HYawkUArpKJO6C6y+Z7xAp81uPhDO3/90=,tag:UNB+7Nvky/EKvVb1y0U8qg==,type:str]
    SVCNET: ENC[AES256_GCM,data:h8Ixs1j/XgzVVn7v7g==,iv:4po9rwvet3Q2FShldDJrOJpBg2nM4fidfufZlWAzivg=,tag:QjXDJeM4MSAcNL69EILj3Q==,type:str]
    #ENC[AES256_GCM,data:4u1MWg==,iv:tNwPjvMqUxsA0ar3dsbZb152z+Ceh/tDTuh9HjrHc60=,tag:nyhS+9p/LA+HoB73cieIBA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:A1JZzjDkvvL5mYY=,iv:6+HL3Z7A+LrdCOQzB3fWb3p9ByNSMzKbLp9CZK7/Ia0=,tag:J8EE85L0sRUzJrEgfiv9+A==,type:str]
    HOMEPAGE_IP: ENC[AES256_GCM,data:fd78AAhCW2oG0+g=,iv:pjdn9mwunN01fhy36qL4+pzXo2JBQfb/rm+AzGnsf2o=,tag:bg9jO5D7RqRUmEz+eCg0/A==,type:str]
    HASS_IP: ENC[AES256_GCM,data:yZaFjtr3RmRm2GY=,iv:MTPX9/bpBZQWJm+IH1mizQucphs1NWcbuNq/cztYWvY=,tag:h0WPm+QDf8DWfYadgzL0dg==,type:str]
    JELLYFIN_IP: ENC[AES256_GCM,data:FqcLRax5PImzIMg=,iv:2gkvixcET5kloA99PRwuHCc4Pdb53uK/yG0B7ZzzaIk=,tag:B3DPagq3exODO+Ccrq2UXA==,type:str]
    NEXTCLOUD_IP: ENC[AES256_GCM,data:6xhfF2geE6W7zJI=,iv:0itu0Tc/xSpUYtagH1PE8vY35DLgipQIEmVcsxJTC/U=,tag:vKhqCFOlA1UBIjxbRh751Q==,type:str]
    MINECRAFT_IP: ENC[AES256_GCM,data:Kdxtr2P26jXWzPc=,iv:BKXpLik7YVjUSCoYbr+X7WwaEhzhYPfXQF/nQqbEEyQ=,tag:8IRkPxXOPKvqh+hNtl3moA==,type:str]
    SPEEDTEST_IP: ENC[AES256_GCM,data:+spwJ+Q+FhdOeC0=,iv:g0qZKhTu08Rj6rwNqpHJhub2jh+Bgn1jI7V5mYQHnv4=,tag:sRCoV5ih5pEuRhqKDeAobQ==,type:str]
    DNS_IP: ENC[AES256_GCM,data:L6zjB8ykLNLfftg=,iv:18Qa22ytYFtuAahWYFl7oHZ1lE0+UZDR0T342dzLCos=,tag:7zoDfKb3HtEBej+KUmFm0w==,type:str]
    HANDBRAKE_IP: ENC[AES256_GCM,data:Vt17k9MkviPab84=,iv:qnJ558T7cCHEyTS8eqzIOvb/eBJTwuqW+azs96t0/BM=,tag:rTjMN5LUU+ejF5NWkRPmIQ==,type:str]
    #ENC[AES256_GCM,data:70OoFcK02g==,iv:iMI5oyxfj7BBMN3Li+yuPwnjLlw3/Z8+7+Sjm0iLyUU=,tag:T3Ub/UfX0Y9r9FyfpZxRAA==,type:comment]
    EMAIL1: ENC[AES256_GCM,data:4/IucBaR8AjOZIZtwA/10A==,iv:b/pWxPNxh4CnZTeOSc3kDZhT5USdm4gpuw05FB5pUhY=,tag:t1cqSgOMmECrkZ2ZYIDnVw==,type:str]
    #ENC[AES256_GCM,data:VRPooXI=,iv:ZuzqmJw/y3AuMjHgtm4OVxEZr4YtxUsLKpvllYjQ55s=,tag:IdBzvE3UvMlzSSLZzL6JcA==,type:comment]
    B2_BUCKET: ENC[AES256_GCM,data:Ks/a6hR+aydk,iv:fCU/Tc6JnyuPUmjyAew9O89NQTW0PfSZGQ/2JfFgEnE=,tag:iWQtDkJrHjkloprr1F9JPg==,type:str]
    B2_ACCESSKEY: ENC[AES256_GCM,data:/v2n9R0nI42nZ5h4eWsJQjHx+xQF8CuqGA==,iv:wMpta1JgJ7HZc/T7HRYN/O65k57AdyhvGOQkFAeo/xE=,tag:zMcO+8m4sB6718bzqBIpcA==,type:str]
    B2_ENCRKEY: ENC[AES256_GCM,data:+qlMo3y/QE6iDD+0vPb6KgknXwkaNAP6Ssgn8T7u8vI=,iv:+5DuQpuA24hPF9uxfxiBcPVkF6MPJb2QKE2SCY4UXdo=,tag:YZqUs6Teaooxf/eXaFPwjg==,type:str]
    B2_SECRETKEY: ENC[AES256_GCM,data:JZbcP9BWfBJwG2NZYiXbMnydyvVIV5oclTI2H62d5A==,iv:hzPH9I7kl0FpSyr8s2lCNeUojMw4GxvX6Oc417JnVTc=,tag:5BtkRzmh4rGL5YHruAZEsQ==,type:str]
    B2_URL: ENC[AES256_GCM,data:qXqMefXhFebZAS7BzENpAbLHomWwOQB//557vyz3UD5i7RQ0D3Q=,iv:582E83z9OuaKhq0YWLTc7jOBiTp8GgPkiJpI5x9KwzY=,tag:E8rpJ9w6wGtTEYB7wYQ2BQ==,type:str]
    COLLABORA_ADMIN_PASS: ENC[AES256_GCM,data:cHIFBM4kqkeK705L,iv:pX3JoRUlIkGAUCkYx+lWE68+NgVk9yylAOzynundesc=,tag:b7Z/oLSK6ZYHJ+zDEXFbBw==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:AolI/0BjeezBAzBx48b0Cm3tm3WaCmTwYS367TFcNYBZbwJPUaPo6g==,iv:HWwAErHgas5wrWaTMs+w0GKQgL/sggJpmU6rjF2SC6Y=,tag:pTuZpnsSpWTLRgor/k5vpg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:QNXzcg==,iv:DL+hejq0Z7dyPc3Hd7m9tz90s1TLnLOTm6xZquvpnBQ=,tag:S/NjNPNrKy661JzNaQrFMQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUHBocUp1czgyNDhPeWZq
            VFBaMWtHRndiMGVnK0RiaThQaGNVT0ZoMWk4ClFPR0VUUDBOc3JKSXZtaFQwcUNY
            c3R1VTlyc1ZJZzRYSWViQ0s0QnNGN2MKLS0tIGhiVXI4RGxqbkVnaGdxalRsZ3JK
            d2dRelhIOVpudC9yNVUrM0w0bmZnemcKWYbh9SBp8gfQQOVJQpDASg8Bo64JKHdB
            p1WMC7YUwYGFCcHxpv+fXFwO9DTJlu0NYCC0uLnFAhnx7Cx7A2AQ7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T18:53:58Z"
    mac: ENC[AES256_GCM,data:GGJEyRlnP5wncbi5GQGSyQcB96p0O9Yy+N4f15BoyMYgejcFkHzYhgrliEJPC54ZINzmoH+uzBex/lvwKXu0cAS8v1F5bj26NQIhmoQ81VQ5P7cDQSesOM0sbJzxcaQxdfE2qIbHKe1tzkQYnWbCrxiv36ysjYfuoDQDb9K6CBo=,iv:DmeUzZn67EFCNwiU9oE6H9piUmfJX4VS6XClHK9cbUk=,tag:mbdXcSMnW338AgBXRnqJpw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
