apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PNl42k9PEuPbS8zGhMPSqvCB2RUDFAtabi1EhUxRooUb3ZySxc6SjHmHM1q/vd/Qqb0h5yDKvlo/mfCvZmC7lZ5CiAFb6I/FRhSc6jNNPdO5kJzkXu5XUCbTpLZUKPt1IBIvLKHpn5gOZXM3HxcL5uJaB00Ou8WTGolesoK+DhaCfWeForGidfnn+Aa1UTWQlmoS+FO8f4Tiaduq7Ua7Z+UZiD7Rm1ASUKBeoMe9I5EsODchGpL8NIr6GDtoVwWpPRSD5SzdHf8222PLS7j8wxFp2oM77M5Y4dQ7OU76WrY/TD1M2P3TBUaL4NBxQidOg2RYzjwvNtcKb4jvMApxO+mXu0lHA+syF3ruBWsutVNl48atdEDXVW4gEAO4Bvfe,iv:ejxR5rX05ff4iKiZBgObIFcOdxqE8xVnkz81Q0Hsvx8=,tag:/wOzMl8HU/E4wca5I+Bl7g==,type:str]
    identity.pub: ENC[AES256_GCM,data:CsdMdMFRYsdW1XaT/tdVDgjdpImvZUEDQzo1eGrlOqRGFTwuC8mJkx9il6Brbnc53ZrU0Z6YnuoBec4Ns7m/pwfOy683o0AqcBLZrER5//kGrR1ATK/EQcIFxrgyZC2Zslkce08yO0MH32JRPyR+pEY/4S/nGaVUtiYeEJfP7ZIPgypW19DHrJl8kEdd/hhafJwT+GXz9Atw9p6GZO17Kisc3hMuaP6yADjJCrOACijbyhjtAIUeuBXzs0CpJo4eykz3Q7rWmTrfTTK+jQ==,iv:BHM8LJpYW3m6I7KEc6D3VLXiYlK/mhMYq3ZqFVNfgiM=,tag:dFhPaCyi5oi70JM9+P9uww==,type:str]
    known_hosts: ENC[AES256_GCM,data:Bn+DyhKyE/ooNKlWhMmfkjcOPDerVT5ZeYAb3I+M0Y5h7brF4SRCoqTRzrJqM1t9Bd+AgRn/TEW4ATJLc5ngSEpJCVS5WauRV7BoPlbIMI5+uofK4XKQtjFJ/nKqtFK9smva7NXTKwfDKMRjufC6/lWX98P/vZArmpvOlhhX59WxlgU24c4KN0k2RPzmmNLFaWfczQUu9G5IzcGy9dwQUVmAB3FHXnuUwJrY,iv:YYq9t/HE/A/SBc7qAw6tynkFUZEArS3Ef47mURe1+JM=,tag:gAbu3Jmupu7F9gzxUvKv0g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scrc83rw7k5a49vvmke2r87ug22a6e6vk02dqpfsxas73llz95uq8pkx4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLM3JZS3lJS1RyQktta2ZG
            TVl2VVl5VlVhY3ZrSkd3aS95ZENaVm9rQmpJCndORXdtcHBKMjd6VEI0NFdRUlRE
            UFJkY1pnVnJTenlRc2hBaElOU1Q4cXcKLS0tIGZVTXEyN3NkUUxQbWQxUjh0ejJq
            NC9Cb2dtWXpaWEtrMmtLSnMvUFlIR1EKjyGRGlddYLD6Y5hqk9W/3w0ABF5sL6FN
            PopqB6fLLKYc1lbREUdwbdPt3ByR0RF40PXXMeKCakY4FbzEDplFKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T15:25:05Z"
    mac: ENC[AES256_GCM,data:HKEK5cTZSqjl9Io0jZURKxlWuqcDFbngATglkN9OjqyHzkUoWkXz+bLXB856R4kwcPfr1e1vuoAddXQYbnKvx0eH1PsOhE4yykGiAksG74ih4SeNzOGkxAOxWp2fJH1GpufhAV5A4fGl91t5ufx+UaEC06qBLWCAmFWfsk+pmdc=,iv:vNNyHDBHY13DqkkVI8BTihgnuSE2u1P9NB0MI/CPs4A=,tag:KJMYuPOGJ5aq8YHYau9jFQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
