apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/3HL7d/rpz4dGjdAlxFdLwFhQC+uIb7p+BEEWjshVUS5x8EWpgR17UE/8QQgNcP9BwofLwjtgeyq/H3OhORoxP/xZHXGh/TwA269kBtlZxmVlJGcKQgh/jxBZx21JcvGpd8+MGvZjOQRvLPeOUS5kSYHhnjlhvtTyKTavR0KHEO6U+neiAAaCsHrpfwVVPn0yr42yKycOQXO2xRp1srwhGt7W4BF72puLKroyG6dO48f692JslsU1p3zZYBCpNF/JS205grHYd1swTECcBr5tbw5d02EPEBfdfSWcIr0wUaRiv01PVFP2VM1BSiQZCAU3VXuHpieV2Ad+rLxQ/Qo4L7HzUgrKX47edHJSJfz6N22ygcFGF4hoAEgLF6pA3Ek,iv:UINH0T/1ug8YcV92NjN1YYnvYJw98QYyBQvwS2+Cst4=,tag:1BQHQZPOKWpPY1P6lA5peg==,type:str]
    identity.pub: ENC[AES256_GCM,data:1ZW2kmGorf8wPRjPELbTxPZ7UdtLTuokT+7OuVOpaz/7J9lviIbFRnKZ9M9Z3kNwG9Izoy73hs5BTLjKZuhyBi/5EXvINhIWsr8ikNoYeM07UmJvP7Y567uBCb9xNjP1LF2d+xOX3PYiKzjYsJNAxVYdMRcoGW5g4O6M9R9Pz03Yp5pL+sWgZ76VH9w7z1V/JHk7TtGAF6FR65I5E05tHvPilDciqK8CMZHspnJz11FrEeACE33/y2QUsAqFLrzmTtIYjCmG8yn1z1ZImQ==,iv:+JTj836GaB0Regk6f4oEPqjYdBvRk2/MWQu9MEAFpCE=,tag:T2h/nfVs219KSIOhA0MvdQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:t8CQy+HLiaHnHRWemw1P8fXD1Bp4xvFBJ9tsKVc8GNhwbCWNSjDI+uVm7ZUR7w/Gd1RMq793QfN8FmzVDilcry3UKKErU8TiLT6Q+jcyT0eplXgdH7dAM8hxDG482F5OUvYsuPsx1euQ6SKn153ZcYw7ZSu2A+Y8087+y9QuI6g7weNOji0N8c7xpFGUxlXUZf82oURgaLiHr7G7UJ02EvafIeXADO0ngiOa,iv:CSxPh2jbx+QG7yUP0iGWr/aPRoWh9mPGEV/2jJ8UsNQ=,tag:mtd19+AdFAoO8Zngpdev7g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbDFGcmRhTFc5YWRQNE5V
            amN1Wnp3azBreldEeVVrQVVGNEhGS1hwYmxVCmhtZUJOMlN0TklucVZzM0hETVRE
            VEdCTG5NcjZiTnUzeENaNXBoLzYyL00KLS0tIG5LR0piWit1RTlaUWRWZHdVRTBT
            cWd4N0NILy82UytDR2VjWDQvZWliUHMKw26PvCMKV18W7XeyHsfmtQ10YJn9pXeB
            3S2tiLpavObOvkl979sveqzbIKddOvuvzGJ+7T+piFkgkcCea3/c8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T12:40:52Z"
    mac: ENC[AES256_GCM,data:LmYRbNREngg95EH9EE9NyFdRnPk9c1rOvpubyq/Yq66iWBmXl00IWt1hhNvcPyGcbemg1vRclyWHzgZuIscsZ0D3Xp/0V5i2lF/MH8OJOMgx7SBMdnSBwv+o/voiLNpry0CTIs5GaWKqT6Pz/YxBtge78YtZkCgasZAJq/XN1SM=,iv:T6QJM87UDBLrbdQz5/hhejP26dit53zPjkSCQO/Gg8Q=,tag:m8lliHae4rUlyGjFoazSJA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
