apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:e/1MdGXZGR62HVOt7mXbMikxcQAtn+bpk4GmIYsUsbzTx9jTOnLQ4BVkB6A+6v2yDuhXFYTh8v7wLYLAB3E79tk1WYyWkx83Ky55eV27GikxhwLjE0PBEDtwdbSGE/Z5W4mFB+54nA32Vr6CDNqcxagKDU1Cqb1qQcKc9qzxnqAQ+ahfGMP1cUYQtPO495vWciKEq0uhPRr3GzYc6tHenMOzrTV9WYBNB8GeUDz5vWZrqc4Fpgz+JGNNEHRX4tSNa6PWqq5iZxcBNlifLgaC4de4NwOT8aJmG2fy1h0EnirJoHEyGMvtmUVvfrDpF+5dXmE82skDWCPoaZrGTDaVJZlMf/FogISKi1pX3VdbBMX7haoVuj+31Lc/x4AMtIiI,iv:NaQedCROVCjODt50f4ItOp/tc74Y/lFi05Nf4o5jvNc=,tag:oPvfze5inspLfIqcS2mzGg==,type:str]
    identity.pub: ENC[AES256_GCM,data:3VZjGpYuRNyr4RUEcKouLkRGgOlHuSyEqSBYlIGRioYtYScXfZf8UWaGX5Wozw+nyYWUNUqlc1TawMrLd7MLEZSEB9/C3dpFUafDxFnCAutBQYGZdn/OE8ts+QWzc6N7mdAU0CvU5D0PJYK8fcxE1pt9k5xKXVRcFtG+h4pPlRwGlCAExIV4UudmtOhHRU75MIVeFc1I80nh/z5/CW4yoD1xqiYX8nveMMPYdDrju9m3GhMclwISI+vZ5q6m8rFuSxLpCYs/jQqd6rzLXw==,iv:M8ntYj7Xbbetcn2mj6+moyz6+QH0XRQE2Ke/A+/XoPE=,tag:46wgVZx3Dp+6l19HsKh96A==,type:str]
    known_hosts: ENC[AES256_GCM,data:+Fu0KR7ZI7EVsv48gwt5wxz8NJz8KAXhQmmsXrRKQZGJebm2o2tkUuSi32bmUPWekj+FW3nQoFSMQrN2NtOAf81XTYdVkwRSWkeFP1//mGrKRSCUTheXLhEfprtQlolhTUCNQDM6ZwQaILvjm5SFagvACxyv3+/sjlIC/sYf0lay99ZXrbpaXQg2kzbG9vNMGJksUFEy8jCPVwCTKwy1N1civXbU81R3zIO7,iv:NowdnsxZO7Ow8WnZlKfllsIo+L38QhrfDtTnd4/ZHx8=,tag:LswDmsnuRPbhpj1XAl08wQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scrc83rw7k5a49vvmke2r87ug22a6e6vk02dqpfsxas73llz95uq8pkx4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSE9xcWtPaXdPUHB1TjZq
            SVAyOXc1ZEdYZm1SN3pyYTlZcVpWQTdyeEZzCkduVS96U2RJd0d6d3MzaCs0Z2lw
            QktSRkNaRWpxdWdFbTZEeVplYkJwVkUKLS0tIHNCZEd5bWF1U0UzY3pFNHNYL1hR
            enFMa01SRjhwS056c01aM0FuaFRqb0UK06xzWAXNcVRgAtFKXgb1FEJHfmtt5n29
            h0CwtWr/UVkxOLoUCAiFcjfkF/Qq/DdA59UprPGGaln+Lh1YRnWkbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T14:14:08Z"
    mac: ENC[AES256_GCM,data:jO2yJssqtq8iKvTq/mRH5wqg21DmKw/R3+IlpxgnQa4KIg5qshVmeM8h194Z5fVUR77ywVsiDr4o7tyYxBTRId7Z1tUj/2TGzyeb0ewogR5j9DSPfHcVqYQHLZP+eAjGG6pZgQ6skTvsgLADTstsTF4P3mgtb/1WkpVkZ20/tOQ=,iv:47B4mHmr2NIshvy9+jVCaJGYDK/b5xLtERiX9ZePjfg=,tag:0AziPb7Ve21HPxAhvI135g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
