apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5x/YJrgytNiWuGUoM8lmANdfqkXwLari0JtslDnjFp10fNKzQkzJhiLHuDwQMX0PfgU9vADugu4E+NHME6g+9/r3NNKwFdqEx93pVbeUNxLc92TD1riVYf1AyQkIj3ITc80nWR3ndHHgnd9Uci43DkRN0Ku/D1Pcziy3GtLZ+LUOKvYQwGonTDA9h9F+pFvpC0TxvsB7GeJQP/BrLj1ICDoQTEjUSFGkXa+w/h9SMluHbfLvUOkI0n1IoLgR8Uu8hGnEjb9vTHEhBVu92a1W2lSjwE1RxDNqZrZaT6fCeGoOvTV3BvjqSAwWFongKa+/lKa3Pp407N9Rv4TFreTaLUxLtG3MkeYH8sGu48ReTulig4MWhsvSA2XvmRoyf8xJ,iv:IelU2AdRpi74SFt3ENFwcm1BdCSyhjgunVME8ANKeJQ=,tag:rdcw1HrVwui7/nOGfw2lFw==,type:str]
    identity.pub: ENC[AES256_GCM,data:yUJt8rWLoyWUyAOE6Vhhit1nVd9fhwtmS+B+ufJD7rCiU+M7CSODo4r+zUYjsCHIRr4r2W4JeFe3LvsDuC+K1yoVzcrq4LOvu7hhJvPQR5otRqZc/5eOkH5T705P9jpITRqbEKdXyiBGmFhMR8iDVEiyYny4LY/P7regfv3ELWJmG0djc7fesHU9KW+pt77FrEd84fXTjr494ePc7Cthkfiz8gtq8ggYCXflUTU/xNm189EsKhYUFyc03ZE95MMWwNoROLG8HD8qA4vPWg==,iv:YvQOZC4ZxWe+1d+b6He8RU4F7fsd0WPCX76jyCFCzKY=,tag:FgMQsUG5Um6+YFTNrrTBHw==,type:str]
    known_hosts: ENC[AES256_GCM,data:x3vk6pZlrGi8TdRtiVKSKn1CqG2vyo1VSP/nFaFhGVBGWJsrov6r3ABLWZaZF0bImWWf1Jr74IsE6UGdEEAAM9XuEp2NBTHCZeDJuq5wLq92TXV1Kg6hy4cM7/nsKgwe3gZQZF0i1LPfWbNfk3/lApeiTHtrQo5n6B8YgW/6Cidc7ZjvtznQYOIykcvEQq1y0e78/nFORsCIecFGt7FxPOQUl78XZgHiqLeg,iv:C0tWbB0Gzy5u6I93dFRiG1p+xfWMd6D+tRPKmEbFziI=,tag:fZtEJ/rZr+/gWjAZzwQfIw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scrc83rw7k5a49vvmke2r87ug22a6e6vk02dqpfsxas73llz95uq8pkx4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyL0RKWW9qR2Q0VkNUTkQ5
            UFJjcXV1LzltT1VNNW1WSCtucisxbllWYnpnClJRamoyMDhrR2h6NXorTjl4cm02
            Qk5XVmJrR3U1dkR3MFVBQTlybElkcW8KLS0tIEVjYlVOd0tUd0w3TDRCL280K0J2
            anFSS3NLOFpTejkwYjMxUTdUZWJ6cEEK/IRR2mXGi4G8pkEZ3pU816JpgOncghqe
            S+wQ2M+DhGV+H9de4EetwO09+Zqb1pXGshmR6+IHceS9QmmevUHEZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T13:22:20Z"
    mac: ENC[AES256_GCM,data:Ff7ZnXryfgMuMvzCtZUQars6Xpo+QLg5QqIoWd39mgkBavC1BU0mIBdJpxR457Om1WypI5nUWjUShk5O4AQ/Uom+Dfieh0KhrrMlLrxc+aR5kKmG2lQ231xwhRi5DRwjX5EjfFEOKQL5NfBM+V419yp8eQ4zltach79JhlmIbyQ=,iv:9fupvvaX4tZ3jOPKEqYXcldTFI2tm1f5pcIzOYpy4Mg=,tag:xqHKc/hupWvWyi2EW3EqKQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
