apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:n1oqVJYU6RMZsJ8JTtvt/bYdczSxKVxAVFcpdp5ENFq5tVRMUryEcATTlLc1Wt5qS45bDoCC1T7ZV2FRm1/rjiDJ5G3IXHVj2LQDHQnUHdcwwWUAIVGpEyyhRRrI4uAQwGmKF+rMH3Le5e6QgLwXdDt3r8/tfRW7WaIVabwJUD4gEuPD/9CM0VwGMNSFTCTheJuQUaOvf76PgowtRt+8DrHg8tlvFNzLUoCZr9LCPCzPVg9TWKDu6lPqUhlkV07Qwo4yqaRVr8efp0rdPiUQGYNCZqlEz2AnUfuLbuyxXXVyaXjUNBCmuuESObY7MMINLC+XvqCcU0jt/rcRF6q4K8K73XQ5ReUXebfF+EflAkM7t1084/a0hnNMDmXnVyKP,iv:uG1Rm4iRC7pldHxvfParay6s/y7DGBcrGUb8Xhlp6ZA=,tag:s1xzLMp3i6wKbB1MDgV6Iw==,type:str]
    identity.pub: ENC[AES256_GCM,data:PiVX4e4BPKx94+eCOiKU+Z74t+J/UN1g08yq6IRmhhi8FoINoNNosyE6Bs4Ll113vmHCb4m8bchq8dWwrUE8KhPQeoPFfcr0uLl7FQf3bOvDi41OT0gQwW/OkTrjcltcWL8RHSoxXDvEaZB1xLcvLYLuvN0LK28SvpdRSTGrexdaKU7jdvANMSZLy6F53NTYS5eC9HSkf6En3T0rXARfJZ7X9qJiZaZvKhgnA3K81NjZIh6KwZdsjC7wlTT8mO07JC0Lve3A5GhpNr7epQ==,iv:MnUM//GJZJOIN2caRwxkEz517ALYyKceukAWT0ptV28=,tag:t/oCAKhlzmet3IRkbABmFA==,type:str]
    known_hosts: ENC[AES256_GCM,data:R4F3Wi54fpPZdeojGCn+bYwDyvBsvwGGfiTBu2x+danAIFRUxWQsUL996SujqFPlhiP8m3gM9xdKy0s7YNBKqK4rCDV/9hbMlrb3EW50Ko/oNyOzzomKJlFZUdz7AHcoOsdrmmaJNtfRaUGbYskrb14zJSc4Fi2y/JwTdJTKCJqPZJmgZ0B292D9OMDVV7TQB3M6elRxAdF5n+RPCwyba2WX878ejjDD5fEH,iv:vyNMZIHeTNx8c1vIcXIa5L/u2V/BuzaLdcPXQZyowdM=,tag:6XkD7sljvlwptoaX+I17UQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYnliVmV0YmhZZlJrYVp2
            KzZETmJreGhOdnFsYnpMWWlKUzhiVk03TUZZCnZ3K0ZqZ2tCc0pJekJmMGhBY3pS
            bW82NnZSYVF5UzE1cVQrNFpxN09DZTAKLS0tIGdvZXJrL2FVNkF0d0YwYThoenRN
            L0dFbXNhVlFNZ0ZYeDF3Nk1VazcwTDAKHT8b3xkYrJv6ZMunyZ+2g7mQbwyZUQuF
            oxYcsXI6wbXYhRdOLrdrz4HI1nJDSurKY47YIYi4/NxJRpPGVh9p+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T12:11:27Z"
    mac: ENC[AES256_GCM,data:aIyRd2qKPhvM2EnDuzXCrzQFSN1GCIXSg8NAldgwUzXMfz5RZuFIhP6LjUY+v42S8FKGUdd4A7FsMEz1qIkT7v3wT6UgDaDUe/IEK1VgDnQ8+0vbmKTbltEQrNSLnwbHvih0IRTjMZa2cUC7tNe2YM92w8uCP/XS/mbM5GLvynI=,iv:ZrLuRQUcDPlhSMIGvXNk3nyOI1jDerC5PU2g+EeB4c0=,tag:8ZutqzvPxZpqOVqzgzNppw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
