apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:sty+qkrF4HHIZMTLMeInd9Oa905gTwwBWsKkv53jwX46CIlcz28WXOG+nbGX+XecN868FJ2ZlweQ5OWKxKK/dSZJxn/7yEqGEGayRbjH8UJaF8BDchgqn6zCqy6f9xDIoItLKBQWUuy8o8Yplj56pKYrZ9/iY+l0yDTsqM4A1yuEgkiIrECexb4TecLlw8/mf6nbw+pFDTgwgpniQSqhxHq20tP/rQCjKZldIgllDJL/sCf5Lu03C/cEcsWUyqxpU/K6Iv7xlCc+Bqo1luffeYJaaiX4M9nmj4USdETnGI6jNjUO7CpMS4NUFY67Ggs1zufen2s41RaPX4QyH6nTQbLvvyKqvljEFETWwOtU5P2Km2AEqeK+d/3O/BiM2irS,iv:j8teCnk4WIdfIeiqKOCLP1r/0iK7SJ3Yp1uaK1GM2UU=,tag:dD7ZHzKHknMse1MZfl6A+Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:am+huO5ih6SoVBZFUHOInkAOzbmZ9x0O7ZI+7TgdrHknebWZ/Z6EQaGOUZsih7RrKiEOC44dsssDyvUOyL5HYwxfsnEusDARS6oFBgXLk4lGvX4DSmf5HoVYg7o930AVKlJqTZjpXUKyM4P0okzSf87m7y5tGqHIPPtQaxGd7TfWyMKCPbJu7wpV72DLWAgXpxhGd0/2QC4c52TfZ5m2uZYI9Mf4fjMHWibi+BUvpunECblN/ZjTT2lkSzUJPtC5TsTlprxzWBZh3w31Xw==,iv:r/MOcWurdnZSPu29xrRtPhLPcfCRskHuutOWVKMum7I=,tag:LAPUUwltlp4bibwyxqyz4A==,type:str]
    known_hosts: ENC[AES256_GCM,data:FYDTKE8gFXHmf+t9MpJ5dnXDJr7B3lEiVokfSuS1cj8B+5z2ZAdKFytWWyoRzfGQCFYW+J5NEqDRqHDB0hawzR3FFgqcSf565aPJwtpriJtHPhKsxYFyq6K8UtJJoeQ2t3xpWYJ5g7d5Ouv3Zt4pj7nvO1+w5xNrli7ofApj5IdjL35PwuT2gb2CPm/FReb7YwBtmuAk0GifReZ54Xim+Vr8r1IkT5xOidJr,iv:9XX7vzK33uWBYwwA1FoPTTbxCdxZgm13l/SRqYG6WIk=,tag:QPOE0LFzFC+6sigwyVzsaA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scrc83rw7k5a49vvmke2r87ug22a6e6vk02dqpfsxas73llz95uq8pkx4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsckthUFdiUFRTeHhOanBp
            N2QzZ2l4UUtwTXpWOUVRNlZwN2o1RmVkVGhBCnJGeUZNTHBYNzlXMlk3Tk5WcVBj
            dWwvUFJGMGhxa2E3MGswMW5PcXJpMXcKLS0tIGZhajNpZDlCMjhKdTRGMzBzQ01M
            aG41Y1ZMN3FmTExKeUw5SjF3WSs5WFUKfdb47hq7lsqPwFer8cFXD/DqRR0Uho08
            q+amXhS8/6sgWLXh54mIMGTdTmZSrVhxBbe6D7d5f1K9acMJaP+cig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T17:23:05Z"
    mac: ENC[AES256_GCM,data:UPZatMfJxaWvfoB+NCnH5rg4+KvCGyfInvmSjNgG0EwCkMCSYFANIXaIkwxwmj8iRX1m2buZBLg6VBmqOxUtwc4nKUtSIYm+mpwmkTjkpyKDqkfAJtOvzyrJPrsVjHnW1k2p6W9qfzL+fBHmNn5ytagI4tLVXvMrd5OK+4JNeyI=,iv:sZIU/1FfJWYTLTm/dfMx5OyGZTbznNNv63S7N9p2dEM=,tag:eESrtol4bj4QcbFkJdr4Qw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
