apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:GJ7DdUk/t7wdiW3vTcBcxDuj5iJRhkxrpFUv5jY5hdEqbbZI4/NhitUjJUj2sB3BJ8PKRz+2jomVVgAc5TQ2bqQEb6n0nO++aC+Rk9FVvs2MQgse31ugWK6MoHqJ8BZlKSbr/kMd9EB35YCMmhtrJVpZ4t76s5TG75hNdtqJ9A18yDj/gRhk4GVJxOgwrrGf/mtUqGtdPb6zB+cd3H+enkbd2VpBceXj81JYWe112Ujiwm4YqRC+9PNkURv3VPfmkErqHpb5SJNsyHrTHSAqVJ6r+qLNFJoK5qYFhd8kE70bWkHciD3j+GauOHQuyyYIlO4HoJVA6y9b57atmI3CdPamjFezvVltRxvCUGZMQW2KPk/FM6+4RlueDfRZYXr0,iv:adj0koccytWc+vvinJhY26j8j8QeSOsQ37utYC+1jhc=,tag:GV5brKXHmycDpWdMjHm7PA==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZNxVwPE2AZpfhkWZFdhNQ0/+0vcO+oQPYfiYEmnqeXSi2mUdgxwthweRrIYb2ODY4Xi8EFAaDj7teoCdSQ/5WTGBQGC2Ri7jOCCKvvaBw5MwaCWjoDsMvZdqTiHfadlK8seKEx7sbMtfG8+V7uSnLuvNh8KVh8iOYWfI12OroZPjY3fkJYJA5jR9oshVMZ6jR6QF/c7pbIOXoP2FTY8wuSqLh7gcSn3W1Zpz014axdKD3zfRR7BsFNMpXzU3o1EWrzhgQiMmMcHtWbxtwg==,iv:bhD8Lpm/cUvSY1wRElcs5rzt5A7zhS8EVKIPBehF6SU=,tag:2wp3fz3N+DW7uoU17Uveyw==,type:str]
    known_hosts: ENC[AES256_GCM,data:8+qpohEVRwQlU5eb3lsG1DNuKArCUE18UGv62KYjLVT+gfQr4AN6q929TnStxWVo6qsl/rrrVr3C3mXYRs1VfbN9XWE8VTQM2LVDynGMtfQHxjor0P//sONv1AKc48O5H6ssJwxbG6uyDmPeo8E7ezzYbl9kc3jxk3o9CBRIMwPb4ASRBZhyNlYrowyC9CtTbQwt0MLVx5ygwtfKTTJgllyBuYO5J/KJbzHY,iv:jBa+5h384/80iqZx0hJGERLleYvGp5DkGG/xJri2gxM=,tag:EnbcyKEE/fCQH6wYvMWAkA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeDhkNVluT2NONllPellx
            aERZOTVaeWgxQk9VY3orMDNrLzFvYVBrdlZnCi9FbTd1YzJ5N0hFU3JwL3lXQmF6
            WVpoV0ZMbWtIZXNkeVFLWkJWTHhjaVEKLS0tIGFHTlJlSWVmajZJNW5obWhkSVRN
            eHRWZ0RrcXRKcE43NDhIczJDUkdJSFEKPIAxuYWsLThLmqfJXIceAiXtcDJh/VNq
            E6zSopS6j7wxykM6/pIb60YZXaA9Sxy6BB/7rj+Ob3GwkAHcTgBnQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T12:28:14Z"
    mac: ENC[AES256_GCM,data:Y1xrRi2JeVLWh7WHrUOpE7dusXZmgFuQAngo8AafnNLSXaUrw9QoOLQUMuw9I8MMk/MFbSIYMj1Wd2dVeEDoLJ+YfaVc1zMwCFMQDL2Chqu/m2NEA5KlYUJpd3imQYYyT2W3glOxA5Q5+uY1TI4dx+rNgbit4y4iDLpbWm9f2Z0=,iv:Mnpu9dW+2+RVrswFDF8617oC1B9jp+pa2diiBScSzfU=,tag:1bxo+Q7e0Zbe9MxgRLSdSg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
