apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:MudHr6vBVxYYdEj0IkX4WHVzXwHaKfe6pPy12WJAs6fD7klgnof2aF7mnW4rKhbKOh4th7J+2o4iPgzCOP3I1r3RwoeAol9lryGhbcsBqQ4wrwojiMjncQhqDYridfqPoafgTQYm3Qvlae+V2MM1lADp/EWOu5lCuNriGn4397F7SevGNeDNoJ2WH5l+Hv1/U5Y42a66ZVKoLEt8Bj6MqEdiV31hJDVz/CqQuVUPfe6gyO9U1+FcLmSiP0rmLb4Sy2EWMBWrUZF+23BPPXkaaC2aGijQWXitz59GNOGHLarTn59bJpTSrNT8d12B7ztUNtQ3cLQoQuU7bvdc5o+YksdW9tI1ciP+bTPtu2e7QMJNtlOxIMARMb72BMdl+ith,iv:yOh5WJq9aF3dkC37R6YiHlMyGN3dVvKPFVRpRhgnjps=,tag:czblCt7iS1dv4TC2mrNrEA==,type:str]
    identity.pub: ENC[AES256_GCM,data:qQBn4s7lUpHGVQmS0Lmzs7lRK3JAI4Lhdykf4UUapXY6JomgcuNY4SuBnTW2PzkCPH0Noadl7r9cScny6x3WwlMRxmz0CsZZRzmHFTJZ5vLMZnq2lws36VIgUfNZ1cmVu/XAHAuoKbCNCjmH1eYXgU0h2+nDFMIEzRWM1dsyUwcrnr0AFH1ek3iGzcZe8yE0nlp3RKtq6yQvFq31ezKebNkFE6hQv1R3jGHB/M/bEVvR7WFT9dLU4UwjqkWvnLFS0hq4jc6OS1lc4ZIg3Q==,iv:e/kiG96+J6q4gjzkI6bbp9ZjFMDS8vZWZxw6Rih3Bv4=,tag:Pbw55L8hMYRxO5lmyKYvkQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:KKRg1RYKBRhrK9e+Ddg7QsR+8rtFzTIDJWrVIY2Ig45QKMh9hrUshDvrS0Ac47EZwOmTXeH56eYbwNGD16CJaEMvSCei0vDIZmc9Oa7+hmJdpTJns5OkVdmzhvzt5iJjae4HOVfbv5BIlpgb/7SPrTbWinM7mXLm/43LU22jEeENMKV1Vxu2XIOiZ4FzYP2qZQ40/F1TRhmMn0r6uzWBQiAuLEHiha+pOJc/,iv:Sdfg9Pm9B4160EObVd5v9HFsEJDjvuVy/WaCbjh3OX8=,tag:2czO76aHFS05MrQGyYktFQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scrc83rw7k5a49vvmke2r87ug22a6e6vk02dqpfsxas73llz95uq8pkx4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3c2VHekhzb1dvMjRLR0x6
            V295aVdRb2lhZGoyRE9rRmdwdHBoeU15NnpZClZ0YkZXKzVSMzI0dU01aVhqZDBR
            NkxmbDlzamxVcjBrdW1UVmJNSVd0eVUKLS0tIHRKK2srU1h6c1MrVTZzRTFBZGQ1
            b1hVeTh4K2pveWZZbUIwaWxRTUt1SDgKlwv3EhFx+2QaM3XgNbqBaXDrPvzgBmUq
            gpdVyNBuWkHMnbunczSxO3F5tiud2IZsb9lJWFgKjQ/PuilknQnOQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T15:49:57Z"
    mac: ENC[AES256_GCM,data:yHpyVpjQc3hbVnqMFj8mR6mLDyep8a+s7uoiL0GnTimChZ51gSlKU/kJoZj6nBuDPZkgnJZbpg7EbCLJAS5ylIOnkddRJJyy92ar03TFEZQu+xuU0P/VDRkmcB1qeL6bblFVLhPtR6kIR4qE3j3zYopD7yJWuORqk7I0vFVhVZI=,iv:O2GM8HDj9vTGW2cFBJJ/yW0R6HP5tz6LTAoTsCzqhdM=,tag:+YRxoi8NgQSCPdLJTG6yOg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
