apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Pry9gNWPqIqr0TkKR0v5KFRFtbclArxjmrjrWk+9reuxHnCLVfWzGPn0VooX5VUX7+CXBPuf1D2s93r7aMjeUbuY9dfKqGNmsH1QfrhSK9O7jPLdTJd5pM/eAytRc2LPuMZMjlBT2II/QAn9Pivfv6vywdNJ1lCs/I8CVubufYi95meMigMUegz+afbZEcuIOOcshAblQqS5gzj3ah01cAd9omzmF0kyP/1B0zNuXJufVdLeKGh3OeB6B0IMN36FVBfvgXWmdwciWmHPS4tQXJB1MOTJI0VXIWvfDtUlIyHROr3ci0VgDfyh+czPA2fQ1lAHrHPR/UZ3mzzPVl1dnkKPHKizJ1Pa96Rlw1B38iWqob3eRGm6PPzzR10l9kyH,iv:ybtdRyMvCoG7XEywMN3L8g5swXwLNVvvhohcw9yVRTo=,tag:3hjOYfa8UfNM3ZZXf8MXhw==,type:str]
    identity.pub: ENC[AES256_GCM,data:0ZPOGmzU34QOqGJjj3x6SwNRzfOXDEiMDW/GsAoYDGhECJiNBLsZd8mzgELyuhQWdGyG7BejN3sfCgBUf5vc6kqKHQeCVs02QCf9SANsPotM4Uv62QeeVW/cHPXpVL02xIxGeEf2lFcZ7ZV/hNd4c7571tJDdnnPxGdGbrFzcoMGL9gZweXjGkL1k7o3VPltv81ZnCdoAdCztFIA0LXDK7X2GJKR+6Dhz9zH4h+lOir34omhTM1tw2ZZkW8d8ZN1vh98YNbZin7QTKhfzw==,iv:5bWfkvCQXw91j4yHP9TS7cH/MPl+9genLhGwC2iD4UE=,tag:/QfNpgw1uTDSHRlltdEUDA==,type:str]
    known_hosts: ENC[AES256_GCM,data:COx2uvGOjebIgDOmdLNsdVO2036sSLaUiqbKjZu4rfcLOjKy+LdOBZ+oge85J716HOwmN0mFM/JNhAe2fgPpx9Tvb+DOAwJ/+gfiTF9Ehqijce0ukrtaCPYQDxj5Om5zyGBXhKikigDOoGrrSTBVdugrknej3hVuvy5y2envVx1uqnbuLGkBF7jhawurWqTDsL1fBimtSjx02BQAPWswZBKRbEhhz4eWCt1s,iv:vJasQqlavs8QyrZlbzOPMNYWWXTRrVlWkhday/luhBg=,tag:As89pz0Fwq4xf47Z3q9V9g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFU0FQMUxDSUFVMkR0eFo4
            ZE85elJOSTZqRkU0a3hhRlk0d2swak9PU3pzCjl2U29OdWorcW40dFZ1K1loTUtU
            ak5hNXZ5R3E3a2VmV3JoMCt2V0ZMamcKLS0tIHp3TmdMcW93WklXQzg3T0pPY2hz
            TUt4aFFhR0ZjR0V4cis2K3FGYnlTTVkKPd9bu79w/x7WEvya41jNg9uUU33N4XOq
            eRplkQ8KNX1gFAKw9TXW/Ko/n8X8krsntShG7Aj5FHsxcgPnuCTAyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-18T09:46:01Z"
    mac: ENC[AES256_GCM,data:B41HCapL+kn+NQ29xWDrgYgEPTqKsfZRd2Hb+nl7eJdYY6qqaJTGTlsLJ7NXQV+5MLXZMy2hMVWvJnxByVeNRM/kROzvdE9Sw0ORAVqQ2JczVYM4YgD9WJNz0hZN6Mh/31Vbr93W/y0qofZvCQ+xLpT/n4m5Mwwz+QJMr7QY5WE=,iv:yvfe4g8yzro4l8ISW2/ua/lUJKsnvQikIZatrAyTkR0=,tag:6v7uGhpf9gafY38pjMXPyg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
