apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9wXjXN1204ewD4nBMoge3AJjVHDYa2fs4+jkJhrsTCFU4XyFm+hwsX+tE9Ny9VmJKmN4fAvWKhwE0CZZAvKr0jqUkkZSzh+oazyuJnxN7D8tQcLUGNEYEpkwW5XEg3zegR3Gp6OWRNWb7qcMQMyIhzJRM+JHHpaYt3xEtz7lgOOrUOepmFkK2Ug6Y/SkFbwgoBCrio0//HbWFvRfeqBxzLu7yNDgKSzJG/KuM2/k87zdfxgs4UYp6gEvyaLCe9CjCUcFZIy2VVLNsTL+27t24LsZ4cwjUE8Z6DMUp6jp2kNtV4+IWucMYtbnzLLHQRCrqIj1Cmw/PKZgvDaPrM5MXIvtADMCEbYOIng3FKDJtLn1h9/4RLf2laYS5W2xiiBZ,iv:gDwthcOQEJGYqiz/cRZh78dsG2WDPPvhF8xEZhkC2eM=,tag:5eR0lYsVmDrVU+/8AH7fEw==,type:str]
    identity.pub: ENC[AES256_GCM,data:WCdurQFEC3IXgUezzptwh46pwcDRf5uOK9o/corI2df6jv5ESyhMX1xeZD0NeDThgp4LjuJoFqRQF2nHLbmUILq7UR9dZnQ/EnAhwiFcq8dNIr2aN/HHzMSvLyAxYHxw7lhOQ/JOUkwANUsFFKnehL9bcHxdqy4xo5m78PV3dAEF3B4JlATYoZZ6pxhqWXmOBWq68CULELiSm9cHukWDTpRj+IBOCeG4kBxfhMLlrxwGfKVbqASEWew3gNq3HyX8r6gDgEXs/VBB+94trg==,iv:dSRTzrTOaVQ408iSekEUfwlx5jNxoXQAeGy+BbRBpWQ=,tag:7R189Xbokho6oQtJsw35lg==,type:str]
    known_hosts: ENC[AES256_GCM,data:W/PDHo5umk+sFLQ9ebGIvgmk3rP9KtsfDcEm1XhjwH1/awob8HS3M4FECLUK6WYhbNBRCbOPZ88zgQHtRzRk/BEKEb0yLXKSZ78qxLKA+87aSpxhRPGJsmii1ikdIiQiLbLoo2dfPsWatvc4j8ZpmSt3lyL8zpAhzgsFcg8eBX5xcN/84MgwZR9uqbtvkHbOc8B+ahUJ+j3QpnDzv0FwQ+9bOOXdLPv6d76J,iv:XUSpAP7gevgFz+4r/4LOmXun5x/albZdM08duknh3qo=,tag:j/mduseOji2UR6MoWNRpXw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scrc83rw7k5a49vvmke2r87ug22a6e6vk02dqpfsxas73llz95uq8pkx4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNXpRTEUwRjFBMCtteVBa
            Q0tJeDlEcFFIYytyRU9UR3NpajE2emVrTHdnCkpoTVhiQ3BKT1lJaFRGUHZ2bkVB
            QVlLbXFwWGh4L3RVWnFrTS8vMDI5Y3MKLS0tIE03TUcvZzZMYkQ5a1FkcU9oK0RC
            Mmpxd0xxMHA4VXlGc0trY2FYbVdLSk0KYp5k6ilAfTXg4L2msFY9s4dmJRn0LQqA
            CQzR20HDFHZoeeLW106m6bjHyMWS+J+hfK5Xkt8gGFtIyFkttISBDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-27T01:48:29Z"
    mac: ENC[AES256_GCM,data:lA3IptMkxT7d0fnccYpJnaMvhbAvbRSATaJ/ofRPcAv9mziAjUoL6HdfgmJQYR3uxAJiBJm1rZLVQR0+vC1Dpe9mm1/PfJbD6d3ycsaLimDbdKZihBvBQFad7kCs57zoqeOpqaYNeAdnbox90L0Ks1s0tO7hpsbAYjdVy9NZFKQ=,iv:FotJnk81CDYFjvIdahkVqwiYyu3a0oJ6B/1j8LRiFqI=,tag:U7YfUTWCVcvVfvmgHqtzwA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
