apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HYcUZhkM/5KIx8AlkZE9h9DYdS8F+uWRvwNYKN1Lm167czu8el9iPAiBAr+eynSQLjjU/ZBg1VYVRE4VI6O/bKPT91TPX/f3EWYmcj1b0HGFJWtmgWXsyk8/+NQuVnG3XNB8Kf44qb9T22sQRjNlv2+8/ZXdVhFZbHUaKMEstZmM56Ye2cTZw3fB9Gputw2MfiHISmqlRG0c2m9Ryik3HeBLOhMdbtrtQhfRippN6Nrmh6YVPaUKDOePwPwuW5S1IdmVaIReWkeVtxVSAZfHnIdjYXXLqIRfsYxrx+OCJa9A4jMQg2oP1kVGgVgb6Zi2X5RbO8Zqti6BVgFGNpts3XCNXioTM5vXzCpPbNth5z4LcRIPanmC6D9ipFmSFp2x,iv:irZ6gZcPTf7j0eGuC5xNpSDsfXURJqe6lMejraMOdL0=,tag:jJp4UGdwnTAFTWRQybFgNg==,type:str]
    identity.pub: ENC[AES256_GCM,data:jLVRbNzaBjMgB26gpzkl8i5p3ykttgPpJr+ch6+fzHEr3Dsb7S+H99OOaZCxXqdRqdi5Z+V3CcAJ1DiKDdft9WcZjH9nlCWPjcx6C91ixeKz+IR/bB9ctJtaN61qWV/UBR1Hh2k6uObxKU+ZpI6EkWnJSFL5PsqMifauOM+M1wgoTxFHwgBNUJRcAobs8ddyssNc++VikQSJTj6MDVcfs+3uuOclwxLSJ9wMi1RXssI7TyYBmVTM3v108Glg1FpQFCAZrIXS14EaYYtTVA==,iv:DtApbUG4dhFsHO3fTYzqbovZZlew0x+q3QRiqR79kJU=,tag:OifYzyLtkXyHwJm1rUGXUA==,type:str]
    known_hosts: ENC[AES256_GCM,data:D0xAq43lYuBVNHBMMJKlafFrsD8TPV7DnXxDo+Q0AsLCQswxbnNKhcJ49x9fRClopCt7MnaqGNDcZIQYnjgQGLQ3iARDsSRMLZiq4Z5nlLC5+BewRaWQiiz+MrjwXyMC/N1sze4Sx6wYaTjJn9ANXQe0gl1DMsl/Sbn8iDr/uBKW6nCQneQdOxvUdf3GiB1oxQE3rwrIlPZ//ZaDP2Qf+QekvxKK7qMEyQ0P,iv:dEzgaLmTkxGlHq6FWke8HCOU8ghUrv72nP+0ffATtho=,tag:+i4CMNmWPp929g/ktpK4QA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scrc83rw7k5a49vvmke2r87ug22a6e6vk02dqpfsxas73llz95uq8pkx4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VEF4aDE0RUtnTFlRQ0E0
            bzZUQUx2SHFINGhVSDd6enZCT21QZG5keGcwCmxlSUdhemxkeUtvZlRhaVIrWjA3
            NWdNUVEwWGlKekFsTnJNM2VQaHc0ejAKLS0tIHFJM1pZUC9qWFg3c1ltUVpxbWQy
            VkNLRTJGUEYwWWtwenhxR3JaZFlKeTAKYb9vGUCikssEFbwCrS6SJEHV7cVJ8wNU
            41RaxvvALoCVb5vcevFs0nvPDqefTfeN0L3mmeIjWryPYZyEKSKiTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-09T17:09:34Z"
    mac: ENC[AES256_GCM,data:/ASmCxeWTV4rL7xML928KaG46ULZu6K8o5v6jaJo7bNTdm++w6MZTwX+Ux2Umx+/ds+k1nBr15WWFyHafK0kDucVY6i8GaG5ROjn9cCe1YeH7XW0buHEQOcC0bXoUduLG30UztEmW7IA+z1wCiuy/jAPuxb5BUOEJ3xUXxuz4GQ=,iv:rmbHNitVqoZaLGGc4/dfdwNdwf8XFGfQf9uSx3R9g4I=,tag:uirNTFiCzE9GKqMFONisUw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
