apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wKBcFhFQnAXUmuHVYUXm+iV5ZJ5RyDwwoxxXoVV3L5N0dDtbI9XtMPKY3IzePjTYggxVXk0rcWmKsbBW55xgLRqq2mu6YQ1SlTSzYCpYTI742NWEQCS0iYZNJ8/Y2x4w1jnuhMPdye6O0KZWMftCVO3AC5/Y6uO241s7moGAsaexU81XE7voD+Llq90Q4uMy8spGTKrLngc4rIX9M2KnEzGafzCKTaKhfGQH0++V2mHh7mYLOYCap9odt0w5+u+B7YM/1mRMHjI1e8wUxBcG3cm0ysZPEldlp5+nTJ53kOkXgFhoxaUVWKUWX/MG6Qgu4P/U9QTdTu5iJLjqIudks7AymXhTJBVhC40IItjpmBjLJ+yQ7MdSlFaVpJeekBVM,iv:TJUoZ6aHTw/crcMN5wkHlf2QGkXHKulxJKJmNz8IJ3o=,tag:ZcOPoBXc6HJX7OEBw1kFqA==,type:str]
    identity.pub: ENC[AES256_GCM,data:QHGlh+cBHL0vr0MCNBHxERLI6h5+ULULQecSmScVWDLkv8xCLL0TFFQ7CrR/lG1J15ITRf1IMsuwbAbZ4W3xNv0WDnFRO991tFYIuJ3jQDom9S6eihCWXwlXKvhe/89WyjJE0FZvZF438CvChI34GSQKj3v407vzI/KjrB+NGfie0ph5r4MMpC/caj+fz9HC2MhLD1kY53Ud2G79yUo6PjxuQQkLIaPWhUc8QYJ9wGMV1DsQhzdfH9a/alYMIguyx8Bs+wI3IkuEaI53Vg==,iv:nB0DOyY1qWBGOSnr4w74rPH5nnzbbq5l2yLvqlxbb5M=,tag:LkC1p5Xw+xnUSDaLWYlOuw==,type:str]
    known_hosts: ENC[AES256_GCM,data:rOpnqHcAiPYy8xmetYZUt5svZIhbLkIuafnshNBjMSKCT4mn56kM07jPeD3Hob7xABoT79a9e3k+Ol01jY92eRRuV9Y1Xl50HrEjpQGmd6zZ6Jpy5KhfOuji0vsLEyC56H+/2TWI5sMVgXIc7Tg6xBB1kB3vdOA0s2EAkDzWtWjpKHH7n4fdTu9ktyuqbxEKgJKlxTweppVV2fXnVkKcS6hX8SR++TeXcftL,iv:cLDLlcT3ayyIl9rUSHfYmFqM3Isyznwzrj9+0wtL4y4=,tag:29XPPziAXcX8C8ql1EhV/A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scrc83rw7k5a49vvmke2r87ug22a6e6vk02dqpfsxas73llz95uq8pkx4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3anRnVTFoZXNldTFlTW5o
            YU9kZHFLTE5RM3l5UUpqQmMvelY3amtRdkRnCjM5VUluTlJlZG95MEpNeVBibWVE
            K0UzSExxaDhhMGFpUGxoNzB4NVJJMEkKLS0tIGY3WUx0UmJ0b1pUdVNBdzZOL285
            eUMxcjNZUzRPRW5XTU5hYTVWYTZ3dlEKa9LWnLjVPjf6YqZgf3NZkcqaZu8uZ+Jh
            gY8IT3SlabQ0xGhrsuB5gMdL4lB673ZgPBkKT0RKV7HXCiGKUnl0LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-31T16:01:47Z"
    mac: ENC[AES256_GCM,data:MwnYDsjCFRCuoovvGZpxEFkuZ6pvbCm6GDRfuQLDnyUYUAApmUid+FzBLXGeIWpob4c+BJmvc/5gEBruu27ejUlPH2YQOmUb4EPsLnpL4Ls0e/vZwzda9Dkkb2G1DGFlYab8Rq903Mf4hEd2WqU3YJk7FtmDm1hVEEASYkq/4Sk=,iv:vyCWxs3d4Gt3+TeqholBSjpC1MOy6yLA2PHFFLrXXl8=,tag:EbAfS7gmIS9lhJlttw6hdg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
