apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5a4vVVoQEro6WGH0MjPN33MWBQKCuqW7vVSgOZ18MB9awdwIDQo+UO/hphTg+zx1l65g/Nb4Jizy9Ubg2LxvKAyhYr79g5gro80kpRTJedlsK07XxIJtIOI+GCG2N+Q+kxXXurSEV0d+racGfe1QS3AkEL3w+24zatj25Q2nNQX3N0kRP8y2lhwOKNye9q4PEOftm1HdA2qC/yXdmA/wNUFCFyIx9E3ntbmXMWXFag+EV9GNUaMP7RGyaXnXQ5gGqU4bVvNGU5pksvU3ukcjdOB3HyUuaZYlrOWRMj0u6882nFsKB1wJy8OZlzljd4K6j1AP89Vn6pavWZGg8xzxh0k6TiPQHfJ5xKTX6X9H6viAFXloB5coIsreMY90kYg1,iv:2UReQTqFfI5eUBFUim5J+UQ1womYqjvBFJDYpNH3ncs=,tag:BPPH/XDgHQRVxrXkgknMOA==,type:str]
    identity.pub: ENC[AES256_GCM,data:dAdwgRBVVuyfkSJ7cLQpj68dLB8jBJI6iW5NvvYUYh0Zhrks4CdfS6634AMroer7WKFWkvDwj355UkQzu7sVdyLab9m+kNbNLYpAGXXuQr5RKart34Xvhg554Xy/sRt3C/QmX00JCas3G5Iu9rFHoyb5BxI90TNk/D+ZZKnw75g+S5y+59fQBFFc54wfr/j2HNqUhsvKaHuMFPUnji56nVqV2Qzqw7cxW3ZHpx/s0kwTEXaQAyOGqZ7qF7AaE4whH99j6zQJD/AncaXeMQ==,iv:UK5I+0MruurRmPJtK1BaKKX1x8MvKkAPytSG8YNQaOY=,tag:PKahK/4HTID6uxeo+ZG4Jw==,type:str]
    known_hosts: ENC[AES256_GCM,data:JGA+60MJlbFQhsrG4nNEE6isyEh4NHg/FG227VAEbO5NHlbTGm9pqmyI89TfsU7DzxEZM171evbTvyhsPN8G7wlMh4DzeRyoFPVkg0GVPnWTdxpXz9QIUGxc63lcrSYYQiXbuId9tBu3y6LBHGap7J+YAEcfhcPzi771No/D1XUOMw2oeGArw+wmpbnH5XnPm6/BsanPKe3A81vkaI/jAzuVEXcOQkk/Ny8W,iv:mcgB6M3C2Zli0WPz44RJ+SRLuiaR6/iD+Fstk+lW70A=,tag:U0fTn352i7eF8hMA2vH8Bg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scrc83rw7k5a49vvmke2r87ug22a6e6vk02dqpfsxas73llz95uq8pkx4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheTFkQWM2c1NVbTZKUmtC
            Y0hMZXJLL3ZnQm1GY2RTS1FuLzhpblpOc2dzCnZGTExMWGsyS1RRSmU4WUlVbEhv
            Z0x4dnR3UVMwRFo4bEZvMnJFcHlKdHcKLS0tIHhOUVc4WUNvWVdhbWUrZFVOdDlk
            SnFVUnNkNXBabHFORGVrQ21xWmNockkKRYRXa3W4sTzrJQMaKWBxAw4s8j5sVJQL
            nsXPbYs/25+mwXCGZIIcx1MFOpd8yY7+9LxqLwiOaKDZucDaKt+wgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-25T06:10:10Z"
    mac: ENC[AES256_GCM,data:U5P1VSIhv0Wwj3xDRx86jSZojyyZe4L3eRViZvifzf5X9rGv8YzlcMP0pDiAhgcrqzZgnYCZpH1oLeSq/LWctTBR1to7XPVIqmbqZ8aPBI77YZhHu2opw/crQHP+xNneLRgGfblYeHOfGAPMVvYeUU2BcROWfmei2mC3N47YRo8=,iv:m5WPrU9424P+kZlE1o0wd0esaRyXz0h1eKrtIG26yDE=,tag:qRuwuLmNKP+EtoIfWe/sQg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
