apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:k+uSUg9hP/PCH7mrqLXAhJkddVr5ezrG47W8Cbxg1rAZ8wAIsz+fMvIAi4JVKTwbuxZoVLUuSL/zd9Eeu05Mcq7/+h0M5BPsWhcp7o7pq5V4uTujsoS+XHI9T/Crf1INwV3FPhyESYRetK6Wr8/AnrsHajub4vUA1eIOX10PtbvLoBh2t0ByzIK0DYvbWwXcM7qrEJmSEu7BH+4hfv/CYtIZrODipw6F73ywKVbj4z4HUxCGqtU5srl9EEpTrLOR2Savk5vD4M7vLd7YXBlEL37cI4qQeK2cgou5BmzSOshiP9+dIUcKxHHaDWZv5yphRmntyx6lsgaDQDN6XD89W+BKTJRfWKnoslK/QAao/GikgeIB8TSYYm1WrUAp+RD3,iv:HSWtgWSGyw9KO8Li30oTXRz4DF95Rfp+QIAhNfK8U9o=,tag:s4BS7KIhSefJTWvktQLvbQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:+038Z+Nn4UP6Xm0kPVFBX8l2JbZ/0L6eH7/uCsGfMtoWCgSK7vYifAltPTyVZcx1IlOV8D4NU5AhoiJ9SGztyJj7TjbHlp45Ad88Pvo+vboMYBmqEx3S2zXZHviblQJSDB7+bwL/MaPOeZURZoZ7aGOGjSOB8JpTE8yoLr4h95m/CSpFHjBpP7VGQDNfuIoErvisL/Jx2y5g9QJljCkltMayp2yWpU+RglqSaGJtOP14Ze1M79Ppsr+Hz1EknKLC51DnNUNE8KLUpfG6EQ==,iv:yHgDf/qfZz4yF6dTPWK3WGgfrWN5TfHb2ByJNkhi9TE=,tag:lI0bAunaZmAF8eRWeiXdmw==,type:str]
    known_hosts: ENC[AES256_GCM,data:LUQYt3Smz6r6RErFp4j/JA+jzFekBN4zjXn/i07GW8BU81sKtZz3sNUogKmdSUJsgAdqMUUaLDXgJEOKTSHCG2w/e8Pu88fOEHkLSGD7KVEON/7xSINjRTZNpEEC8DyS9niscmbD7bPGOkBF9HLYb7E4qcxx+KqiF2QX1cqRvVhDV+1vuofNFX8eaWzPRzXcH3400LAomplrGdmK5uNwdVs5sy5f9JazRIj7,iv:gnr8Jq9lKrFyNerdSii17uLwy6p5a6dtBdzUA226CK0=,tag:qmBjiOiJrEamHB3EGjTvyQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scrc83rw7k5a49vvmke2r87ug22a6e6vk02dqpfsxas73llz95uq8pkx4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeDYyT2ttMk5EbWZPU2F6
            NXBITmdqQ0ZsMGlFOHNLVXBwaHN2Nno2RWhzClI3NXB5QTh2VlNTY05lYUlzazFF
            OWFNREMwZGk5YmRSTmxKNGcwMDhMSHMKLS0tIDNRVlNTdEZIbHNkRFMvSTRDUzBP
            OVFKT2VkVFM5NTBiNk9oMUxtU0liYkkK5ZLNsWY82W+iPuhlZqH30MLf4aCQM+FA
            1AhxxVo+imAZD1o1qXFyaJkV13s4Cd8hNPCWGlIXPDROSbL72VCxag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-13T09:16:07Z"
    mac: ENC[AES256_GCM,data:5iwMEqoe7rNLfg/NFSEgGV+mtOCGYrPSLscDNxROwYvKMgH+yIzjwwfxiJcRZ49zyRFQXp6JpjsXHYmuBAXMSzFnuKHgxBQjwZquui6nWvLkyx1tNNiXCzNnO+NmXDhSeuAYvQFEH/Co//BI7+skISdAgArCSH/1CXWLGG0pVIk=,iv:JZqhdxIl8T5RahfQ4ddT2iOlsM/dkd+aX9JLMhNFqmc=,tag:PCMTockqVPWAMOBp3tljcg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
