apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:NMdPAcqunRJ1kjSXOV4CRdR7JI0QBDBdqE9aXmMPIvBR5s06pRrLOeOS4wBYe2Xuj2A64+OByK5dYrsXz63lGfm5DaqVu9p9MlF0Ax4uyjOyVfg+zOlh4LgZJ33BHDL+ycbbnGSREnZioQmdTgVyPlZyz4FgKpjJlkKWR40Vefm6d3Z3F4hSLSSONw2TSXhbbdOHj+2+NecRThAr+kHFb8QLUHX8zqmqCGrE+KiSGfTpFeBLSRTcGdVyGvuYsq/NE+tv94NnTtLZQ9cj5DGckP4fmVduonL1I24hDp3JoqQsUGM86fZb9xWOsJLqsYR2bz9gckZQETzzGVHSD0WYK9HMdps9zSCGjIf0Ca8aFZY6E0s7F51XBoWQvVuE/Rxe,iv:Il0PnVNRrSkw26Fq9k0xy/pn/n7muKigqt2jfIg1GM8=,tag:xbjApyCHGh0zpCc4IEo3fQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:FVR3JKbS0JTCu7KJMwbr2TS3kk0VwxQvxWwB+e0RZGotkaeajB2ZVQdZMr8RgsBO0X7A6K9IPqYhtk6Ef3W4YKqsv88HCrjsUr7Kajs527Y8aAPO8XOBcmMnqV0c2YP3HlWsuJbC5b0ty6ISYcbM0b321U9fh9v6lkM1cl4eiG6OSqQm997oXEbF0eULInXZ9WU+7HXxaQhCa4I5HiaB0n/103D01aroEzUxwkpnebT2vBV1rh3tPMpFNSMY3ksI9Z8RurIaRiJA9Kg5uA==,iv:t2MQt7O1b7WDtDVsdfRLA98t/x6Dik4g1Za3S0ehtTw=,tag:eOOB69h4klaxWllDBbFpxA==,type:str]
    known_hosts: ENC[AES256_GCM,data:WdptBeEbINlA3JCGfD9x8QDswgkXvuCcxlkF/r6Pg8RWF/sIac6nGKYhOdZn+48uJdZtxeOOBWBplC69JoEkLKGAuJS5v1ExNUc8pfnPXvCjQhp0PRbjr18F2j/3Zw2hI0SCUDKSH66EJ4SdLCY2n15LaeR5Huiia4HEx0dVP6+l0uQ8dA3CM3k1qL1eKnASutPRUlcH5AVBRnJ8BfIp7QngjU8S3tNvLtiF,iv:2fp1cWNswh6vEE8+KyQs9ETmFyJKiBRd+651vCkYRk8=,tag:2gtuUYc3GdqBYEMPfPNeGw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQk1UMk00KzU1RmJ3RW9v
            RU1Na1lMRlBRUHZlZUhvbDk5Vy9WOHhRelJNCnR4TlhjQU01S3pwY1BhcHM5ajJr
            NTlmQWIwRUdFWnlRNTBjQTB6elZTcTgKLS0tIExzc3crQ3B3azJkdXdEamc1cU9u
            M0FUcUNQQjRxcHBwUDNlUlR1dGZrd1EK73iqfXCm05InBRa/jVl/7p2YwtMQbgrT
            2qow8bJKqD7/ktkCSG/IVNiwROCzN5QnkUKNHpyd9d6RkotMeDl/hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T13:24:01Z"
    mac: ENC[AES256_GCM,data:dxZQw3IZJaTUYP/YmBbeTLcVXYd0WHi+/JY99lHzcbWhp0e7/Wf2xM17U0puk4TJRxE9/GHenWxJoCG4c5yO7uKBV1i/ae7voypCsL/UuGaEgBpttgPfwq+N+cvAMXKcES8kXQ+asNDlEeke4/byVCJnTpvrpohnwkTFv/+Y5Xw=,iv:KaMnTfRXIwA4VyNl18xiZCDvjyNX4+f30XJQQm5OkAs=,tag:A2VJylEpZTefhGTZ5Wt4yw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
