apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HyUYHkYdPnMk245sQ8TZt39J4e1Hhj7iZNhmB241FoDAgUQQ/h9F+IYIG7bnZHoK0ZRMRXniq9McZfgnxN44PAOy1SVLO/CJCrRhirssZG/3brhAdtvsgDQ/QFW8KTZlclpHHFK0MCTHHMQzdVTUaj5mrJ+itVjMHeQ6c6IRMZq3CAlLdCzW2cZ0ccftid7FWf5OvTaiRBBzwyvFckJyt5Hs47gRwFbyI27LriuIK91l8H3/ZgQqbAi1jQxNzNQEFxdWn7D0BEESO2UARXOk2F87tX2pr81Ws5LJ6cxy2W4GvYVXhcCBI84NciIgnCo+g+XQFTBrEvgjyJ+rZvhUrmRCbOiqWSwh61gXby0daOaj9dF2S7gX+IHCENdPXBCG,iv:TSgYFDIIKpBUZS/xUVGgW7PgZJgkf5M5zAcSRNnDWls=,tag:7fqqS4h+zamveg0d4e+4NA==,type:str]
    identity.pub: ENC[AES256_GCM,data:/F4QvU7n8psb9ff+b1y5Q8EmPg0mwt8HQ/sHcnDPoXq7Bsm98FI1vdaEgDGtajRCbYggvS05cohVssPdxaJLFg9EPqjCnOc9+1DQckVcJi9qH0FoSMxI/XKiLqTSpXN6uNOMdwkrtX+IDBK3QbQTYq5HIFTtTbi94L82mYjnMLrZ0B+L/bR62cU2l6ui31UQ5kQKAvwkSSYrr8xW0iHlvWhbXH7Uifl2NkXPbSiNO5v2IVZHDn8g7yH2CQlqeWBofyFFj94zYqaAEIyRXQ==,iv:cst/0yqEofwYfv/n7iP2tHA7dnUNrkDXJ+DwwPxNQvk=,tag:4VRln3X3RyqomdDWlMhTeQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:F03m3hMxvUryDbmNv+cDb8xCzQUkNmcdXAHrzmpY9bDnm3TWc81dSFA6YVgbfI1hcLC8hgQgGG87GUs9dxjs2EbA/G01FSFnS5bBGbsmT8h1bDw20bzPNcQqk3h2aXb9XeSJVFs3yhWMlRYuk61WxeQ+a7LXHU14/PuvoZS68L+0P1sBfNImq7C7Vn9N57CrnMdLzK4cOTSWOHc+WucBZCsuPEAgPrQ+01i6,iv:EnipHTYM+05RANHO7gs10D8lKj3WwrbXECSyqZi00Wo=,tag:8SNVRjm3LjD91zTPN19m/A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRG1sUGtQYTREQ2pnc0Va
            TExldGZaNVFvV0U2YmZNSCs4UHVxVi8zQ0ZFCndJZHNwQnpMT1FFRk5UM3YxUGNW
            azhLaXJtK0FKMnZjemN1a2pSOWgwVjgKLS0tIGtObE5oV09JVHZkWi9FcUIvak8z
            RmxnN2MvTHp5SHl5NjczSnl6SE5ENVUKwdsrYt/jJbCYxKYogrDzmZauVdN7Azoz
            prph9tShqm2VL3/paqDP7KQx96/cSaSFLpU7WRH7Tt/ccDIYPBr1wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T00:11:01Z"
    mac: ENC[AES256_GCM,data:/eNlFS/MHwW+pKOoEtSdtUbgINA8pRUERTf4I4n2ne7a3FfDRRalES0N3yofQYCZ+Q1VZsUZIJ7eTrThTBYTBmqGUF+bj21IzNSlvCfhyJZROrFAU6xYz4ncJEoBUYgGrTC9+ZvlTSrrKo8JOTLAZrYsFk2OWnJDTZyWPGUx2Tg=,iv:t5Z24QpJ7upwp5EyNSmLRLnj7hQxV1YvfaXXhnBZ/gg=,tag:4UP/+sGHz+06YNLOCQa5Nw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
