apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FPol4DHwZRfDsXWL4DLk4w+ZFTV6aplv2AEF0JtOSdiJVZIVWU74VgXQNSuuqZ7AlXqvuV17DcTLGdbfMQ2ahiuCZEZ5/BP+YFBVFFKE4nFFq1N3MA3yXRYV9fpbviMcB+xPdKYZJu70VvSQMfZIrCzEUs/Fjl4k9AZZS2Xgyvd6ElrXl7eLKXPtKOgFpvui1B0kSnRM/8fDJs6FH9vD0rZJ66QtnLEpdn1RV8FV4ppOO5Oa+w373ta0tFSsro5rY3EPzvag6kWGHOrbq/fT/unxb5B3FdAoafCWdCJXPwk5Fc3PO8fKU2Yar8X7CxN/dO0JHTcSCnv1QkE+WkaloENLqA33BKqot2jYEuOgUVzoxpK6dbiADsJ9HHZNntjj,iv:Fx7rD8S8ayDVZcOcJhOA69lVNAFVEvVmu4a6vow6DHc=,tag:GkifIl3bQtSgz0drQAXLLA==,type:str]
    identity.pub: ENC[AES256_GCM,data:wfDOJSt8/XLcDHV73Xa1i5xmP8x2n+CuzbQ1ni0IG/SsWeOTe5wl7bNgQIsPHph/gx6EBkkthIBkywrnskunuIGrM5EGzXbsWz1C7QOQ3XDUHqoT4EUrGmwh26spZe3MY5ylLQmGSOUyWIGaLrZtR3l8qQp+hyN7Tf0Kr6QWOM/2ywfxTOpTJ6rsFk2hH2D1xIyxVQGrrdSMJ7/MAnF/0D9xHkYcT6EaUm2PoeXhTGwyat8qIsa8+suApOnBJLhiqo2RqFKkirKTQOjaCA==,iv:mCXRqwpJzu5RW+DMklwLGWc4v+j0z0VsfAfRkF9D0dY=,tag:RPxhUx4NSugO7z3OYPWUIQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:s+O6xcj2EMHy9bS8151ii4q/oE5tRnH245Wo6rCHYCQmlSSFX7EBOmPFngAV6tsbzLJYfeWNJmpDBknearw2P74togPXBp/QoleqrSGZXKl35rZXXtc5aSSXMrGlOLSY1gCXIOJhzVWuxXbkjHf87nVmaXv/bZNGRrEVslXz1oQ7mQUJvfinONOGEibKcc5XasxeA02QDmBEO6DRBAtYWv5+IsfPUUzwElWY,iv:ubbyDGy8jpFbW6rVggAobPnRg5h+TjX6NT28sVyMAMI=,tag:Ob0vSi5ohi5VXtIml/yh9A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scrc83rw7k5a49vvmke2r87ug22a6e6vk02dqpfsxas73llz95uq8pkx4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUmVoK1V6UjZnZGtpWkhM
            Uzh4MXRoTlRxTFRFVldYdVhXWGlzMldJdTBzCjArc0Z1cjFka0E1Q3d5enhSRUhF
            WmtJaHhVSEZQdnNPVGJLTFZrbEhCR1kKLS0tIGZ2Z0VNdk14Q283Y05iMFZCbzJh
            UzJ1ZTkrWjRUV2FZOEkvdlk3RFRyNVkKUCguyF7qBZYcknabFRF6MWWKTvZCixyq
            Oxs/oFOhSrQvZpodPHYWDKqnZYCmy7dV5q8gkY+Qb2eniNzl5hxDzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T16:06:13Z"
    mac: ENC[AES256_GCM,data:QPyxRW9OuBF5gUdQJ9INCKBYj3u+hh+jmkfd8FVwQ02oDGATdZPxXs4H+Kf8yCS7lmnTt3rFFlxFkAHzAuqpD/CEXBSz5gqlkSdklz/h7DU51OyT8ZFhl7I/ca6HGqJhYBbZwb2U1ZEsuCLmAGPi31EiZoeDfIKwRO/2wlwo1/U=,iv:7mRjDp3nIb+Hae5XNBcY1yWT3E++scWFLjT1fzOow0U=,tag:RUCpmgmn8nw8v7rltw8Xig==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
