apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:j7yNdtWI2OUExO+ac7e3vHly1xGZEu/Gs2WNWBgomO1X8V+kLD+AEcquxA8rwQGi5u01sZEsOdUAqPwBQ1cb8M4ZfuZcDGC9Hh3ccNsnuHQ4jiv+XpjyThHIEB3osJZ9dvpnDgLMuRvXZCDZvvoQPfxyY3iVT8bEiWYfRkK+v329ESzZvZ9a5u0hWOlpRvDR7K03oL9S65acYppb6WRkvUWt9qyd1r6mj2vKE2hTNuyJgsrQjABRZyh6MA29BOPFgg+ClS6XiG5hBeWvmV2gqRFUwb0CO2vaOQ5wuR7XRDCbgwNLcgyqKVrxl9sVYA0RX+G8VyXjFdWj5cXO4yk8WTxQd3UpOy2GlKamGis5pu+aTpIJq/5VpZeZFHJ4iwyF,iv:ss0flrd2gPy68YOFwo1VuyIsCsO+pf/udJc4uGPwPaw=,tag:BwL5eVjBFTRjODM+El8g+Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:b1BWJeAcqdnYL/Kut7DAEUMIfuf4aNRgAIkutfn50YvQetaCm+jySS1n2YNpxPJAm7Tpx/JkRBx4e30wNeMNkLjfa2zZ9eHD+X3W2PGSzOosv7hMb61sdcejbMSiPViG4znKcV01SGmYQHTobqiYnnlNpMA/dc6z+tj3GvMSXnBKoR4gxj4gkbr+j1T6FDxXu7sZna+1dyGcnO6kGjKhkBBIhXjuim8ZjXjvmpneAGeneQeD8z+EFd5wUTmd6QZKTIUnHaYLaUvMLDv53w==,iv:WZIPfnMEjOimw+hmmubCx9Rqt4sR8u0YlJ4m8556M8Y=,tag:0Vvvo8gbYXsMbrNjUu87tA==,type:str]
    known_hosts: ENC[AES256_GCM,data:r4u444Y1Htvs2aEEZLllYWelhjke6ASQx67fr8QddXrbl2/zibzTJ2zX76qb8UQ1XdujTngWIcg+LQFEnWABn1LpoMp1ks3sji96kYb/RClUdmtoQzI12pJHNcOMgHDsVIDLjk4uVkTpMoCmD2j6FdD9ZuA/jY1QlMHEPruA1rmJ1UNGauSkv2L26Ds24YjP82B25AnzjpSbEOETug+LvW+YueN2YWSsIp9W,iv:kNQIg/8aucFb9w68Ol9Xf3x7gJlUaD1pV/aV+0wjXQ8=,tag:Yf2Pow9WY+7gkPBiUVmCqg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmV2o2b0t6b2loRHAvWE1h
            VjVVaDJ6cEtxdSsyRFpyQzdXNlhIajdYQUhVCmtLNmg5S0k1VUNacEpkSU5IVmRK
            S3VML1RxYVd5WXp6TkZNZGFmR2dFVG8KLS0tIE1SWHI3VXZVS09EODFFR1B4V0s5
            WGFjOWlBK2hiOFowMENRVjBXWFpBT2MKqzJrrNp6t4dDKduC1cZfH30aBYZTh2Js
            +0t7QF+nm9n5E+sgl3joj6hXfPjCFXaylCrEjE+15i/BA6S1R9d70Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-18T10:28:02Z"
    mac: ENC[AES256_GCM,data:RzjJFPQgQ4Jdy19x5EaXPFZjYK+LXYA5lK3DoO6n2kRClpY7QV6BNPGNJ0R5VDWN56bcwDKSLENPfPngUTl3gYDBm0JJk+sgwB+ivMyHVu4rNK4H0AP//jRRFx6OPT98jaA+dK6ch5YsIsd1LvYryKbZiyqr08MddGb5ppHDUR8=,iv:vOU5kTpyKK+T2/JBGdt25pxuOwuSJOMYRFpxYPpWZT8=,tag:bLBk3odSeP2RnJdKHvM2ag==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
