apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:v7Yeu9DUjipydeq20I6LJ7v6Pu0/FPXmEzysaOPlrLQaTEj9MrxZiv9YM9YR3AGAzhi4acKJOpHdP9iVwwAYkw1PobhdUt2eevDyqKVLwictCaUGEFVYg9InCCG0IS9v/8G4GeoOIu7XupUb9qHsmdJJChkCPw64/OdHPt53k/zl96k1fERbThV6Rz1O8BcmcEeZ5l86okkBDuAILHmW2Qvt2a9swejxiWusAUX68L0L5bUYFup62/eBHscL09SuVcDMNdlTS6EtP2GWsm7WR+Dh0KiFmoUZS/Hmp+xz5linzWulMZ8ZKFRpcxq7XWNHTyLOmPr8m+jKMxK568RNkzF2LDn9qJy4SEfC33XrdJ2I7PQyzDmw+SWrKa1z+zHk,iv:Gz/p3B9fVW2yOy5rLn6qI673eZjtZ9OEnhaCuIUXj+o=,tag:vgiyMssHbu+f6xXEs7uytQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:O6VlG9s19R+5E+MLQjjzFOuhBfoN7G39u2gUYUChVPttfThw0Ul57GrjvEikyfzAg4wt3bsOgfErKaHcJO4AxtUwAdK86iisXOTfmC8EuK5SYdEucyYJuvOQD8/N5B2XibAOZJ1494h1s33yuAK0PB3QJzXboZ4hG+eaotvJbUT4b0BRdCCAvAbPRDg5hhO55g+CogXm+QiJsUH8U1uUuHNGKEN2U44+I0kLPaG472+5FVcmEBMPfmPGn+YWlb5i5iTZrgV9Y47HSrDmxg==,iv:WbJY1RZNtEHn19qvLZmUawdy7DSpFRK82nroryiAQNw=,tag:Dvk5gDWu19hPgx7OjNNGnQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:+kWoIeK9jUdDi/sGwkYV8bl7dQ/CT2hMYtEuKprGexybDcxk8U1U3HMvKUPD/OZ1ymJccoidU3kpukAvy1Ioz9Ch0jq82R8mGuwFldmGDMHt2gEUh4n+N/rKOf6FJY9uOqcbMCbAjcl6ZBSWrgdLcNQ0jNcrm1mgBPVTAjTIP4iy602Md/Sx0LytmIiQZXelZVgJAHJwElzuDxkLRZ+dQYw1vISaYrl7LeRs,iv:KwQxtgfh2/MzN6uY7tQmwiEcjn2+8HKyxou7X8H00rc=,tag:IXrb0CcWNjw6/O+o0dxWNw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scrc83rw7k5a49vvmke2r87ug22a6e6vk02dqpfsxas73llz95uq8pkx4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUWxlRXdjZ2dXMjNYRS9V
            UURkcVBJeWVlZkJPbE1CaEJZajIyMzNYemg4CisxV1B4MVVtcFEvV1FXK1EyVUpT
            bm5vSjgvcWR3Z2pBUHQ2MWFCZlRYek0KLS0tIEJrUmpTTG5Fd25YUTRKbktxN3c5
            a212YjdFUFRJdmpnMjRLTWJBRWg0WkkKZLOfowXzMEq17q5te46CTr9FwvEYVn4d
            ir/ukh8/PypwesuEmrNUmM+VXCVK0X4pLg/4pW9EZTtj+Wn0cCFD6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T17:05:33Z"
    mac: ENC[AES256_GCM,data:O4TjYYx5PcRAa+bZ20U6miS+gybrZHfc3d9VmvDiHHDwIDm+Od2puz/OJA2aj/NdLlB/eB7SuGDVINUPwkdVnF9gTW4Uh5tWmY6jetsKlRNc6fM5BYFjwaHgR8WS5N/RvNC+ck2wUeeOf4XFFSwTGRFsHdU5ImbW8FlTx4Hvvzw=,iv:IGOtl0I2IHKOvSgEtY2RePmhlQXRps9ciodqPm0WGok=,tag:3E5sSmKnOn5bJZiwKFq71g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
