apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SqiYpw8k3uZUVN8H6LsxjsfprtBSqeWcISkC1Ay8ah9DJEDkqaVEZKmrDaiTFUPMlNb+F5U+xERciwCE90VvsvJ17IizBWZPtju1rNnfQtW+DWtQdeyvAB15Lq6AJl57kX4tEAwhag1cCYQ4YRbo5nHviMXqFxn/8hw3RA/m64hsCLckOYCd/0YLzLpuquJxvnuNrpn2G1D3osbKk488wRopkLWVeL472yIaGRtiDDegHl++gKjaxdYvR3472lRibjKAFCfavt5G4cELqQdqLv6dtzgjMEN/fFVMIDnCIVHvYY8icHyNVU1E2o5DpWsl+GiHxGLbo+Jw6FyVepIWkEBcQomWZ+UyrlnO0Jt3md7pmS69e+6tpAtlu5fmkWFI,iv:crohgO8KuzBWBmpxCxYyhDIJ/vSPl6t6N+iOX8qWRBw=,tag:AejHw4fGO3D0cJxZMhuKmA==,type:str]
    identity.pub: ENC[AES256_GCM,data:vvNTIhDha/cuV9nLnLgXx1nT2qbP55UYTUhW+WDroMMB5FoOL2e6hw0U+bWl2m8zTNHchgW4ZDhzwTN4KgCQaDUw19FT9b1cthFprbWP+n79VzfVH/gpKg+vLDd8msaMGBUkkAyFzyLZ5tiwQZQrmGF6/UQsHcb9GPbD1YUSuFCTc/uiBLVkOaSEM1voPVS2qbJh0Ic/dk6JhjbIz0zctp4GbwF4Nxmchr6XlXi62hsw7EXrtx4cp9Pbtgt76uu1GeJ9ANfdi0XEDqfkAA==,iv:IUBhJdLZeyfIQCjlfK+CZ9Bb9CjFwyfS8aKYEC+opxI=,tag:viBfS3TKiXvLgd/WHJf+Ug==,type:str]
    known_hosts: ENC[AES256_GCM,data:5zX3oXH4xwU47+wSPrjJPwQJlfHRhI5mUbo6cS2j+Dphuqt7fhqjpXUX0hpkGr9D80yD5rQ1z3iGDwmAnNTnJo9cX3dqBazgPiR0oBZiitzPmXf4kLROtp8InATM2BWgQnvPwLwJF9DR0bos60xMqM1P1FsTCJuqG9nf9aOwJ+6H7OB9M/8BsQp7QfsPgZrxbHpp+YriSGtDvixuS7M9cUcbQ9JI4ANnio+8,iv:lnuzNscS5H+qfhmOD0Qc1Ppxl61mL218TF4ZZa6j5e4=,tag:iAxpi8nkslCDbV4yFkw8JA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scrc83rw7k5a49vvmke2r87ug22a6e6vk02dqpfsxas73llz95uq8pkx4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZ1NEZitma011RHlabTZi
            aEM0U29pc0RPZ09odlp4RXFqdG5mbU01Q1JjCi9Wcm91bTZiL3pPR1dwOGREUTc5
            bzcwZjZyMVI4K1VQRVhFVmwrNVBVQ2MKLS0tIFZUOWwyN2xVeDdxVWpvRTJYWE9J
            S0JNTVBIZm9DNEdNd00zTk1NcmhFRjAKSjbRhtJwYG239mz45230uqAAWWCfe93D
            z9po4JcQwHow825MzZEZ4HXCR5qwDP1rfdYDx8fgvVITzOw+xbtjJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T12:11:24Z"
    mac: ENC[AES256_GCM,data:V75s3nNOyjg5fsG6YDu4EhrWT0AvcP9dLgtHnoL4SXNNwvpkLS0MVO+95b9LFwK3xmLn+j/woVnO/z4o4x3uxfbxYoM6NcC9q8DrTVGPuiEEZoSN1wvIc83D3Me8BLWrJLDO2EXL1gMDNeRPxOwqgeBcNjyX3L7eXONYshcjHmQ=,iv:4g903/GXK8cFlyIPO5tAKKXmmnwoPXjW7LyP6y7ZdLM=,tag:4fmpWyQpxyhPAXlflHcqNQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
