apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OUi4F449JHwGiblCkLMtio0bseIUj0wHi9XiVO1r/tI6M1vZ6nbpKumyugNZqg1Tp4YF6SBr4fA1NkWkwP9lReL4c64HxVMAoUlsY9KgIwEQBZ6apOrhV4WV8V20A9ztEctUE0tzYmPV/0d74sEl/eq4daWTECbDYl4eD+kufOuC/OqNhUT1igsoHPZ6Max/EKN6aXuYsUnLXLX9zWFROr21G5P1cAjCJrtz6P5/zUM39lN4+reJoXJC995l9pBcuw4MQscl6H9LzqxKqQVw4DRbkg1vOe/kO2JAWTIV3k4oF5HWQpLuDLLJPwgCEesoKVY7j6+G/j92jVhnMCVu6A4aLnX+AyfFD/taZb0R0CSbOv9/PBtsS6GOhStvS23R,iv:sEQw5jxrPT40Y3MAUkVPYSw61UNSF/N1Lcm4z2vp2NI=,tag:4gebLoEZTFD6q60mTA11gA==,type:str]
    identity.pub: ENC[AES256_GCM,data:qDjXjXaIjcfVB50rJJFCrGX1PX54dwHFDC6FaTD3Y0vyCT3OlGG34XmombU+syqBQ+ScKF138zabujaoqOo3wVSCTiIfVKPrcn64DTR6fxhQcR1h4Dduso63I8UxDOaN8+pHZQ7Q+8jf62GXnCx8mbDgYVQ6X4Pjye1ZtiyO+ce4Y+ed+mU6soyM6mja92yN0nluDpkPoOt5LlH5k5Ah+P+otbYEfKgoNS88jcAqVXJuFsC1fE9MCi+PqM/b8oRI8A1LQFLMayVu9W2/MQ==,iv:r052gHuVOi7BxqB2Zin32/VhBAVUP1djn4poPoOpjnc=,tag:hhTk10kWE6UKcFddnf1YlQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:uvLAW4rJX4tCPYlyEpG4T2AqtXwC4KVEVOcT9rh+3J0iLv/KtwDJde1RMFarpf9A5aXfpCRSee65Vf6JYGzy0wOSbdgF5cj2mtS2aj332UJ5twf9erNs+uArsAXC1cxKQ1YA7Wuoc6O87/Z/SmGOw+I52u4i7Uy+bF3Us0CigbgsTwPHuqXma/El/i1luf6RHQwiduoUYdxBkOR9xohhcEp4dAL/HJrNx4xj,iv:k3g3Ui+Thspw4OUFoZz/AoOROOMdeKzQLkqlSpC/wxU=,tag:HhnjzijHBFi39fgxGEO8+Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scrc83rw7k5a49vvmke2r87ug22a6e6vk02dqpfsxas73llz95uq8pkx4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NHkya25oZExiaS9kUS94
            bXAwV2o1QkxKakFqUkZRYkQvVzRIM2ZkeUdRCkR3RllYMWJGWVVLUzd3WjFJYm9k
            SS85TUY5SVJRZS9Ta1B6UHFXbW5adkkKLS0tIHdkQlA1TW03NEFpM1cwT2diZ3Fw
            bGlZaGxCc2hiSmRlTUVXcjdWQjl3aGsK/J50DDu8CjyDQDa+O9RhzboRarFPl3Zd
            MiAaTnlCq1X6LQ++8MfTXDm/r1yQ+gvg4oM9n29u7cUjJmm8KGkWoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T09:19:29Z"
    mac: ENC[AES256_GCM,data:EmEdwq0S1SOgX4gO5H8T53Ia0Gjlgbbzel+ZXyRE8EKbl0ivla16QBb0M82mgYgSYy2xmDIpPf6S8Llw3VgOR2MesK1TgSlzrTJhajL8oyeXUUZ44UYsXX3U93mD9Cb2leSJlqN9f17WTyplfa7Bo5WbzfYJchAFacYaiH8L1jE=,iv:Z/P/pLl4+YilU1GfmDuwzqj7gwjoednyQX6Jx67iZuU=,tag:327JLgSuJFC1dJLZhIxXCQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
