apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+yltovqnJgI/W/w1NAYUQok2IkxHK7ApJ5isTbZpNjR1cozwuwA5DoEXg63Pgt6ku5A6SwbUU88FG6XNMKrEO32Ico9E+DbwzdwFKKblM9mjVs868PivPmECGMA8VK9X0ZSl9UdMRhGHn1JI4I6I6gJsbdX/GZ+EK9d0v7vx5UKHMSowcPSfcSG+WaI7EtXOKcWHMy4b4mb5E5zHwkAoCgLRjEMbr/BLr5s4lM/l6L1dRRNPdVTYHxFz61dXH0Y9BgGRO00gXz9bmdTnUIaElAvi6xW8cxMxXGCnbg6yKfiU10xv2X0ADeQY88pvhtYFIbG0QHVGM61iiEqIMjvjP2GY37lIHqsfBMcFZNr43JJsYTcpvptlyF+96UQeolmU,iv:y5JedMuFK8XlgVhPWcPubFIH+bcjaHNKy11gSXMDPVk=,tag:e/r/u3bItYRJuzM7RqFt6A==,type:str]
    identity.pub: ENC[AES256_GCM,data:pI7A6H1LByvFXdf2AVF/naRz8rqsto//2ck+5+5i0tAw9Oy6HuKetxKxP8EkybM4DmuBmsXu2IrLmnX8zRG9g/ioy8V900aPSqAQXsEGYQGcKagex9GK/cb+xhQnHDm/3SloJleJxHfFAbzincAzAEEcsr0bYFe0n5Y9rkIM+jJmRb4cvGjKJM8NI0ssUtBonihYoymmaT6dNZPwPV6R8vWHqAiXAJ04pldpfLkWRYbxIdRDbahXk2WQsPwb+bSdvqZoRvraHXfMJOrcMA==,iv:8QCHDVwbnmKk5uuFr/IACjW5t1Pj+tTQBrqVV6HQbGM=,tag:u+wleZ3s4XaqjBs2Ry+V5g==,type:str]
    known_hosts: ENC[AES256_GCM,data:17kacr5jry8fzb3+KxrX8NDrBYIz4BRPH2MnAQzlG4r+JLEs8U1umTOGiQtsdAGDCL0YBLWVkKPlpHhl2Em4lqlDqqgFcWMWHo2KPpXZvvvcBCRUtr1J+yMrih9SsANMw/8bhShSW89QakA9es1mlBB7SmjPo9mLNxZ19ZiN06PLglDWM6G7WPrhAIyCKqRBfbwbZNLT++x0TdSQgmGRMUcSY5Qdx6h6Px64,iv:RJyC55qA1OiSOwphIHdRbZiU6B6wiKkfPwI4WYisbBA=,tag:kZTROBnwQHh+UwMZT47wSQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQ1FPY0pxWiszczlIUThz
            WUhPZ3VxTm5XcXp3MFJZZ2lQNGtKT0Jud0JRCjdDa2oyTm5hYVV4aHpZMjZySi9t
            QlNFQXJNbTM2WVR0ZXVMblNEUmsvM0UKLS0tIGZFdGRKbS9BK2FYaU1OZGN1cXV5
            aGxkRFp6WmJMYTBRbnFGRkQyWUJSTDQK2D+kBZRrvEiJyJM0/L8oTrv7/paFmMuW
            1YvtIuv4j9T82yOQwdVb6+0aXOVZ3/dklaxmSdVuPQO9mmC80shfvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T22:20:02Z"
    mac: ENC[AES256_GCM,data:7LmCNlyvWueqGsENjgmVL7ScqEzMgu/7epBn9ICQP78wR78Ds7uzXIw4cwsN94Trjw8MswsonDouFWCqr3dV3PDisLaYbtnEDSMyXQS4AQdOqy8udD8Ivhw+mqht+RCpbIVrFadPBGfZmScRwlgEn8V1kNot3GPJXxKF5HhdkYw=,iv:vi0ygh5to2c6vv7ZuVkr04o/sNIgiXkJ+3hUbudBCnc=,tag:yjTEotO0dKQCGy1z1UZYmA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
