apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hfGXVx43Uu7yd76GHF5kYMirIPKAwK6drgzE77i3bV7zPEM7vemio46Uq10L+bbPp1m0UemBw358iDvNl1jjtSGSb4za5tbDeIGqIN2bIOkMb3MTBfJ2t5iJ5Ooelwf4yT488aoe8H4TNfL844G237L6taUjkfT47jXrTnAB9RuflUETwonclY4s9HO8Sa/yQqX5eTH/amWhp0MQCBbNFfClEAHwi/YFrv/MQZ6Ke+WqGNLTFQ0QVS/wwnj/yxa6UrgjgiBga4EJVWDW/GCDOrLcAnIPKosTq058keNpGr461Q6V4CcchN4ZZhwXdCqREJft5qdomSXx5vKeJ+N42gBJRCRSTlYmGkTTf3T8A/UkH7fznQp5n9oeaVMEg+9Q,iv:W+5SYFHzzAkh6ZsfOAxCrHDlm665nAJ/ALZ1DJRkdUM=,tag:cwm2HYzq5dzeHZr768ubng==,type:str]
    identity.pub: ENC[AES256_GCM,data:JgHxjGeaKJ97GGoHcUQ3Zmv0vARoNrIweWuLnKJyZ0ITVIButpvwppvQ2wcRmxUi5W8+Y/b/G7bjJaHKwucsRiEhccxBMQwkSj+2R4nhxkOvg6PHE7Z39d45E6zNOiaTBtCEr3dkQzWSotncsoMzTvYovdmztZBpWLuXs+shd7Hx4M2kkQSyXtOSuSrhsi0lZ+a3lEQRlWsg39+2ENkhAf8LI4DsDJXoFPFYQk0sTtDs9ncxdBiEEP1k97fcn4zsAdhQRgFn7sNIf4vD1A==,iv:SFa8sRDbYNOZ8jEf0UUux2KnVJYDYum6Tc+so/e/k+U=,tag:UFLJy6DCEI49dFJJweHJHw==,type:str]
    known_hosts: ENC[AES256_GCM,data:XIdmc6fds9DL0Fx3dBt6a/9PumUy14CXDJPASP21H/MeYeh+ENgPKzkL9kpivaYiiPlwCkr3rTow3heWNLKrAxAGuwIUvXlAI+QOuWpgznV6OhpExmFQavTkiA63wTnaHBOlvNKSSq7cRd2igCu8gA7AeDDBadHdVSIAkAxjFZZcOIkwBXt8z1r3pfxt4iqGLrj5NDlkm5gnQJAjNJFGflCDiyxCJw2NgVgn,iv:UnrBrLIXPQzFzNp3M06vmoph5rz+iyLO1zR7SDSRwmA=,tag:GQizYGiopIcd9UshLmlJhA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwc1FmVHI1NVY1V0NyYUNY
            K29KcGs0RXYzMW81VHU0dFpsWm4rV1RXcVg0CmhrVW8yVEVieDRUWi9WZDFlcEx4
            VW5rUXdSMEpNRDBNaG9DMkVRODllS2MKLS0tIDdrYVhtU2dJa3NMSEh5VGJMSnNz
            M1lRbytNeDM4RlFwUDVURVZDdjhPUFUKvT0W8dmyNywOUilbvJUso9gwLNO7u0eg
            yQcG5ZoMvuSt4/JtRi7NrJzCRWrt+nMoI5Hlp3tAsWuFXXUTgXMVmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T19:27:22Z"
    mac: ENC[AES256_GCM,data:Dzs6oWrDBSgJcNVAE2HPes4G/X9ATrEGuKrDAoHRPXqmP5Gh0Z8nWSyf16bSpt1zYtTXRoWn7JEXNBXodQ+0ftB26GDi1Oc7lE/TPC4JZ6nyhiFjdQoMGr0OTCV3GGUkKYaZwc8NGvwzid7CR9/WXknGj7w5TrFWYWL4h0hrWwg=,iv:cZZyk0b3hCTcyGlsPj8QlssGcQobp5OxqDioTqDIHuM=,tag:SNi8PSImvYuLPhjFqIEV0w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
