apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qhBtCHa7IT9SbHf5iPNnvZ+PjsVS+WLtBwczWRrX4u/TxPJpfqAqrCUzhJlBLUblp9umXkiUxkmPhRzQnULh8CvG+zWyXshamyB8zEgAR4cGupAeoH46U5/IS0psLajOhOg7ulxRQl6ZJk7pXuzgz5CrA1DSq2WmA+f2tbWlxcpTTgHqEpLvhValjjjDmS1FRx4+DSdwRcJeABTTT4vdmQG4wOZrbbXcqtilXkpyAlh+7dbw8B/AW0TLg+Hm14+eJaEtr6loGKolM8oFCUrm8I7t26o+A22TONrT9K+v4ncQIZWxsz7tlo/PDXfBgTXHvDWN+ZmMh0P0nXeU9XhPztAHVmLPlzs8wug2duWRTswssLuU97FG9bLXRp8QnJCH,iv:gIvHTJDdpIH6yVEIOpZlw6NisHywaNiP/AHdMYNojzw=,tag:6B3b0uffiVYH1vGwaDEiGg==,type:str]
    identity.pub: ENC[AES256_GCM,data:DmNvt++7irnCLdtk1sFxl4qyJesgRIpnXSZBM5fBz9oxctx0TvKGboG1vH7f8+Ia/cY/f3T5VBQPmYxvcsGuQ4hl3HCZYRgkCD0e0ZSKGte1sUDKAyoO/OlS0f0+ediPfVcv3Vj12+UgromGlwJ8y/R5OiRWI/pb/ji8ZuTpG7rRbyAMoCBk57WAneNJpMB7kZTCKP2VmiCwBgdufPBOHtij5D3gjhIXqekOeWOgKPknOTkhuoY4sM+drtRqpxVBmEI2JM1B9LnSuglizQ==,iv:5TMpe3JWkbuYAo1fkBJIR4tFXykJ78jc0/9iybFjxhE=,tag:hsh8JR6xO6M8hdIWXB4yHA==,type:str]
    known_hosts: ENC[AES256_GCM,data:vNcLANidLTxtUQwa+I6A8Iqeuaq22dW4zRoyeUX+Be2oVZmybtjk03G+55yV/cM5ZaDw4PB7iRlunV+JGbHw68m2Nxq0beVAnDzh0vRTTREQrxSWdl30lii94bjo3vv8fKKMQP4GdpE9RfWWSVrhxXXJOUXkhXTy3dZe6N/E4U1g1os3fp8JUmp9xhELkSKAJpxEzqc/+VTM7PX/HgXgmcixbni29AQoxWqZ,iv:Rn+JvZtinmr3QlDghrD3BmFEMWq5tWEIndG8i/SxSJU=,tag:j1v/CRaArAM9+7YYTIrYhw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVR1JVaVQ5T2lOSWZPdnU1
            cmxnMCt4UFZ6eGNFWlRoRnBtZVk2VytHSkVFCndzU3JlTnRNbDZYSG80d1A1R2I1
            YVpNRGVyUEdveFRlUW9BTnhFeVNGWEUKLS0tIGV0VzJjWmtTRVJDY2F5Y3l4dUZ2
            eU1RZHVwUU8yKzZldGFJNThFMWNDNUkKHpnlGEO9E8Uml5zooVA6/dfvEYumZ3aP
            ewOp7bcG/eG7cxlWPx4sZiiEMJcbQ3vrKhFpCstXskIYdpda4eBImA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T19:29:32Z"
    mac: ENC[AES256_GCM,data:7TMzfXIldJ/AQ3wHW6XQLTJhFZi7+4pmgRv7Nhz369L2O+igPLTqyvbk7n/M8xbOv1ln/imcfrJjgthstLrdlWoH/vWEoQxdi9eMNqybhEuepMDSiaaBjvg/akjXQApQYpfj6GzJrnNz8adBgsy0xUK9bZnjdoIsWhHRKWhtsmo=,iv:pdIMf4J7rq2oJCQCjNameds9fj2p+kH28dOXLdkSbWM=,tag:9FfXELRodmkn5h/zqwQ1jg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
