apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tUnRQpGPRM6z4z/m+t5AXvq93h+4lq1YpDEZ8w3nmbxHLO02/VSImPrVhMpM6/7lhPAkgZD7YCyDTqgGb7Z10BtYMyt4UJMQYj7melBQGc2c5RkBdpHMmRBhjvnLyAp73FYSVgFomrlffZ0oZdMfxRG70UU6zNiwVKUsaGc0X1EBF+NgQcs4A65JncAmi/GnxxVP2Bn8mZpzBNhuuByz6FRE1ZyBFC8wN0RYkrpj6F2c5NtJ7NmOl7S/jDPAyMSbPSnUsXXSOhV66oVB4jOSVM1qechxRvyEm4VXfiY5ziCLyFLHp3mIypOowp54d0Ou+m3wa6aAnilkGQS53OdTnj6Xl3Np9dYNqmuaTfTTco5WG01QEe8qDT5pOzolF98X,iv:wVAb8qjKcJRz3JBt5IJFqoNxmf0GY7Vf2TAMyaFXv0Y=,tag:s1w25xGzZMpYxRqO+V5PMg==,type:str]
    identity.pub: ENC[AES256_GCM,data:HAYQxPDQdK+yANGB4Fp8vY5BmawN83qet+2Z+gYs9Hk6u3XwpIuL93uG7M3j7VS6PD8TYcA1GuN06atGi2tpcYnyMnNH3fWwCfUhG8+ikjNu7glWbwNsJErCg1VN6Y8tlKjuxu+woipaYkyGOukTtBXWlgK+/5iyZulqS6sKJ0y3ymbwNBOJ0iJr15Rr51iDkP1K8/DuwkwopArnpYQtEdx29J3wGxCz6IY8XpVWkOntju32M0ifJkA7Jw/0TpKUkQqjwSyZj0aSrvVIBw==,iv:lmi4rZRwoMxEEA3FmlzODR7/DjmQGmqCEZpU9nPdiXM=,tag:lA875pWWrXJ5gTRIRDkH9g==,type:str]
    known_hosts: ENC[AES256_GCM,data:Pwk8d/m2VrMUCCMIAPvuW5rGnVoVo7Tkj/WefleuIS5Oqb7JIyHczztAYlnqCAOjSaEFCBcecGgn2FZlAboatZ4yVYL0BTv5sameB/HHEF11cv9ey9GKeXNtXqWIxchtzNIUyMcdXIBtqeLbmeqA/dLXTOEnjKBvthouqsNKgBS3cpPc9t48cZ0H9fHkcFYJszK9nbZx0kbODz8YGyW9HWaFq/XwBJLO/O5d,iv:62E1OBK4/I2v/zll9X7QWHCnSqAI2B05/xiKWa9fKpg=,tag:4N1HT8F62VYwrY+sSg1fgA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scrc83rw7k5a49vvmke2r87ug22a6e6vk02dqpfsxas73llz95uq8pkx4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNjN5ek02cTBtbXVrQ2Fr
            VE0wc09HQkIxanRLazBqQkFIVjJ3MmkxelRVClowSlMwYjZTYkFtK2xGa1pUZHVq
            NUNXcHBWcmc2Vm5WR202VUlzL3FNdWsKLS0tIHVoZFJKL1ppaVl3RzVuT1F2SlFJ
            ZGdZMlc5bVQrWEc0cTNGdFErZ1h0OTAKFViKlbiWMM/Lnpse3rC95HsKHEv/G0ca
            zn4Yh6SDgnBgxYB5ub+Bbvli6pW+BNko00JjPpBUlPYT4XWfDdYMrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T20:05:06Z"
    mac: ENC[AES256_GCM,data:muw7IKkA2nhUvwPrgmgvNgxvy/ENb8ryqQNiUFlfyZdky9DE9pepuzLKzas7qTNrCph/jAX6gHXSQVU+XrKxV2pkGbdS6gnLII5fwjgNxst0Gv1Sclb6f1loRcPfphKY409v8aGhY/KwQ5dK8H2cA9ZQ3kY0PRdcd4i3XJ1xd+8=,iv:L+VaWRH9QcxXyQcHTlyJogPMyGkKuKOfjqS2Z+tK9Fg=,tag:awwtHWkrwm3gV/8/a6IyNA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
