apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vIrLBkwBNBnP7HEjh7R9QN+4pzGJ/WT3Zx5F6EP85kgh4Vn/WoebuwUXFNLgRYvODLfKMtHxgpUMfcQ3TJufW5ipBAz+Zh5fj9VenSlKt9h2UeRtOomStM8vAqrKuXrSfbEK943ASp3v1wXAhzqi+D5s7V6wJSuO3RwhCKtUZ9fKATXIovEOr5LZqD1MZylLAgVaWmibw1ZDE49V37+JREeuK1pZtGONIckn2sWLDsUG45dCEiixesh2exH26n3qSllcvY2N0h3SGdCfgImaRt8ogVGcSAMPRGCWeQCqH7lcjNl4d8IUT7qxXKBg/MxjDL3zy52kmE76/N2ljmGe5r7F50FCegx4ENFneKgcCi86vuuQLs+xxs/FXtUjckzT,iv:AmQ3zUfkucoyxx+sxaZTO+Nj3/O9BmzM9I9jhJgvHes=,tag:l1EFYUduOJyhsKaQrnCYKw==,type:str]
    identity.pub: ENC[AES256_GCM,data:h1pgYefCIokciKyIGwYnxRQSPNw7h42drNtp+IN+BQl7AwKBZAlUyveMFmWxz07cKc1xHsD+f2UmMOrzLDXnzY+U7Clj1auWg6GJFcJwa65ULHTau3gAyH+ROVsmQr9icv0zMej9KLDy5IxFsvGgedC6urKZtWRFFWwzxkU4hTMBEkkb5RxY13/f0rMkZjP+lfkMElqmwKyFTn0PW/Af1cPJuKW3gEkKNo1nw8NIX6t3FcyICeOQ9PrdHC9NIgdq8N8XLS3PXsb9qkk7Gg==,iv:l+1EvDboVdnZVfXkA+Z93kL4iChnkvlfQPm2Q4bhahQ=,tag:EezwI/yQzMGhJPwnfJO/pw==,type:str]
    known_hosts: ENC[AES256_GCM,data:kriQ00I36a6/Bs7WOceZKirNf472bf6q4gnXl7y2lm2To7HSuV5STL3eF62lQmgpaBvUGKhCZqe2WiLm83mmUWAdrMz5ernWudI/QbpRlCVvFbyKW1VZpPWjYOH7b8Ocrl0IXtlXG7/hG5E3mMmLkoEiuq0+oe9rheZcJORnavAfUrpXTXo83r66bmASziNXoWX0k3zWtX/La+DNwFlDJgWeu6AbiaeIrqG7,iv:sTyj+uvhA8cskRLyi9kX7DFEQNarIjM0DuI9I/ANDzs=,tag:EGYHSh1t5UOOX09EcyVBNQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTXk1S0xpSVNOV2h3SUV1
            cjFDTEx5Mytpc2ZFQ2QwR1JhMnFaUWpQYUE0Cjl4V2FPZ3lraWwyclBqcVRsSjVK
            aDVnR2NndVdUR3hNa0xZelM0MW1CTFkKLS0tIHVaOHFxaHJFYnVKand3QVlTSHQy
            dGd4d2piTTVrM0tLQVBsVG83ZFRsY2MKjLcqGuxgRhyaoPTRFA7C9Rsz7ak0nZW3
            tNOKzgDg/87lORVwBRn8lEw6O2tbCPtFIUAGc1tu/Xu/1c1RLldEUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T16:29:11Z"
    mac: ENC[AES256_GCM,data:RyO+e+3/DYWaCAjAE7QPXtFB82vX+/6Im1ZqTMRvv91HkNf5CLeTshJuBGVlUIQQTV0v85nhYtSZPLkrGFeiih3FALRhkJHhB+LO3rZu8/4yA5UhimCW8kiGK+HRHmxgLF6VPjr6NvQSeRu3fj25dx4sq4epqJniF+Z7DOW25KQ=,iv:1NKWLsqgn5iKhBUetV5mS+CmdUCDzo2tOnBsdF64RkE=,tag:Ja+LuLcUdyFg0ixVzrOYTw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
