apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:lXidOkK07sjIu4PDuKVddvP7a0C/a9StkfAGGdXmgj2/Y7WVTuUHEZOxc1XEft62uBxDD7db6NR0jkT8+xzuUMO5rtMRC7Vnk7g3Mz3hai0hwxwEMB+/aOnRAF13mvEeo/9l+r94HcuJcKHU44ah3ii3mGl/2wSwfVNBTKCqXcD5nSyoteVKemzLLkwjql/RT8vCXYT66SSIP2yLLDvlYv1naYBTez0Sz08t1ah1oEOdGp0zJWD9PM8I5wtV7D+pjEgoaBKfg3ybbMaLZJRIxSR65Mv4CX88H+7NU2fUtFkLDV64weEa0HzFagO8R5Kj1Kr9mfydzK+mJE3R5uAIHu7/kHQEz3raxtAjr4wPCVDku+7mPF4Ecl19QwvOV1su,iv:YbGh1DbkTTv/iSWZ08pm/gVTkpH2ujgze/BQqeV8NnM=,tag:CPXAe2PtMrcvN3hq1cYPww==,type:str]
    identity.pub: ENC[AES256_GCM,data:/RZt0zELE4x178PD6qyOB93Zw3EKLHMrRv/vkJJCUK3DfWRVizR8nLOoNcwnU4lDdhAKRvv+97JPfOy+SpBViVIqkI+OmqiIuPu3XiW57o/oV8yYko+tAeifFpW8wVIXNb/G0lUoG0OsQgxyhsDtqL1FreAMXPuEDIz6n7oaogFMPpUtDk9Mke5Gk/nq/gdzxzEIzhHj9joJ+LEjRb608E7FJ+GohofMmleHmIRjSfxNYZ8gWKIhJkidV5fmlWjY2XazcKsJwi768v9vJw==,iv:aviiRKaw5kLrsvyRGwYRncUUMFisC/+4ScnNVwH1jI8=,tag:cKC/Bt6A9fiKe1vBKetbDA==,type:str]
    known_hosts: ENC[AES256_GCM,data:U+RgZFx+7OTYMLl7aW2TlqY+Xq2wLCMbRX4l2phcCjDwVF9oI21lctyzwWb2GkZF915XppEkJjRP9uknys2gBdpM9o6M1R/3dRl5JHdGK99QBAEEr9pqej7aSpEU/QDePivX1d3kdrd/z/0Wto6AuwUoETQzbEzPz90gqrb7ZtxdiBaANVhG5wXDuG696WcPo9vdJdgdTsMOAjiqJertaC9OCuhlwm/+5Qfr,iv:NbhDo2f5ks59FWaLujdK4mbQRMe6IeS5yjq4Ca69+1E=,tag:bJPD/of1obdJ5oAYkke1ww==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scrc83rw7k5a49vvmke2r87ug22a6e6vk02dqpfsxas73llz95uq8pkx4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTC8rY1JIN2dGa1Avc05J
            Wkg4b044Q25BOU4vWXF5M3JTc20wdHlqcUEwCndScFdDQUs0L2ZLVlRXcHo5bitT
            OEdaM2FBSjBDbWVLalB3MVlWOU5JSmMKLS0tIDR1dnQzemFYajF5R3RNMEdQTVN4
            SnhXNXJHdGY4MjhYcldxbXlXVVRxVzQKBl8YLKxww6Bl49KxP15JlaZxzv0695J1
            ut4GA7lApF/PEBguBKwyDsgpsRFxY1b/7dQYBPK+UYV9RibjhpFV1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T16:43:13Z"
    mac: ENC[AES256_GCM,data:9cNqGJNgoVsC0AhP/SXuXtJ2ofrPU2QsExPCmttCH2DwYKZ8IwpZBgGJfLZRP6zjJukuxIULAfK5l0H82QDlRq6VggEzeoVV5WjSlNsgzB2O/PxD3HH+VZSGWBDEfwAezYYio+qMvKW7xuHv3Ev6bt0Z5ccuY7gI6S5nkv1j2ag=,iv:XyR+gwNPhU9FPRq7l6tfTwEPzUNgBCCLIkmC0xBJBNk=,tag:VfC82K/2jvj10D45atTcaQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
