apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7JdEKPywGJWj/VU85s6ypjEQWDcZ7DwnjPkhcUV1TNQK8PSyyI/yB+5dd+C7U4pVNrzdQsDZNwH8RaHxRPJS9Y74nZHe1Qp6nRtZ3AmMrsYSEzYV0BTmHfPGiEWv6ViApfdJjRVXjU17W07TmBF/E3WcSXIO919q+oUGThXaEGsviUaR0NYqD/1KsvGCud6cmn+fot5GTgyVJXHDqtJSpw8VpHTEu0hKagzL0P3Ei+z+k8QJ8qMA3b7Mnw93K9BUwb9Eu51diQgb2JHNLVPg7mvRmUUXxLfcFz6xysxPD1m/2PI06k5qJCU61pavqm9t6NeSFGheRvSN9p6TVdR61k1b/WfsOOOwyioDCd7uF8mXufN9h0XzsLQESc3d0QhR,iv:/N+0PZRp8/hYAFuPyX7ZMoNZDoz6TXBARmXJry6ijxg=,tag:RNJh+rOIAFB/AlEboUfLFA==,type:str]
    identity.pub: ENC[AES256_GCM,data:HQRX0znlHypcE/66kFYhG3/nsGIxN5ByU/L4lAirCJ/JB70PulMHEG+WnlQvQdJobLmpcrYfQ4eKop0d5NR7Hxjv/xWc9iKzCd7ojTuo7E0otPt/pLgjq/whMgeUwhiPj0YYBSHtjM7uMNkmMQmAv6YEYCpge8ygDoZI6KmgMVxYux2OmFvzUepLkFSaT1YaXdBKQuNbZ+jsySNu5YxlaL4aIGKgvxSHByzXb2TNj7sYVv/Be9UosLhUKR6geDc3acWmAvm2dwajRu6O/A==,iv:DlmGXlmB5EADLpdCQ01dMY1eNbdEDxUUvAzwXi5zGHc=,tag:90JIbhklEYSlP8l+iBOdXw==,type:str]
    known_hosts: ENC[AES256_GCM,data:PGorAohzExJAgyy+QpvHlcIgd9aMDoSCjyWMq7luQfyR3VKkMt9v5K2EZgxvqGIRrlhsH45Ti57tO32rtotLWVm7EcHEZjPThFDiFA8E0VbzPFtQGg5uoQUwGphyqTpyBe/vbReWGIURJGOLKsiDNT1PwNnOttJ+AN/hVuNGQGX8UClVFcP0EGC1JMMp2FyzUeuxDVH0EUEDmgeeztfBv1GcUZ7oQausIaxU,iv:85w4cJJPIs8CMCHnov+LXplhvF7COjbz33NbwyfOW0I=,tag:fh4fqotn0EVecvw3vO5e3w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSHNYWUtkRW1WTUMyWEJx
            YjJmeEFkMWlVQ0lndU1sd3lXN01waDREbUNjCmdhMW5tN2EwQm1uaStHREdtSEFq
            NzIvakhPa1BDT3BVR2ZPL1IvM3JTbE0KLS0tIHhvUWJKSi82dkZIcDNIM0ZTeHc2
            RFBkUklNLysrancxUm5pNjM2ZjhsMjAK00r0GFMkJemTn31wnUcByLuKwycVmnaP
            F7y0N9MMIJ7KgPlY1OUmaJwJgh3TLtrB2OL9mcV47UdTlz8vwtMNMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T10:08:55Z"
    mac: ENC[AES256_GCM,data:SjhcTcZPlgdLfBr4Xdjc3ZOfvghgFmlZwAF7mkoqyaCP0Kgt/XbiOf0mbRAR0V0cxOIsDOBmJoO9iHlhiRaoDRKRG5O+d5g4XAtpIvdOzUoEBdq2EhhzORU9t3qZrGdTFQYsMvD/xFOHF2kvfXODn6n2Xq452mGr475+1hBY0/I=,iv:jxQGP+E82NwRT0Z9hLgvIYR1KsvejPZp4FQtJPf5k1k=,tag:Q3MkC3HNQ1mIOz1Yt4jmiQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
