apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:s2glAN2gT4beTW2OdKlUOVNEXcgA9f/3wwKGzd82HG16CbtpJ/ZDSPvN1xttqJP66TMlJ549IvB9pnPMghI32twPli9/d8nfHQDAWGBPwArBFFjfxejS7gt5caP4OTQYn4fBa2+J/l1q+187btzEvUbZjnDvSImsqonp3CRGtquDuyfQDqwIcDAnX69B5cxFD71rjK/2ZFClZn2z/UU3Ry+qbrrpNC1oWLv8SBt59AcXdMXZv7z+4C4HXLamAFMrsHfgIj1qOmQFJ0w7+6eBBR2SXdqcQdTAz2oNxmjYW+aq0MmGLf61TE/rwYOc+bJdu668xOhFtCdriL7cSvUMJ0z1rwe6fCKgDw9K/JqmcbK4NLSwFh5ioeBvMUQTLcpW,iv:OZOeylGCfk4PqFOud2cKSz1JkDJXZmMfGKZFKG9I5o4=,tag:HCy18cj1airs58ENlpD4GA==,type:str]
    identity.pub: ENC[AES256_GCM,data:gs1heb+dlhWY11p57e0R5XfmJ+IoDqkRqFDe3CfkCmRNC+TzrJRuPjxFMBqVB5XW6X7KhFu9I6RfphqFts8+f0BzBI09vE6DnHR9i7j0T6XctGjK6MFuEu73SZGaFBEJj1OgcpksLcvR/0GNj/IshHr982riluB+TRaFH/HObFJVoeclW/TPKeZVqMZBprDbTaf328Ce1VmiiGBomnNFaXpDp5vYNh+Zxq15+Z8sfjk2JrPTMaC2STNl2MI3DiQ/OyqnG77zlF6h3GeD3w==,iv:ObcKS2i36uUUobyltd0ulE0w/pzYNQClyvPJX1sFBpM=,tag:eykbq2b6MMIreTC4xU/nWw==,type:str]
    known_hosts: ENC[AES256_GCM,data:gjAATc2XPs75GzNMcoQVoysDht9tMrSfijPZt78gY/GU1khdCiWp05eqZTmzIfcNvL/bPU51r7tt2hOmURmmin01mMfGCYQDOpwi0aPt1yo4faWIJvi9i4TwLCSIbb7HhvcdfjcB3Slk9VvrqG7v+YGP0DgluSbO37PDuM++xAcsbE0ws4rWhGTUIJ3Y3QQDw+YKmtlAKF7JyPK4NJV80t8x3M2mt+uomcvp,iv:bYpKoAuy6FhqmT8WDeFQ340R1nYVDIUv8gAdyCfFg+Q=,tag:kY5Sdcd/NM6XOltkM70gwQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5N1hkV3FJL1RVTDI1TGJv
            Q2FLYkZrNGl3SHlrOHArMFIvVUY1RE9LQkc4CkNsUWlJejZHSnpGRWRZTUxTUVEv
            czBBaUNDalZ0T2FWZ3BMczhScVVJRmsKLS0tIDdiaDlFWG91MVZnRGYwUFRjcHNi
            WkQ1eGE5Q2U0bDd5N2o2bmRHRjlRT0UKXvJQrv+R1YdPGoVTIa/LNUzqPZKXvtCY
            G4H8puexrXg1Lfe8QhsiUHKbHVPy3ZEkQo2ZHZmtPDBqfOgNsil9zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T11:54:54Z"
    mac: ENC[AES256_GCM,data:cOgv2lSO809oHsJD7nODK0lw8vlp+pCCfx1Rh/iK1ZQDeeURczLjkLckKN4v9yHEYGwnbQyk0bTyO+2EUt2VhM/bxiP0YeS/kHG7icotxE0EBKpsNQ5uCTmlaXFUmXIvwFzeviAnDiAEnv/kdsLOs0LWR0CQPctCS4rez80WZGA=,iv:xQQDdCkmkXulobE/0aACBSN6GxdGh9yErDyB6dzjOmI=,tag:lOoOKrU7NtVSkZ3jB/h/6g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
