apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xP02BqZ34/sbNxWco80DYYLwU/pnDrKQgTMWMb0G1hFiIRoIw9Y5BZd+CzXMdF/FbmcQMOpO0+KqQbXlJSLymyI1pzLG1nD2vNOR+THKy1BxwIHu9ZpJVPJ+skrtsoxaQeMUuCMwQiKn/4UP+Fuy8qIwPmNTm1AcPSDTBCoVnhSQe+lfjJiDTk/35F5NDK4DEF009VI6+7ZtZi+nW6EwLiNjz8BiWkOthmboWUE7YZE9sQHnErxKjWHqvFg8mNKy4/tsswf6ML3WkVVYSP3+Z/hvWyO6G2iQOw0axsI5V+Uo7lXhSllNa2ltj4qYIG01yOTUX5ARz8ckn8ptkpAKt3499gRx65ucTtbsKm77c+vyztj6ty03uYxaQlPU3+R8,iv:+9ND+Y0mgA1zB2IAq7/rZkFEEBEjmCyF1c9ViRPEVPk=,tag:POlArSzeKdc0Ct52lYX3EA==,type:str]
    identity.pub: ENC[AES256_GCM,data:i0zgffrz/hcOIbVnRUsVXqs3iL30qLnYw2Y6V9nqGLgNrQgjrag9U3ZAbaAwgmT/2Gaa54Vn5/fewMw3NO1JEHnnMtuhlu32uxG0ia8l8gUDC3PtLNhylRdDU1o2x058Jd4+TEO1NdjPcp01BK7m3ux31EkvfE07wJB+Ojt1ohOQzTdB4wZ4naaxOVv4w/M/T3oUMITY2WOny5TWdVnf5+Xpw/U1Z3rDqvM/ES2aooVWjmMDfy8e0ntubFzFC73LhdBTdx2vbc07z86s5g==,iv:cSbz1sA1Q5pLjk2x4SJJyCE7Uy6nMHQ998R91F5GprI=,tag:7ud0WTFoW9SGYwnM0Kf0mg==,type:str]
    known_hosts: ENC[AES256_GCM,data:cB9w7JPQEX1Oeb8BA6Hv0mDP4kYMpWwiiO2mGnPtgKc54053AAKJUK/Gi8WXtms3KLGmS42TbJINWU8mIKnm74NfYKgb1JYH06FaS8ktQz1DeV6mGmFktzxLRBmJ1ZhhedcZK9y3BEY+PMMK9B/aqXx0RZs7cuF7+9mgmf3cUmbCKR3QkAUSIplqOWwhZlSHd9EYqaicdOaAzMfexP8GGWcgv+DWZDi753QT,iv:uqPSw4UYzejNAU0q7J5Rx58Zi8KrjcWFlPV2eValcGw=,tag:NDH0hH6/xxuMt99buDE3OQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scrc83rw7k5a49vvmke2r87ug22a6e6vk02dqpfsxas73llz95uq8pkx4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVk45ZUt5dTlRcUtXOFJB
            M0ZoT0lJd1hnb3VaRnZYTjZOaGllaC9JTEJVClY3VEJlM1VpRnpsWXlFdFFBR0RE
            cTd5NHF1MkVTVHkrN3BtRHpDRDJHMUUKLS0tIGUvbTU1NTNjdGd4UmNUQTJDYzNp
            TURFUXUxdXZDcFFmalhQdHlrWVJVVmcKHID+D03FDyl4TeUajE5PcOHH2EzshX3U
            36WwXRXk3pdl5m48LvJXHkDuSi4dRuTs9zRbNxElk8gSfLS59/4wuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T15:57:32Z"
    mac: ENC[AES256_GCM,data:UKyAUl1s5PSxugWADsdyU1QTHl0hqWCV3/Ej+6UZzHn89p7029SNU29yotCS+n0tDOVPbKCd6BAo2+EMLu+3viC+KWAfmQOOTLAmCdxemzArpprX9VrXCzkyK0jng1i5PIyVhZwcvOXJVPjHKzFhduKbOQN0LZUWyO4yviZHMIM=,iv:Sdga0e9xZ1pOiLtH2KJiRx2X51OKyUqAvgsulqZuF7w=,tag:vZuHrwo9wY3rHGh3npBmGg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
