apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:BLruFLaVMclI9WXjbPIPom2XqJLJv2YhOIWQ9OqIZq9rxf6YEe6vBeQkgDDJuwJO8zyQYaJest8EYgk/zWC7fPl+pnof+qSZUbFe8wXSyI4VJhVPzsA9zwjVT9eZ6HNjeODy7TppJeBltbykv+1V+Chbe7sq84tRTGRlCX5PeyvYidxk1xG8zXxdT+9oOe26L3D0fvCn/wIqkW5upLio4iQwaUT59C/UR5NKmaoLTEoJCtx0428CJDYO0nTnAXMLpUKDbMdtgcE/JJ30IXUlIKTVyYgo3Rrhv6Zcc+UGYgjgN0KvFFl7y2xzVtcrCu379QzgtC/rxcpf4rrJggrRxqY1uq3/Gbzx2mu+uFMnx3WzPjUh/Any0/yDwlILVIsR,iv:suwf5tM9BKADz2+qyDZ+cggJEQYejmZK8fcaXf0EYzI=,tag:PCTGXhf0JeBgMjL8rq98Ew==,type:str]
    identity.pub: ENC[AES256_GCM,data:ru6fK+Vz7LO4SVIU5T4GlghWvnKPuv7Nzc5a9yAxkISMJ0Rmimypb0LiXyfXnwQIspjJ9g4JtHE+VSNWSRt9ssA08Y4dMhABInqc0zS/n6lrRwiCSuuAaPWeAjN5d5EovCso/+hCYLEEf4rrfqJL52gKYUa5Mej/yRPw68uCbgaZE2icJLkiVB6PWnZaT4HVW/smEd9y1O2EbIOKnKwgtSLmY64f0VXu6cBRoQSORLKLCM/nxMUTHvNZh1s+np2oOlzKW/RygZujmcygPw==,iv:DHtk/WyOMofbAOM9Y18LTRfQOCYmO+OjVjysYESPbmc=,tag:hvA8ELnIi2wJ+fwmMsTbog==,type:str]
    known_hosts: ENC[AES256_GCM,data:NGET0BZ8zhL/hQkkEd6XPVsTebh9ZTfX6dz2cve4CRfgcMOPA+h7XDXpiYW8EMjg7NbQz4StFYIExsPFtQExuubhBmULC7Plgh6mmxgKBduzrSocgnrC9aahEIeaSqijkSQzwyOwg3E7m6bHvuA04W4FPmRpZsfl8eSLi9ZN216XjIsc+covts8QSV4Ik8YPezw0EfsPmYq6o6M3SHY+vGh6tgmQ0VF6jZOL,iv:QIAuoxC1R1ZWAxy7Pz4f3RsomtY0fJNZYxjFiUnfUh4=,tag:SQ55KnLOVKaxV+VBward0A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MU1JdXJpbkNxT1VwcVpp
            VjA3KzVYZzVZSU91OGYvbndjYWVaak5yTzNJCkhNT0l6aXBUY0wzWmc2MVhXenpr
            ZkJ3QW5oNEcyRFUxY1MvOUxkV0NUQnMKLS0tIEgveWw2SzVoYklBdTlqQ09tZGJP
            NWhadjZKblhTVGNROXdqc1k3cE5TdUEKwYbdPLPXM8sNXuJYvd+1/CZNTDEsKYrN
            afksaxJuiaGAtLRYqVzYA43xlaW3zeuNjMbDfHuiZS7BxChpSZ+tag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T21:28:34Z"
    mac: ENC[AES256_GCM,data:xCRzpBoc0XcWlOYO27mjniTcbO004NLk0OJNr0iW1/RL38+XM3DkZpXESY75WfZS+eoTB0SsF+To6m3f1KUz+SxP88p/1MdfakVz62iQoNOnmwElU6UgXS9K3PjY5qXpGN8TE28X5w6nnKzQQZBrVmTyqERBloPUF23nEk6g5sw=,iv:0Pd9iEuiDQQ6TumaLAGJLhn+olC7ag6Zc15ACmTw74I=,tag:UX4yVSiv25m4Ag79VTBIfw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
