apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:z8SQC7ydVGdf5GIFit9deeMJFJH3azaHnGGRj+j5FHThU+LtGx6u7EZ5QoD7yhWs19aGzf/G79DORGQzQJsshYujh+CeABk5oY4bUXC3Vu6vM2aeGFHZprFmX3uX48H3IE/VDcg0D8qnxGki+Z6aL1QMxMNhFo/jeJ/cXJ0bJu19BkotfMQxf5RtYSS4VXWh4dlO6O/d35sgWvGx6quksONwJax6eEy2v3YZPAxaG2suHNknzjnbrr0+kAZsabnygVwaUfeKita9htWq/tNj4SNW4m/Yb13Lxn/HxwsdRjwF90kT5K9i6lWR6MZyvI+tkDbOcybZpY9Cak0R7z1ArUXgObzJE7CKv1xxVLln/XeJhx0o6MYoi/MEQSjn5fEU,iv:uRqxnrHf8b7qm+EFzE95nBPjkKuSsbHKYHsf8W2FB+0=,tag:Ui9w7ucIxQAcPU15BP+szA==,type:str]
    identity.pub: ENC[AES256_GCM,data:JgO1YTlMxtx/BwsXgB5Chy34WFbgbt/1ZzWQBKqcyMq7MOgdnPDr0Bq3ah5iiRuKmCuT9LeHyeIb+SexN9tC9sMSchb+yIxUOOiTo/uvvbBaSJyJW2KDiMaCp6hWP7b9CC/QmyCnUS6S619sWOK6t5QW+VDz770rW/6YmM7oVgcN6lh7AXLr7ggu4fPqNGUQHpuatusD3Qd5SXXl8fa53umvvU5I9N9e9UZeHpQ8o5f5sYpb/sCqwK1x9mp5mtok1q8qtRi3dXo3ZvC/fA==,iv:6daWsDROH/xqnGSfdUNeD0+Dr41Atd+MaRXzadEVrro=,tag:yXfKMQz4Qu1+mvFVbDpCqw==,type:str]
    known_hosts: ENC[AES256_GCM,data:dLXZn/vGxTkmzjDuZU9gQQUJH4Ud2MmpeXO3vsesO5mV1/rJtaZpqOwbuIAW6CfxSz3E+aKCCW7I5t/KtfuhjkpDhN5YMOteXyWgk0uteecjMins9QA6xJcDwYAEwqEvGtmjErVqe9X7kWt4yQOP39m0q2+C9IgsOKOFMgbyd9JjslgY7I26rPbCMTOGP0PylfMVhio8O5GFEHVH9S61IO8xKut9q4jHcQwY,iv:iIJonWIS74RK/3EH/xprxV9HhMQepMjjnkUm9gy/kFo=,tag:LfKULawJFmnCjd/ASaFMkQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfkd8k0rqt5ln2s779kxmzxmaltr2ulqk0kmk7fgrmd3jdl9spcs9h4pw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTVovKzVBajk4Q1lldkJU
            M21LU0doTVVYMkE2RGpFMUpkMTlYZFkyWWt3CmY0Q2c4OUc2S21ub3FUWENWTGIz
            Z2xMaEhXTmV1VldTdTZqZ0ptWWlhQncKLS0tIHVJSWNNV1FVcmQrWHpURlA4bGQ2
            Tm5HMWp6cHZlMTVmcDBvVkdiRWJCTUEKAhZ40smlbmTarMdpQ4KGZoW5PyX12CUT
            87KDeeDRI6EtyzEU81tRoqHw4laKeBKqL24g1ja+QkAKllqAGKYuLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T19:51:16Z"
    mac: ENC[AES256_GCM,data:8es/Gtk1EiA1Xwx+piZD19y9oR+4zgKLonNpkQqw8py4xqB8eFyr9HarT0menGqtCqFJFcDShA4pUNf79KXMTQeJprNTOThmLvyvIZd2wzsmMgQRrdeWHQPKKI7EnzK2VcruSadc83aBAKZMUHX7a0WluJNWpxxftWHsZeT0ijY=,iv:pk5jBIIbJV5o7kgeWpoE6FjUyLoHTnUFNhesdYkRHt4=,tag:WCUHbLNjtMwsL7ufPOV7cg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
