---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefox
  namespace: firefox
spec:
  interval: 15m
  chart:
    spec:
      chart: firefox
      version: 19.0.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        type: ExternalIP
#        loadBalancerIP: 10.242.10.51
        externalIP: 10.242.10.52
