---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 9.3.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    addons:
      codeserver:
        enabled: true
        service:
          ports:
            codeserver:
              port: 12321
          type: LoadBalancer
          loadBalancerIP: ${HOMEPAGE_IP}
    credentials:
      backblaze:
        accessKey: "${B2_ACCESSKEY}"
        bucket: "${B2_BUCKET}"
        encrKey: "${B2_ENCRKEY}"
        secretKey: "${B2_SECRETKEY}"
        type: s3
        url: "${B2_URL}"
    forceConfigFromValues: false
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: false
    securityContext:
      container:
        PUID: 568
        UMASK: "0022"
        runAsUser: 568
        runAsGroup: 568
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
        privileged: false
      pod:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${HOMEPAGE_IP}
        ports:
          main:
            port: 80
#      main:
#        enabled: true
#        ports:
#          main:
#            port: 10352
#            protocol: http
#            targetPort: 3000
#        type: ClusterIP

# TODO -- enable ingress
#        ingress:
#            main:
#                enabled: true
#                hosts:
#                    - host: homepage.musson-lan.uk
#                      paths:
#                        - path: /
#                          pathType: Prefix
#                ingressClassName: ""
#                integrations:
#                    certManager:
#                        certificateIssuer: cloudflare-prod
#                        enabled: true
#                    homepage:
#                        enabled: false
#                    traefik:
#                        allowCors: false
#                        enabled: true
#                        entrypoints:
#                            - websecure
#                        middlewares:
#                            - name: allowlist-private
#                              namespace: ""