---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 9.3.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    addons:
      codeserver:
        enabled: true
        service:
          ports:
            codeserver:
              port: 12321
          type: ClusterIP
        ingress:
          enabled: true
          hosts:
            - host: homepage-vs.${BASE_DOMAIN}
              path:
                - path: /
                  pathType: Prefix
          integrations:
            certManager:
              enabled: true
              certificateIssuer: cloudflare-prod
            traefik:
              enabled: true
              entrypoints:
                - websecure
              middlewares:
                - name: "allowlist-private"
                  namespace: "traefik"
    credentials:
      backblaze:
        accessKey: "${B2_ACCESSKEY}"
        bucket: "${B2_BUCKET}"
        encrKey: "${B2_ENCRKEY}"
        secretKey: "${B2_SECRETKEY}"
        type: s3
        url: "${B2_URL}"
    forceConfigFromValues: false
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
    securityContext:
      container:
        PUID: 568
        UMASK: "0022"
        runAsUser: 568
        runAsGroup: 568
      pod:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        type: ClusterIP
        ports:
          main:
            port: 80
    ingress:
      main:
        enabled: true
        hosts:
          - host: homepage.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: "cloudflare-prod"
            enabled: true
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: "allowlist-private"
                namespace: "traefik"