---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 8.0.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    addons:
      codeserver:
        enabled: true
      service:
        ports:
          codeserver:
            port: 36107
        type: ClusterIP
    credentials:
      backblaze:
        accessKey: "${B2_ACCESSKEY}"
        bucket: "${B2_BUCKET}"
        encrKey: "${B2_ENCRKEY}"
        secretKey: "${B2_SECRETKEY}"
        type: s3
        url: "${B2_URL}"
    persistence:
#      bookmarks-config:
#        enabled: '{{ not .Values.forceConfigFromValues }}'
#        mountPath: /dummy-config/bookmarks.yaml
#        objectName: config
#        readOnly: true
#        subPath: bookmarks.yaml
#        targetSelector:
#          main: {}
#        type: configmap
      config:
        volsync:
          - name: b2
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: false
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${HOMEPAGE_IP}
        ports:
          main:
            port: 80
#      main:
#        enabled: true
#        ports:
#          main:
#            port: 10352
#            protocol: http
#            targetPort: 3000
#        type: ClusterIP

# TODO -- enable ingress
#        ingress:
#            main:
#                enabled: true
#                hosts:
#                    - host: homepage.musson-lan.uk
#                      paths:
#                        - path: /
#                          pathType: Prefix
#                ingressClassName: ""
#                integrations:
#                    certManager:
#                        certificateIssuer: cloudflare-prod
#                        enabled: true
#                    homepage:
#                        enabled: false
#                    traefik:
#                        allowCors: false
#                        enabled: true
#                        entrypoints:
#                            - websecure
#                        middlewares:
#                            - name: allowlist-private
#                              namespace: ""