---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: makemkv
  namespace: makemkv
spec:
  interval: 15m
  chart:
    spec:
      chart: makemkv
      version: 11.0.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      backblaze:
        accessKey: "${B2_ACCESSKEY}"
        bucket: "${B2_BUCKET}"
        encrKey: "${B2_ENCRKEY}"
        name: backblaze
        secretKey: "${B2_SECRETKEY}"
        type: s3
        url: "${B2_URL}"
    ingress:
      main:
        enabled: true
        hosts:
          - host: makemkv.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: cloudflare-prod
            enabled: true
          homepage:
            enabled: true
            group: Ripping
            widget:
              enabled: false
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: allowlist-private
                namespace: "traefik"
    makemkv:
      AUTO_DISC_RIPPER: false
      AUTO_DISC_RIPPER_BD_MODE: mkv
      AUTO_DISC_RIPPER_EJECT: false
      AUTO_DISC_RIPPER_FORCE_UNIQUE_OUTPUT_DIR: false
      AUTO_DISC_RIPPER_INTERVAL: 5
      AUTO_DISC_RIPPER_MAKEMKV_PROFILE: ""
      AUTO_DISC_RIPPER_NO_GUI_PROGRESS: false
      AUTO_DISC_RIPPER_PARALLEL_RIP: false
      DARK_MODE: true
      DISPLAY_HEIGHT: 768
      DISPLAY_WIDTH: 1280
      ENABLE_CJK_FONT: false
      KEEP_APP_RUNNING: true
      MAKEMKV_KEY: "${MAKEMKV_KEY}"
      SECURE_CONNECTION: false
    persistence:
      config:
        enabled: true
        mountPath: /config
        volsync:
          - name: config
            credentials: backblaze
            type: restic
            dest:
              enabled: true
            src:
              enabled: false
      movies:
        enabled: true
        mountPath: /mnt/movies
        path: "/mnt/pool0/movies/"
        server: "${PLUTO_IP}"
        type: nfs

# USB DEVICE
# Host Device Path: /dev/disk/by-id/ata-MATSHITABD-MLT_UJ265_WR54_035519
# Container Device Path: /dev/dvd