metadata:
    name: uptime-kuma
    namespace: uptime-kuma
spec:
    interval: 15m
    chart:
        spec:
            chart: uptime-kuma
            version: 11.0.8
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: uptime-kuma
    values:
        TZ: Europe/London
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        credentials:
            backblaze:
                accessKey: REPLACED
                bucket: Pluto-JTM
                encrKey: REPLACED
                name: backblaze
                path: ""
                secretKey: REPLACED
                type: s3
                url: https://s3.us-west-001.backblazeb2.com
        ingress:
            main:
                enabled: true
                hosts:
                    - host: uptime-kuma.musson-lan.uk
                      paths:
                        - path: /
                          pathType: Prefix
                    - host: status.musson-serv.uk
                      paths:
                        - path: /
                          pathType: Prefix
                ingressClassName: ""
                integrations:
                    certManager:
                        certificateIssuer: cloudflare-prod
                        enabled: true
                    homepage:
                        description: ""
                        enabled: true
                        group: Monitoring
                        icon: ""
                        name: ""
                        widget:
                            custom:
                                key: ""
                            enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        metrics:
            main:
                enabled: true
                endpoints:
                    - path: /metrics
                      port: main
                prometheusRule:
                    enabled: true
                type: servicemonitor
        persistence:
            config:
                enabled: true
                mountPath: /app/data
                readOnly: false
                storageClass: ""
                volsync:
                    - credentials: backblaze
                      dest:
                        enabled: false
                      name: config
                      src:
                        enabled: true
                      type: restic
        release_name: uptime-kuma
        resources:
            limits:
                cpu: 8000m
                memory: 10Gi
        security:
            PUID: 0
        securityContext:
            container:
                UMASK: "0022"
                runAsGroup: 0
                runAsNonRoot: false
                runAsUser: 0
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                ports:
                    main:
                        port: 3001
                type: ClusterIP
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                UPTIME_KUMA_PORT: '{{ .Values.service.main.ports.main.port }}'
                replicas: 1
                type: Deployment
