metadata:
    name: cert-manager
    namespace: cert-manager
spec:
    interval: 15m
    chart:
        spec:
            chart: cert-manager
            version: 5.0.4
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: cert-manager
    values:
        certmanager:
            dns01RecursiveNameservers: 1.1.1.1:53,1.0.0.1:53
            dns01RecursiveNameserversOnly: false
            enableCertificateOwnerRef: true
            installCRDs: true
            prometheus:
                enabled: true
                servicemonitor:
                    enabled: true
        configmap:
            dashboard:
                data:
                    cert-manager.json: '{{ .Files.Get "dashboard.json" | indent 8 }}'
                enabled: true
                labels:
                    grafana_dashboard: "1"
        operator:
            register: true
        release_name: cert-manager
        service:
            main:
                enabled: false
                ports:
                    main:
                        enabled: false
        workload:
            main:
                enabled: false
