---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metube
  namespace: metube
spec:
  interval: 15m
  chart:
    spec:
      chart: metube
      version: 14.7.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 30m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      backblaze:
        accessKey: "${B2_ACCESSKEY}"
        bucket: "${B2_BUCKET}"
        encrKey: "${B2_ENCRKEY}"
        name: backblaze
        secretKey: "${B2_SECRETKEY}"
        type: s3
        url: "${B2_URL}"
    ingress:
      main:
        enabled: true
        hosts:
          - host: metube.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: cloudflare-prod
            enabled: true
          homepage:
            enabled: true
            group: Ripping
            widget:
              enabled: false
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: allowlist-private
                namespace: "traefik"
    persistence:
      config:
        volsync:
          - name: config
            credentials: backblaze
            type: restic
            dest:
              enabled: false
            src:
              enabled: false
      downloads:
        path: /mnt/pool0/movies/_MakeMKV_Out
        server: "${PLUTO_IP}"
        type: nfs
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                DEFAULT_THEME: "dark"
                OUTPUT_TEMPLATE: "%(title)s [%(id)s].%(ext)s"
                YTDL_OPTIONS: '{"writesubtitles":true,"subtitleslangs":["en","-live_chat"],"updatetime":false,"postprocessors":[{"key":"FFmpegEmbedSubtitle","already_have_subtitle":false},{"key":"FFmpegMetadata","add_chapters":true}]}'