---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 29.3.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
#    ingress:
#      main:
#        enabled: true
#        integrations:
#          traefik:
#            enabled: true
#            middlewares:
#              - name: allowlist-private
#                namespace: traefik
#          certManager:
#            enabled: true
#            certificateIssuer: cloudflare-prod
#        hosts:
#          - host: traefik.${BASE_DOMAIN}
#            paths:
#              - path: /
#                pathType: Prefix
    middlewares:
      basicAuth:
        - name: authKubernetesDashboard
          users:
            - username: "${EMAIL1}"
              password: "${KS_DASHBOARD_PASSWORD}"
      ipWhiteList:
        - name: allowlist-private
          ipStrategy:
            depth: 0
          sourceRange:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
    service:
      main:
        type: LoadBalancer
      tcp:
        loadBalancerIP: ${TRAEFIK_IP}
        externalTrafficPolicy: Local
        ports:
          web:
            enabled: true
            port: 80
            protocol: http
            redirectTo: websecure
          websecure:
            enabled: true
            port: 443
            protocol: https