---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clusterissuer
  namespace: clusterissuer
spec:
  interval: 15m
  chart:
    spec:
      chart: clusterissuer
      version: 8.0.12
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    clusterIssuer:
      ACME:
        - cfapikey: ""
          cfapitoken: "${CF_API_TOKEN}"
          email: "${EMAIL1}"
          name: cloudflare-prod
          server: https://acme-v02.api.letsencrypt.org/directory
          type: cloudflare
      selfSigned:
        enabled: false
        name: selfsigned
      operator:
        cert-manager:
          namespace: cert-manager