---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 15m
  chart:
    spec:
      chart: home-assistant
      version: 26.8.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 45m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/London
    credentials:
      backblaze:
        accessKey: "${B2_ACCESSKEY}"
        bucket: "${B2_BUCKET}"
        encrKey: "${B2_ENCRKEY}"
        name: backblaze
        secretKey: "${B2_SECRETKEY}"
        type: s3
        url: "${B2_URL}"
    addons:
      codeserver:
        enabled: true
        service:
          ports:
            codeserver:
              port: 12321
          type: ClusterIP
        ingress:
          enabled: true
          hosts:
            - host: hass-vs.${BASE_DOMAIN}
              path:
                - path: /
                  pathType: Prefix
          integrations:
            certManager:
              enabled: true
              certificateIssuer: cloudflare-prod
            traefik:
              enabled: true
              entrypoints:
                - websecure
              middlewares:
                - name: "allowlist-private"
                  namespace: "traefik"
    cnpg:
      main:
        mode: recovery
        backups:
          credentials: backblaze
          revision: "1"
        recovery:
          method: object_store
          revision: 
          credentials: backblaze
        database: "home-assistant"
        password: "PLACEHOLDERPASSWORD"
        pgVersion: 16
        user: "home-assistant"
    ingress:
      main:
        enabled: true
        hosts:
          - host: hass.${BASE_DOMAIN_EXT}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: cloudflare-prod
            enabled: true
          homepage:
            enabled: true
            group: Smart home
            widget:
              custom:
                key: ${HOMEASSISTANT_API_KEY}
              customkv:
                - key: fields
                  value: '["people_home", "lights_on"]'
              enabled: true
          traefik:
            enabled: true
            entrypoints:
              - websecure
    persistence:
      config:
        enabled: true
        volsync:
          - name: app-config
            credentials: backblaze
            type: restic
            dest:
              enabled: true
            src:
              enabled: true
    service:
      main:
        enabled: true
#       loadBalancerIP: "${HASS_IP}"
        type: ClusterIP
    homeassistant:
      trusted_proxies:
        - 172.16.0.0/16
        - 172.17.0.0/16