metadata:
    name: scrutiny
    namespace: scrutiny
spec:
    interval: 15m
    chart:
        spec:
            chart: scrutiny
            version: 11.0.8
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: scrutiny
    values:
        TZ: Europe/London
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        credentials:
            backblaze:
                accessKey: REPLACED
                bucket: Pluto-JTM
                encrKey: REPLACED
                name: backblaze
                path: ""
                secretKey: REPLACED
                type: s3
                url: https://s3.us-west-001.backblazeb2.com
        ingress:
            main:
                enabled: true
                hosts:
                    - host: scrutiny.musson-lan.uk
                      paths:
                        - path: /
                          pathType: Prefix
                ingressClassName: ""
                integrations:
                    certManager:
                        certificateIssuer: cloudflare-prod
                        enabled: true
                    homepage:
                        description: ""
                        enabled: true
                        group: Network - Performance
                        icon: ""
                        name: ""
                        widget:
                            custom:
                                key: ""
                            enabled: true
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: allowlist-private
                              namespace: ""
        persistence:
            config:
                enabled: true
                mountPath: /opt/scrutiny/config
                readOnly: false
                storageClass: ""
                volsync:
                    - credentials: backblaze
                      dest:
                        enabled: false
                      name: config
                      src:
                        enabled: true
                      type: restic
            influxdb:
                enabled: true
                mountPath: /opt/scrutiny/influxdb
                readOnly: false
                storageClass: ""
                volsync:
                    - credentials: backblaze
                      dest:
                        enabled: false
                      name: influxdb
                      src:
                        enabled: true
                      type: restic
            udev:
                enabled: true
                hostPath: /run/udev
                mountPath: /run/udev
                readOnly: true
                type: hostPath
            varrun:
                enabled: true
        release_name: scrutiny
        resources:
            limits:
                memory: 4Gi
        securityContext:
            container:
                UMASK: "0022"
                allowPrivilegeEscalation: true
                capabilities:
                    add:
                        - SYS_RAWIO
                        - SYS_ADMIN
                privileged: true
                readOnlyRootFilesystem: false
                runAsGroup: 0
                runAsNonRoot: false
                runAsUser: 0
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                ports:
                    main:
                        port: 10151
                        targetPort: 8080
                type: ClusterIP
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                COLLECTOR_CRON_SCHEDULE: 0 0 * * *
                                COLLECTOR_HOST_ID: TrueNAS Scale
                            probes:
                                liveness:
                                    path: /api/health
                                readiness:
                                    path: /api/health
                                startup:
                                    path: /api/health
                replicas: 1
                type: Deployment
